### ISSUE TITLE
Changes Requested for AppCenter

### ISSUE THREAD

**Issue by cassidyjames** [phase1geo/Minder#1]
Hey @phase1geo, thanks for submitting Minder to AppCenter. After a review, we have some changes to request before it can be published to users:

- [ ] Screenshots [must use elementary defaults](https://github.com/elementary/houston/wiki/Before-You-Publish#appdata-and-oars)

  > Your appdata.xml file must contain a screenshot tag that references a screenshot of your app with elementary OS default settings including the GTK stylesheet, icons, window button position, etc.

Some suggestions, while not required for publishing:
- [ ] [Don't use the word "Application" in your .desktop file](https://elementary.io/docs/human-interface-guidelines#genericname)
  
  > You should not include articles (the, a, an) or the words "program," "app," or "application" in your app's generic name.

**Comment by phase1geo** [comment]
Thanks! I will get both of these issues fixed and create a new release for your review.

**Comment by phase1geo** [comment]
Issue has been addressed in 1.0.1
