### ISSUE TITLE
Error: Updating icon cache

### ISSUE THREAD

**Issue by btd1337** [phase1geo/Minder#10]
```
Updating icon cache...
Traceback (most recent call last):
  File "/home/arch/Repositories/Minder/meson/post_install.py", line 13, in <module>
    subprocess.call(['update-icon-caches', hicolordir], shell=False)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'update-icon-caches': 'update-icon-caches'
FAILED: meson-install 
/usr/bin/python /usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed. 
```

**Comment by phase1geo** [comment]
Updating the icon cache is something that I've had a hard time resolving with Travis CI. By making your proposed change, Travis CI builds fail (at least for Loki) for some reason. I changed this from gtk-update-icon-cache to the update-icon-caches specifically to work around this build problem which seems to make Travis CI happy. I would like to know why this fails in that environment before committing this change to the main branch.

**Comment by btd1337** [comment]
I think that this action is executed automatically in post-install. It see like others elementary applications are coded.

https://github.com/danrabbit/lookbook/blob/master/meson/post_install.py

https://github.com/danrabbit/harvey/blob/master/meson/post_install.py

https://github.com/RonnyDo/Wammer/blob/master/meson/post_install.py

**Comment by btd1337** [comment]
@phase1geo Roberto sees how the sequeler codes this action of update icon cache:

https://github.com/Alecaddd/sequeler/blob/master/meson/post_install.py

**Comment by phase1geo** [comment]
These projects don’t have custom icons that are used within the application. Their only icons are the ones used by the OS to represent the application. Minder has a number of custom icons used within its interface. If I don’t update the icon cache, the custom icons within the application are displayed as the default icon.

**Comment by phase1geo** [comment]
I have gone ahead and merged this change. If there are issues going forward, I’ll bring those up with the CI team.
