### ISSUE TITLE
A Lot of Unstability in 1.5

### ISSUE THREAD

**Issue by Fatih20** [phase1geo/Minder#100]
In some cases, I can't open the app outright, other times, the app crash when I need to open another minder file. Also, if I go to the file manager, click a minder file and chose to open with minder, the app won't open. It just flashes but nothing happen.

**Comment by phase1geo** [comment]
I will need your help triaging the issues here. If you start Minder from the command-line using gdb, we should be able to run the application and get a stacktrace when the application crashes. Is that something you can do?

**Comment by Fatih20** [comment]
Give me instruction on how to do it.

**Comment by phase1geo** [comment]
1. Open the terminal application.
2. At the prompt, type: gdb com.github.phase1geo.minder
3. At the gdb prompt, type: run

At this point, the application will run, allowing you to use it as normal; however, if the gdb output in the terminal displays a prompt, you will need to enter the command “where” at the gdb prompt and provide its output in this issue. Leave the application running as I may have you continue its run based on the output you provide.

**Comment by Fatih20** [comment]
https://drive.google.com/open?id=1Hpgc_R6VqLe-y4qy6Rq1VmnxV0dTHtyB
Here's a video recording because there are much to unpack. Also, the gdb output :
`fatih@fatih-Workstation:~$ gdb com.github.phase1geo.minder
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from com.github.phase1geo.minder...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/com.github.phase1geo.minder 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe807f700 (LWP 12675)]
[New Thread 0x7fffe787e700 (LWP 12676)]
[New Thread 0x7fffe65f3700 (LWP 12677)]
I/O warning : failed to load external entity "/home/fatih/.local/share/minder/custom_themes.xml"

(com.github.phase1geo.minder:12671): GLib-GObject-WARNING **: 21:12:23.313: invalid cast from 'DrawArea' to 'GtkWindow'

Thread 1 "com.github.phas" received signal SIGSEGV, Segmentation fault.
0x00005555555de675 in ?? ()
(gdb) stop
`

**Comment by phase1geo** [comment]
Okay, that first issue is not the reason for the app crash, at the gdb prompt, type: c

This will continue the run, we may need to do this a few times to get to the real reason for failure.

**Comment by Fatih20** [comment]
`gdb com.github.phase1geo.minder
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from com.github.phase1geo.minder...(no debugging symbols found)...done.
(gdb) c
The program is not being run.
(gdb) run
Starting program: /usr/bin/com.github.phase1geo.minder 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe807f700 (LWP 13441)]
[New Thread 0x7fffe787e700 (LWP 13442)]
[New Thread 0x7fffe65f3700 (LWP 13443)]
I/O warning : failed to load external entity "/home/fatih/.local/share/minder/custom_themes.xml"

(com.github.phase1geo.minder:13437): GLib-GObject-WARNING **: 21:27:38.983: invalid cast from 'DrawArea' to 'GtkWindow'

Thread 1 "com.github.phas" received signal SIGSEGV, Segmentation fault.
0x00005555555de675 in ?? ()
(gdb) c
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) [Thread 0x7fffe65f3700 (LWP 13443) exited]
[Thread 0x7fffe787e700 (LWP 13442) exited]
[Thread 0x7fffe807f700 (LWP 13441) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.`

**Comment by phase1geo** [comment]
Okay, rerun this again and when you see the segmentation fault message, enter: where

Send me the output of that command.

**Comment by Fatih20** [comment]
>Thread 1 "com.github.phas" received signal SIGSEGV, Segmentation fault.
0x00005555555de675 in ?? ()
(gdb) where
#0  0x00005555555de675 in  ()
#1  0x00005555555e1bdc in  ()
#2  0x00005555555bcf12 in  ()
#3  0x00007ffff7b9110d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff7ba405e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff7bac715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff7bad12f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00005555555e1e78 in  ()
#8  0x000055555559dd2e in  ()
#9  0x000055555559492f in  ()
#10 0x00005555555bb47d in  ()
#11 0x0000555555586222 in  ()
#12 0x00007ffff7b9110d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff7ba3de8 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff7bac715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff7bad12f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff6d04b95 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007ffff6d04da6 in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x0000555555586701 in  ()
#19 0x00007ffff4eb7b97 in __libc_start_main (main=
    0x555555565790, argc=1, argv=0x7fffffffdcd8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdcc8) at ../csu/libc-start.c:310
#20 0x00005555555657ca in  ()

**Comment by phase1geo** [comment]
This dump information is missing debug symbols so I won’t be able to triage the problem using gdb.

So let’s try something else...

In terminal, run the following commands (each command is going to be prefixed with the > character but this character should not be entered in the terminal.

> cp -r ~/.local/share/minder ~/.local/share/minder.old
> rm ~/.local/share/minder/*

This last command may produce an error/warning about not being able to remove an images directory within the ~/.local/share/minder directory, but ignore that for now.

Afterwards, try running Minder again. Does the app still crash on start up? If not, try creating a quick mind map without opening an existing file (doesn’t need to be anything important — this is just for test purposes).  Once you have created some nodes, try exiting the application and restarting.  Any issues with doing that?  Does the sample mindmap that you created display properly?  If the answer is yes, try opening an existing mind map in the standard way.  If the application crashes at that point, was the Minder file you were attempting to open created by 1.5.0 or was it created with a previous version?

Let me know how the above experiment works for you.

**Comment by Fatih20** [comment]
No, it was created before 1.5.0 since the app can't even be used currently.
Yes, after the first command it stopped crashing (on my laptop, not my main machine, I haven't tried). The second command returned this :
>rm: cannot remove '/home/fatih/.local/share/minder/images': Is a directory

**Comment by phase1geo** [comment]
Yes, that is the warning/error message I was referring to. That’s okay.

So after running Minder with your ~/.local/share/minder directory cleared out, Minder is usable? After that, have you tried to create a test mindmap, exit the application and start it again?

**Comment by Fatih20** [comment]
Yes, it's now usable. Thank you.

**Comment by phase1geo** [comment]
Is it okay to close out this issue then?

**Comment by Fatih20** [comment]
Yes. But perhaps you should put a link to this. Maybe someone else is having these problem too.
