### ISSUE TITLE
Include note in export

### ISSUE THREAD

**Issue by bepolymathe** [phase1geo/Minder#101]
Hi,

It would be great if you can add a option to include note in export (and note only the structure). 
;-)

**Comment by phase1geo** [comment]
Which export format are you missing the note information?

**Comment by bepolymathe** [comment]
Text and markdown for example (maybe Org mode related to a precedent post)

**Comment by phase1geo** [comment]
I just checked and text and Markdown formats should both have note information included already. The CSV format is currently missing note information, however.

What is VUE? Could you provide me a link to where to find it?

**Comment by bepolymathe** [comment]
Oh... i have to check for text and markdown. 
VUE is a concept mapping software.
[vue.tufts.edu](vue.tufts.edu)

**Comment by bepolymathe** [comment]
Okay, let me tell you a little bit more. 

I mentioned VUE because it is a useful software that has allowed many students, researchers... to do concept mapping. The difficulty with mind mapping software (compared to concept mapping) is that it requires a hierarchical approach to the organization of ideas. VUE is powerful but it is no longer maintained and aged. Could Minder become a replacement (even partial)?

I like Minder because it is beautiful (it's important!), well integrated with Gnome..... and especially because it allows you to "detach" knots. If we could consider putting tags to nodes, then exports in csv.... it would go in that direction. 
It's an idea... that goes a little beyond the question I was asking earlier. 

Translated with www.DeepL.com/Translator

**Comment by bepolymathe** [comment]
And yes you're right, it actually works for exporting notes to markdown and txt... why it didn't work before... I don't know. Impossible to reproduce.

**Comment by phase1geo** [comment]
I'm going to close out this issue as Minder had notes added to the CSV in a previous version.  If there is something else related to this bug that is unresolved, feel free to reopen the issue or open a new issue.
