### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by gibranlp** [phase1geo/Minder#103]
You know what would rock?

A feature to randomize some nodes colors

Let me explain, i have a node with 10 subnodes obviously all of these are the same color, a "randomize child nodes colors" would be awesome.

Cheers!

**Comment by phase1geo** [comment]
I have added a new feature to Minder that is accessible through the contextual menus.  If you select one or more nodes and then right-click to bring up the contextual menu, there is a new "Link color" submenu that provides a "Randomize color" option.  So to randomize all of the child nodes of a node, select all of the children nodes by control-clicking on the parent node, right-click and select "Randomize colors".  Colors should be randomized, leaving the node selection in place (so you can re-randomize as many times as you like).  Link color randomization is also undo/redo-able.

**Comment by phase1geo** [comment]
This feature is committed to the development branch and will be generally available in the next stable release.

**Comment by phase1geo** [comment]
This feature has been implemented in the 1.7.0 stable release.  Closing request.
