### ISSUE TITLE
Not Opening

### ISSUE THREAD

**Issue by gibranlp** [phase1geo/Minder#106]
Hello,

Yesterday minder was working fine, but today everytime i try to open it, gives me this:

(com.github.phase1geo.minder:5078): GLib-GObject-WARNING **: 18:28:16.486: invalid cast from 'DrawArea' to 'GtkWindow'
[1]    5078 segmentation fault  com.github.phase1geo.minder

Any clue?

**Comment by phase1geo** [comment]
I don't have any immediate ideas. If you have Minder source downloaded, you should be able to go to the main Minder directory and run './app debug'. This should run the application under the gdb debugger. Once you get a prompt in the terminal, you should be able to enter 'c' to allow the application to run. You may need to enter 'c' at the terminal a few more times before the application segfaults. At this point, enter the gdb command 'where' at the gdb prompt to get a stack trace. You can add that output to this bug and I can figure out what is going on.

**Comment by gibranlp** [comment]
This is the entire output, not sure if a i did right though.

The Meson build system
Version: 0.49.2
Source dir: /home/gibranlp/Downloads/Minder-master
Build dir: /home/gibranlp/Downloads/Minder-master/build
Build type: native build
Project name: com.github.phase1geo.minder
Project version: 1.5.0
Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Native Vala compiler: valac (valac 0.40.18)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Configuring config.h using configuration
Dependency gtk+-3.0 found: YES 3.22.30
Library m found: YES
Dependency gobject-2.0 found: YES 2.56.4
Dependency glib-2.0 found: YES 2.56.4
Dependency cairo found: YES 1.15.10
Dependency gee-0.8 found: YES 0.20.2
Dependency granite found: YES 5.2.5
Dependency gtk+-3.0 found: YES (cached)
Dependency libxml-2.0 found: YES 2.9.4
Dependency libarchive found: YES 3.2.2
Program meson/post_install.py found: YES (/home/gibranlp/Downloads/Minder-master/meson/post_install.py)
Build targets in project: 11
Found ninja-1.8.2 at /usr/bin/ninja
[132/132] Linking target com.github.phase1geo.minder.
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./com.github.phase1geo.minder...done.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) c
The program is not being run.
(gdb) where
No stack.
(gdb)

**Comment by 5e1f** [comment]
I have same issue when i try to open mindmap which i was create recently.
Minder opens fine after deleting tab_state.xml from /home/username/.local/share/minder/

**Comment by 5e1f** [comment]
I think the cause of the problem in the use of the Custom themes.
When i was change my Minder mindmap tag <theme name="Custom Theme name"  to <theme name="**Default**"....  the file opened normally

@gibranlp do you use custom themes?

**Comment by gibranlp** [comment]
I do use the Sierra theme, i have to say tthat this was no a problem before, i have been using both Minder and Sierra theme for most of the year now.

i will try your fix though let you guys know

**Comment by cesarviana** [comment]
I also had this problem. I created a custom theme, and after closing the program it not opened anymore. After deleting the theme tag it opened successfully.
