### ISSUE TITLE
Bugs with the new 1.6 version

### ISSUE THREAD

**Issue by Fatih20** [phase1geo/Minder#108]
https://open.lbry.com/MinderElementary#bb8d5533e2b78d3697e968618b2a171a3eca13f9

- Bugs when closing the sidebar

**Comment by dvn0** [comment]
Getting these too.

**Comment by phase1geo** [comment]
The issue related to closing the sidebar has been taken care of in a development branch and will be generally available in the next version of Minder.

**Comment by Fatih20** [comment]
What about the crash?

**Comment by phase1geo** [comment]
No, the crash issue has not been fixed yet. I'm going to create a new issue to track that issue. I don't like having a single issue tracking several issues. It makes it difficult to properly track and handle them.

**Comment by Fatih20** [comment]
Maybe just maybe you shouldn't have rushed the update and instead focus on beta testing so user shouldn't have to wait for over 3 months for a usable software that they might heavily rely on.

**Comment by phase1geo** [comment]
I apologize that it took so long. You can always downgrade by grabbing the last working version from GitHub directly so that you are not completely stuck.
