### ISSUE TITLE
meson.build:48:0: ERROR: C library 'markdown' not found

### ISSUE THREAD

**Issue by codeitlikemiley** [phase1geo/Minder#109]
Hi Im using archlinux 
I tried to install it using yay package manager but i dont have luck compiling code
this is the part of the meson-log.txt

```
Code:
 int main() { return 0; }
Compiler stdout:
 
Compiler stderr:
 /usr/bin/ld: cannot find -lmarkdown
collect2: error: ld returned 1 exit status


meson.build:48:0: ERROR: C library 'markdown' not found

```
is there any dependencies not listed on the aur ? which is being needed?
if there is please tell me so i can download it and compile this thanks

**Comment by codeitlikemiley** [comment]
Im using i3 gaps as my window manager so literally i dont have a desktop environment being used such as gnome , kde etc.

but i do manage to installed this by installing this 2 dependecies
discount
gtksourceview3

**Comment by phase1geo** [comment]
I just updated the project README to include the following dependencies:

libgtksourceview-3.0-dev
libmarkdown2-dev

I don’t know what “discount” is and what it provides.

**Comment by codeitlikemiley** [comment]
discount is the C library markdown
it is extra/discount on AUR package , but can be installed as discount since no other package name has this

**Comment by phase1geo** [comment]
Has this issue been resolved for you?  If so, I'd like to close it out for tracking purposes.

**Comment by phase1geo** [comment]
Closing issue.
