### ISSUE TITLE
RFE: port to gtksourceview-4

### ISSUE THREAD

**Issue by kloczek** [phase1geo/Minder#116]
Yep .. it would be good to port it to new version of the gtksourceview :)

**Comment by phase1geo** [comment]
Is the new version of gtksourceview available in the 18.04 Ubuntu LTS? If it is, I will get it updated now; otherwise, I will wait until the new LTS is released and elementary OS has integrated it before I make this update.

**Comment by kloczek** [comment]
I heve no idea. I'm not using any Debian based distributions.

**Comment by kloczek** [comment]
Just FTR some patches from other projects about porting to gtksourceview-4
http://deriv.debian.net/patches/g/gnome-sushi/Debian_gnome-sushi_3.32.0-1_Endless_gnome-sushi_3.32.0-1endless0.debian.patch
https://gitlab.gnome.org/GNOME/gedit-plugins/commit/c8e0b2b5bf2dde722a44564c8087ee6fdbc9fc61.patch

**Comment by kloczek** [comment]
Seems like now Minder is one of the last active projects which is till using gtksourceview-3 :(

**Comment by phase1geo** [comment]
What does version 4 provide that is missing from version 3 that Minder needs?

**Comment by phase1geo** [comment]
In addition, here is the apt listing for the gtksourceview packages available in the lastest release of elementary OS.  I don't see gtksourceview version 4 available, so this work isn't going to happen until the next version of elementary OS is released. I'm not going to be shamed into implementing this change.

trevorw@trevorw-KPL-W0X:~/projects/Minder$ apt search sourceview
Sorting... Done
Full Text Search... Done
formiko/bionic,bionic 1.3.0-1 all
  reStructuredText and MarkDown editor and live previewer

gir1.2-gspell-1/bionic 1.6.1-1 amd64
  spell-checking library for GTK+ applications - GObject introspection

gir1.2-gtksource-3.0/bionic,now 3.24.7-1+elementary6~ubuntu5.0.1 amd64 [installed,automatic]
  gir files for the GTK+ syntax highlighting widget

libgspell-1-1/bionic,now 1.6.1-1 amd64 [installed,automatic]
  spell-checking library for GTK+ applications

libgspell-1-common/bionic,bionic,now 1.6.1-1 all [installed,automatic]
  libgspell architecture-independent files

libgspell-1-dev/bionic 1.6.1-1 amd64
  spell-checking library for GTK+ applications - development files

libgtk2-sourceview2-perl/bionic 0.10-2build4 amd64
  enhanced source code editor widget

libgtkdsv-3-0/bionic 3.7.5-2build1 amd64
  GTK+ syntax highlighting widget - D bindings

libgtkdsv-3-dev/bionic 3.7.5-2build1 amd64
  GTK+ syntax highlighting widget - development files for D

libgtksourceview-3.0-1/bionic,now 3.24.7-1+elementary6~ubuntu5.0.1 amd64 [installed,automatic]
  shared libraries for the GTK+ syntax highlighting widget

libgtksourceview-3.0-common/bionic,bionic,now 3.24.7-1+elementary6~ubuntu5.0.1 all [installed,automatic]
  common files for the GTK+ syntax highlighting widget

libgtksourceview-3.0-dev/bionic,now 3.24.7-1+elementary6~ubuntu5.0.1 amd64 [installed]
  development files for the GTK+ syntax highlighting widget

libgtksourceview-3.0-doc/bionic,bionic 3.24.7-1+elementary6~ubuntu5.0.1 all
  documentation for the GTK+ syntax highlighting widget

libgtksourceview2.0-0/bionic 2.10.5-3 amd64
  shared libraries for the GTK+ syntax highlighting widget

libgtksourceview2.0-common/bionic,bionic 2.10.5-3 all
  common files for the GTK+ syntax highlighting widget

libgtksourceview2.0-dev/bionic 2.10.5-3 amd64
  development files for the GTK+ syntax highlighting widget

libgtksourceview2.0-doc/bionic,bionic 2.10.5-3 all
  documentation for the GTK+ syntax highlighting widget

libgtksourceviewmm-3.0-0v5/bionic,now 3.18.0-3 amd64 [installed,automatic]
  C++ binding of GtkSourceView

libgtksourceviewmm-3.0-dev/bionic 3.18.0-3 amd64
  C++ binding of GtkSourceView - development files

libgtksourceviewmm-3.0-doc/bionic,bionic 3.18.0-3 all
  C++ binding of GtkSourceView

liblablgtk-extras-ocaml-dev/bionic 1.5-1build3 amd64
  collection of modules for OCaml/LablGtk2 applications

liblablgtk-extras-ocaml-doc/bionic,bionic 1.5-1build3 all
  collection of modules for OCaml/LablGtk2 applications (documentation)

liblablgtksourceview2-ocaml/bionic 2.18.5+dfsg-1build1 amd64
  OCaml bindings for libgtksourceview2 (runtime)

liblablgtksourceview2-ocaml-dev/bionic 2.18.5+dfsg-1build1 amd64
  OCaml bindings for libgtksourceview2, a source editor GTK+ widget

nescc/bionic 1.3.5-1.1 amd64
  Programming Language for Deeply Networked Systems

python-gtksourceview2/bionic 2.10.1-3 amd64
  Python bindings for the GtkSourceView widget

ruby-gtksourceview3/bionic,bionic 3.2.4-1 all
  GtkSourceView3 bindings for the Ruby language

**Comment by kloczek** [comment]
FYI https://developer.gnome.org/gtksourceview/stable/porting-guide-3-to-4.html

**Comment by phase1geo** [comment]
Gtk 3.22 is the latest available gtk version available for elementary. When elementary OS 6 is available, I will get this library updated.

**Comment by kloczek** [comment]
This is not about gtk but porting from gtksourceview-3 to gtksourceview-4 :)

**Comment by phase1geo** [comment]
Yes, but according to the article, you must have version 3.24.  The gtksourceview-4 package is not available in the latest elementary OS 5 (Hera) -- I have tried.

**Comment by kloczek** [comment]
At the moment only few packages are still not ported to gtksourceview-4. One of those is Minder
Last gtk 3.23 was released year ago https://download.gnome.org/sources/gtk+/3.23/ and all updates/fixes for gtk 3.x are only for 3.24.x (in last year was 23 releases https://download.gnome.org/sources/gtk+/3.24/).
.. so I'm gueassing that "OS 5 (Hera)" (whatever it is) must be quite old and/or distribution developers which you are using stopped updating packages.

**Comment by phase1geo** [comment]
Elementary OS is based on Ubuntu LTS releases. So until they release version 6, the packages are based on 18.04. Version 6 will be based on 20.04 which will contain the new packages.

I have asked the question previously, but I will ask it again since it was not answered. Is something broken for you with GtkSourceview3? What is the difference from a user’s perspective between 3 and 4? I can’t imagine that the user is going to notice a difference from a usability perspective since the note editor in Minder isn’t a full-blown code editor and is only using GtkSourceview for its Markdown syntax highlighting capability. But I could be wrong here.

**Comment by kloczek** [comment]
You know there is nothig wrong with using kernel 2.6. Are you you using it still?

Again .. less and less software is using GtkSourceview3.

**Comment by phase1geo** [comment]
Good. So nothing is currently broken. That’s good to know.

**Comment by phase1geo** [comment]
We have updated to gtksourceview version 4 in the 1.13.1 version of Minder.
