### ISSUE TITLE
Child-nodes unfold when creating a new one from parent

### ISSUE THREAD

**Issue by pescepalla** [phase1geo/Minder#117]
How to reproduce:

1) have a parent-node with multiple child-nodes and grandchild-nodes
2) fold the existing child-nodes so that only parent and its child-nodes are visible
3) focus on parent-node and hit TAB to generate a new child-node

What should happen:

A new child-node is created. Nothing else happens.

What happens:

The new child-node is created but also the previous child-nodes unfold. What's worse is that they unfold without padding so all the branches are shown messily.

**Comment by pescepalla** [comment]
screenshots: https://mega.nz/#F!s5IGhK6A!Kd2HNeGmMbwxCKHVgvLg-Q

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch.  This will be generally available in the next stable release.

**Comment by phase1geo** [comment]
This bug has been fixed in the 1.7.0 stable release.  Closing bug.
