### ISSUE TITLE
AppData: Invalid release description tags

### ISSUE THREAD

**Issue by cassidyjames** [phase1geo/Minder#124]
Inside your release descriptions, you're using a number of tags that are not supported by AppStream, namely at least `<h3>` and `<b>` tags.

See: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description

**Comment by phase1geo** [comment]
I have update the appdata.xml file per request in the master release.

**Comment by phase1geo** [comment]
Stable release 1.7.2 contains the fix for this issue.  `h3` tags are replace with paragraph tags and `b` tags are replaced with emphasis tags, both of which are supported according to the appdata.xml spec.  Closing bug.
