### ISSUE TITLE
chinese language support for node

### ISSUE THREAD

**Issue by alanKin123Jin** [phase1geo/Minder#125]
I can't input chinese in node but can in note.

**Comment by phase1geo** [comment]
I have a U.S. keyboard. Is something that I can test by using a virtual keyboard?

**Comment by phase1geo** [comment]
The reason why nodes and notes work differently is because notes uses a standard Gtk.TextBuffer widget while a node uses custom editing and display code. Every effort has been made to make node text display work like a standard Gtk.TextBuffer, but there is always room for improvement ;)

**Comment by phase1geo** [comment]
Can you elaborate on what you mean by "can't input chinese"? Is the problem that chinese characters aren't displayed in the node at all? Is the problem that text is display in L-to-R instead of R-to-L? Something else?

**Comment by alanKin123Jin** [comment]
The chinese characters can be displayed by pasting to the node properly.But I can't use ibus chinese input method to type in the node.
The input method just don't show when the cursor is in node.
Chinese character can be type in America keyboard.Because the pinyin input method is using english alphabet.You don't need to change keyboard layout.Just adding input method.
If you wan't to reproduce the bug,you may need  go to system setting - language region-keyboard setting-input method setting-input method-add chinese-intelligent Pinyin ,
And then changing the system language to chinese the input method .Log out,now the chinese input method will work.Using control Space to switch it.

I don't know what is L-to-R or R-to-L meaning.

**Comment by phase1geo** [comment]
Thanks for the clarification and directions. L-to-R is shorthand for left to right (the order in which characters are displayed in a text field). R-to-L is just the opposite.

**Comment by phase1geo** [comment]
Would you be willing to try out the "input_method" branch and see tell me if the implemention is working as you would expect it to? I believe that I have it basically working at this point, but I would greatly appreciate any feedback that you would have.

**Comment by alanKin123Jin** [comment]
I've updated minder to the latest version via appstore.Then I have tried several chinese "inut_method" that offered by the elementary OS.Sadly,it doesn't work.When I want to use input_method to type chinese word,The node just shows the english  letters.

**Comment by phase1geo** [comment]
The changes that I have made are not included in the latest Minder release. I was wondering if you would be willing/able to test out the enhancements I have made to one of the development versions of Minder. The git branch is called “input_method”.

If you are unfamiliar with building from a certain git branch and are not willing to learn, just disregard my request.

**Comment by alanKin123Jin** [comment]
built failed.Here is the output  logs:
:~/Documents/Minder-text_input$ ./app run
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
[1/127] Compiling Vala source ../src/animator/AnimatorAction.vala ../src/anima..../src/UndoItem.vala ../src/Utils.vala ../tests/assert.vala ../tests/test.vala.
FAILED: com.github.phase1geo.minder@exe/src/animator/AnimatorAction.c com.github.phase1geo.minder@exe/src/animator/AnimatorNodes.c com.github.phase1geo.minder@exe/src/animator/AnimatorPan.c com.github.phase1geo.minder@exe/src/animator/AnimatorPanScale.c com.github.phase1geo.minder@exe/src/animator/AnimatorPositions.c com.github.phase1geo.minder@exe/src/animator/AnimatorScale.c com.github.phase1geo.minder@exe/src/exports/ExportCSV.c com.github.phase1geo.minder@exe/src/exports/ExportFreemind.c com.github.phase1geo.minder@exe/src/exports/ExportFreeplane.c com.github.phase1geo.minder@exe/src/exports/ExportImage.c com.github.phase1geo.minder@exe/src/exports/ExportMarkdown.c com.github.phase1geo.minder@exe/src/exports/ExportMermaid.c com.github.phase1geo.minder@exe/src/exports/ExportOPML.c com.github.phase1geo.minder@exe/src/exports/ExportPDF.c com.github.phase1geo.minder@exe/src/exports/ExportPNG.c com.github.phase1geo.minder@exe/src/exports/ExportPrint.c com.github.phase1geo.minder@exe/src/exports/ExportSVG.c com.github.phase1geo.minder@exe/src/exports/ExportText.c com.github.phase1geo.minder@exe/src/exports/ExportYed.c com.github.phase1geo.minder@exe/src/layouts/LayoutDown.c com.github.phase1geo.minder@exe/src/layouts/LayoutHorizontal.c com.github.phase1geo.minder@exe/src/layouts/LayoutLeft.c com.github.phase1geo.minder@exe/src/layouts/LayoutManual.c com.github.phase1geo.minder@exe/src/layouts/LayoutRight.c com.github.phase1geo.minder@exe/src/layouts/LayoutUp.c com.github.phase1geo.minder@exe/src/layouts/LayoutVertical.c com.github.phase1geo.minder@exe/src/styles/LinkTypeCurved.c com.github.phase1geo.minder@exe/src/styles/LinkTypeSquared.c com.github.phase1geo.minder@exe/src/styles/LinkTypeStraight.c com.github.phase1geo.minder@exe/src/styles/NodeBorderBracket.c com.github.phase1geo.minder@exe/src/styles/NodeBorderNone.c com.github.phase1geo.minder@exe/src/styles/NodeBorderPill.c com.github.phase1geo.minder@exe/src/styles/NodeBorderRounded.c com.github.phase1geo.minder@exe/src/styles/NodeBorderSquared.c com.github.phase1geo.minder@exe/src/styles/NodeBorderUnderlined.c com.github.phase1geo.minder@exe/src/themes/ThemeDark.c com.github.phase1geo.minder@exe/src/themes/ThemeDefault.c com.github.phase1geo.minder@exe/src/themes/ThemeSolarizedDark.c com.github.phase1geo.minder@exe/src/themes/ThemeSolarizedLight.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionAdd.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionChange.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionColor.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionDelete.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionNote.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionTitle.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeAddParent.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeAttach.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeBalance.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeCut.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeDelete.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeDetach.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeFold.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeFoldChanges.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeImage.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeInsert.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeLayout.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeLink.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeLinkColor.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeMove.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeName.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeNote.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodePaste.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeResize.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeReveal.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeSort.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeTask.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodesInsert.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleAffectChange.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleChange.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionArrow.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionDash.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionFont.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionPadding.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionWidth.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleLinkArrow.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleLinkDash.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleLinkType.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleLinkWidth.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeBorder.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeBorderwidth.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeFill.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeFont.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeMargin.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeMarkup.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodePadding.c com.github.phase1geo.minder@exe/src/Animator.c com.github.phase1geo.minder@exe/src/Application.c com.github.phase1geo.minder@exe/src/Bezier.c com.github.phase1geo.minder@exe/src/CanvasText.c com.github.phase1geo.minder@exe/src/Connection.c com.github.phase1geo.minder@exe/src/ConnectionInspector.c com.github.phase1geo.minder@exe/src/ConnectionMenu.c com.github.phase1geo.minder@exe/src/Connections.c com.github.phase1geo.minder@exe/src/CurrentInspector.c com.github.phase1geo.minder@exe/src/Document.c com.github.phase1geo.minder@exe/src/DrawArea.c com.github.phase1geo.minder@exe/src/DynamicNotebook.c com.github.phase1geo.minder@exe/src/EmptyInspector.c com.github.phase1geo.minder@exe/src/EmptyMenu.c com.github.phase1geo.minder@exe/src/ImageEditor.c com.github.phase1geo.minder@exe/src/ImageManager.c com.github.phase1geo.minder@exe/src/Layout.c com.github.phase1geo.minder@exe/src/Layouts.c com.github.phase1geo.minder@exe/src/LinkDash.c com.github.phase1geo.minder@exe/src/LinkType.c com.github.phase1geo.minder@exe/src/MainWindow.c com.github.phase1geo.minder@exe/src/MapInspector.c com.github.phase1geo.minder@exe/src/Node.c com.github.phase1geo.minder@exe/src/NodeBorder.c com.github.phase1geo.minder@exe/src/NodeImage.c com.github.phase1geo.minder@exe/src/NodeInspector.c com.github.phase1geo.minder@exe/src/NodeMenu.c com.github.phase1geo.minder@exe/src/Partitioner.c com.github.phase1geo.minder@exe/src/QuickEntry.c com.github.phase1geo.minder@exe/src/Style.c com.github.phase1geo.minder@exe/src/StyleInspector.c com.github.phase1geo.minder@exe/src/Styles.c com.github.phase1geo.minder@exe/src/Theme.c com.github.phase1geo.minder@exe/src/ThemeEditor.c com.github.phase1geo.minder@exe/src/Themes.c com.github.phase1geo.minder@exe/src/UndoBuffer.c com.github.phase1geo.minder@exe/src/UndoItem.c com.github.phase1geo.minder@exe/src/Utils.c com.github.phase1geo.minder@exe/tests/assert.c com.github.phase1geo.minder@exe/tests/test.c 
valac -C --debug --debug --define=GTK322 --pkg libarchive --pkg libxml-2.0 --pkg gtk+-3.0 --pkg granite --pkg gee-0.8 --pkg cairo --pkg glib-2.0 --pkg gobject-2.0 --color=always --directory com.github.phase1geo.minder@exe --basedir ../ --gresources=../data/com.github.phase1geo.minder.gresource.xml ../src/animator/AnimatorAction.vala ../src/animator/AnimatorNodes.vala ../src/animator/AnimatorPan.vala ../src/animator/AnimatorPanScale.vala ../src/animator/AnimatorPositions.vala ../src/animator/AnimatorScale.vala ../src/exports/ExportCSV.vala ../src/exports/ExportFreemind.vala ../src/exports/ExportFreeplane.vala ../src/exports/ExportImage.vala ../src/exports/ExportMarkdown.vala ../src/exports/ExportMermaid.vala ../src/exports/ExportOPML.vala ../src/exports/ExportPDF.vala ../src/exports/ExportPNG.vala ../src/exports/ExportPrint.vala ../src/exports/ExportSVG.vala ../src/exports/ExportText.vala ../src/exports/ExportYed.vala ../src/layouts/LayoutDown.vala ../src/layouts/LayoutHorizontal.vala ../src/layouts/LayoutLeft.vala ../src/layouts/LayoutManual.vala ../src/layouts/LayoutRight.vala ../src/layouts/LayoutUp.vala ../src/layouts/LayoutVertical.vala ../src/styles/LinkTypeCurved.vala ../src/styles/LinkTypeSquared.vala ../src/styles/LinkTypeStraight.vala ../src/styles/NodeBorderBracket.vala ../src/styles/NodeBorderNone.vala ../src/styles/NodeBorderPill.vala ../src/styles/NodeBorderRounded.vala ../src/styles/NodeBorderSquared.vala ../src/styles/NodeBorderUnderlined.vala ../src/themes/ThemeDark.vala ../src/themes/ThemeDefault.vala ../src/themes/ThemeSolarizedDark.vala ../src/themes/ThemeSolarizedLight.vala ../src/undo_actions/UndoConnectionAdd.vala ../src/undo_actions/UndoConnectionChange.vala ../src/undo_actions/UndoConnectionColor.vala ../src/undo_actions/UndoConnectionDelete.vala ../src/undo_actions/UndoConnectionNote.vala ../src/undo_actions/UndoConnectionTitle.vala ../src/undo_actions/UndoNodeAddParent.vala ../src/undo_actions/UndoNodeAttach.vala ../src/undo_actions/UndoNodeBalance.vala ../src/undo_actions/UndoNodeCut.vala ../src/undo_actions/UndoNodeDelete.vala ../src/undo_actions/UndoNodeDetach.vala ../src/undo_actions/UndoNodeFold.vala ../src/undo_actions/UndoNodeFoldChanges.vala ../src/undo_actions/UndoNodeImage.vala ../src/undo_actions/UndoNodeInsert.vala ../src/undo_actions/UndoNodeLayout.vala ../src/undo_actions/UndoNodeLink.vala ../src/undo_actions/UndoNodeLinkColor.vala ../src/undo_actions/UndoNodeMove.vala ../src/undo_actions/UndoNodeName.vala ../src/undo_actions/UndoNodeNote.vala ../src/undo_actions/UndoNodePaste.vala ../src/undo_actions/UndoNodeResize.vala ../src/undo_actions/UndoNodeReveal.vala ../src/undo_actions/UndoNodeSort.vala ../src/undo_actions/UndoNodeTask.vala ../src/undo_actions/UndoNodesInsert.vala ../src/undo_actions/UndoStyleAffectChange.vala ../src/undo_actions/UndoStyleChange.vala ../src/undo_actions/UndoStyleConnectionArrow.vala ../src/undo_actions/UndoStyleConnectionDash.vala ../src/undo_actions/UndoStyleConnectionFont.vala ../src/undo_actions/UndoStyleConnectionPadding.vala ../src/undo_actions/UndoStyleConnectionWidth.vala ../src/undo_actions/UndoStyleLinkArrow.vala ../src/undo_actions/UndoStyleLinkDash.vala ../src/undo_actions/UndoStyleLinkType.vala ../src/undo_actions/UndoStyleLinkWidth.vala ../src/undo_actions/UndoStyleNodeBorder.vala ../src/undo_actions/UndoStyleNodeBorderwidth.vala ../src/undo_actions/UndoStyleNodeFill.vala ../src/undo_actions/UndoStyleNodeFont.vala ../src/undo_actions/UndoStyleNodeMargin.vala ../src/undo_actions/UndoStyleNodeMarkup.vala ../src/undo_actions/UndoStyleNodePadding.vala ../src/Animator.vala ../src/Application.vala ../src/Bezier.vala ../src/CanvasText.vala ../src/Connection.vala ../src/ConnectionInspector.vala ../src/ConnectionMenu.vala ../src/Connections.vala ../src/CurrentInspector.vala ../src/Document.vala ../src/DrawArea.vala ../src/DynamicNotebook.vala ../src/EmptyInspector.vala ../src/EmptyMenu.vala ../src/ImageEditor.vala ../src/ImageManager.vala ../src/Layout.vala ../src/Layouts.vala ../src/LinkDash.vala ../src/LinkType.vala ../src/MainWindow.vala ../src/MapInspector.vala ../src/Node.vala ../src/NodeBorder.vala ../src/NodeImage.vala ../src/NodeInspector.vala ../src/NodeMenu.vala ../src/Partitioner.vala ../src/QuickEntry.vala ../src/Style.vala ../src/StyleInspector.vala ../src/Styles.vala ../src/Theme.vala ../src/ThemeEditor.vala ../src/Themes.vala ../src/UndoBuffer.vala ../src/UndoItem.vala ../src/Utils.vala ../tests/assert.vala ../tests/test.vala
../src/DynamicNotebook.vala:1045.13-1045.41: warning: Gtk.Container.resize_children has been deprecated since 3.10
../src/DrawArea.vala:927.14-927.18: error: Assignment: Cannot convert from `Gdk.ModifierType' to `bool'
        bool shift = (bool) e.state & ModifierType.SHIFT_MASK;
             ^^^^^
../src/DrawArea.vala:976.14-976.18: error: Assignment: Cannot convert from `Gdk.ModifierType' to `bool'
        bool shift = (bool) e.state & ModifierType.SHIFT_MASK;
             ^^^^^
../src/DrawArea.vala:2796.32-2796.36: error: Assignment: Cannot convert from `Gdk.ModifierType' to `bool'
    var nomod   = !(control || shift);
                               ^^^^^
../src/DrawArea.vala:2796.21-2796.27: error: Condition must be boolean
    var nomod   = !(control || shift);
                    ^^^^^^^
../src/DrawArea.vala:2807.47-2807.51: error: Argument 1: Cannot convert from `Gdk.ModifierType' to `bool'
          case 65363 :  handle_control_right( shift );  break;
                                              ^^^^^
../src/DrawArea.vala:2808.46-2808.50: error: Argument 1: Cannot convert from `Gdk.ModifierType' to `bool'
          case 65361 :  handle_control_left( shift );   break;
                                             ^^^^^
../src/DrawArea.vala:2809.44-2809.48: error: Argument 1: Cannot convert from `Gdk.ModifierType' to `bool'
          case 65362 :  handle_control_up( shift );     break;
                                           ^^^^^
../src/DrawArea.vala:2810.46-2810.50: error: Argument 1: Cannot convert from `Gdk.ModifierType' to `bool'
          case 65364 :  handle_control_down( shift );   break;
                                             ^^^^^
../src/DrawArea.vala:2817.27-2817.31: error: Assignment: Cannot convert from `Gdk.ModifierType' to `bool'
      } else if( nomod || shift ) {
                          ^^^^^
../src/DrawArea.vala:2827.39-2827.43: error: Argument 1: Cannot convert from `Gdk.ModifierType' to `bool'
          case 65363 :  handle_right( shift ); break;
                                      ^^^^^
../src/DrawArea.vala:2828.38-2828.42: error: Argument 1: Cannot convert from `Gdk.ModifierType' to `bool'
          case 65361 :  handle_left( shift );  break;
                                     ^^^^^
../src/DrawArea.vala:2831.36-2831.40: error: Argument 1: Cannot convert from `Gdk.ModifierType' to `bool'
          case 65362 :  handle_up( shift );    break;
                                   ^^^^^
../src/DrawArea.vala:2832.38-2832.42: error: Argument 1: Cannot convert from `Gdk.ModifierType' to `bool'
          case 65364 :  handle_down( shift );  break;
                                     ^^^^^
../src/DrawArea.vala:2800.11-2800.17: error: Condition must be boolean
      if( control ) {
          ^^^^^^^
../src/DrawArea.vala:2845.25-2845.29: error: Assignment: Cannot convert from `Gdk.ModifierType' to `bool'
    } else if( nomod || shift ) {
                        ^^^^^
../src/DrawArea.vala:3060.10-3060.14: error: Assignment: Cannot convert from `Gdk.ModifierType' to `bool'
    bool shift   = (bool) e.state & ModifierType.SHIFT_MASK;
         ^^^^^
../src/DrawArea.vala:3061.10-3061.16: error: Assignment: Cannot convert from `Gdk.ModifierType' to `bool'
    bool control = (bool) e.state & ModifierType.CONTROL_MASK;
         ^^^^^^^
Compilation failed: 17 error(s), 1 warning(s)
ninja: build stopped: subcommand failed.
Unable to build project, please review log

**Comment by phase1geo** [comment]
It looks like you grabbed the “text_input” branch instead of the “input_method” branch.

**Comment by alanKin123Jin** [comment]
I have successfully built this.And the input_method is working now.

**Comment by phase1geo** [comment]
I am going to leave the issue in the open state until the code is merged into the stable branch. Thanks for verifying that everything is working!
