### ISSUE TITLE
Errors when compiling 1.7.2

### ISSUE THREAD

**Issue by shooterjet** [phase1geo/Minder#126]
Hi. Thank you for this amazing application. Im having some issues compiling. I have tried Debian Buster and Ubuntu 19.04 so far and have issues for both. 

On debian buster currently and have the following errors during compile. Hope you can help.

`../src/exports/ExportPortableMinder.vala:75.23-75.42: error: Argument 1: Cannot convert from `int64' to `Archive.int64_t'
      entry.set_size( file_info.get_size() );
                      ^^^^^^^^^^^^^^^^^^^^
../src/exports/ExportPortableMinder.vala:78.23-78.26: error: Argument 1: Cannot convert from `int' to `Archive.FileType'
      entry.set_perm( 0644 );
                      ^^^^
../src/exports/ExportPortableMinder.vala:99.9-99.48: error: 1 extra arguments for `ssize_t Archive.Write.write_data (uint8[])'
        archive.write_data( buffer, bytes_read );
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/exports/ExportPortableMinder.vala:182.14-182.81: error: 1 extra arguments for `Archive.Result Archive.Read.read_data_block (out weak uint8[], out Archive.int64_t)'
      while( archive.read_data_block( out buffer, out buffer_length, out offset ) == Archive.Result.OK ) {
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/exports/ExportPortableMinder.vala:183.41-183.46: error: Argument 1: Cannot convert from `void*' to `unowned uint8[]'
        if( extractor.write_data_block( buffer, buffer_length, offset ) != Archive.Result.OK ) {
                                        ^^^^^^
../src/exports/ExportPortableMinder.vala:183.13-183.71: error: 1 extra arguments for `ssize_t Archive.Write.write_data_block (uint8[], Archive.int64_t)'
        if( extractor.write_data_block( buffer, buffer_length, offset ) != Archive.Result.OK ) {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 6 error(s), 0 warning(s)`

**Comment by phase1geo** [comment]
What version of libarchive is installed on your system?

**Comment by shooterjet** [comment]
Package: libarchive-dev
Version: 3.3.3-4+deb10u1

**Comment by phase1geo** [comment]
Would you be willing to try grabbing the latest "devel" branch of Minder and attempt to compile it on your system? I have just made an adjustment to how the project builds for version 3.3.3.  Let me know if there are any other errors that come from this.

**Comment by shooterjet** [comment]
`../src/exports/ExportPortableMinder.vala:78.23-78.26: error: Argument 1: Cannot convert from `int' to `Archive.FileType'
      entry.set_perm( 0644 );`

**Comment by phase1geo** [comment]
Okay, I have submitted another fix to the 'devel' branch. Care to try again?

**Comment by phase1geo** [comment]
I don't think that Archive.FileType is the correct argument for set_perm(). According to the documentation, it should be Archive.FileMode. The latest devel branch uses this parameter type instead. Hopefully, it will work for you.

**Comment by shooterjet** [comment]
`../src/exports/ExportPortableMinder.vala:74.24-74.39: error: The type name `Archive.FileMode' could not be found
      entry.set_perm( (Archive.FileMode)0644 );`

this is what i got from the latest devel branch. I apologize for only being able to report bugs and not provide any help. Im still a novice in linux. Im learning as much as i can and one day will be able to contribute.

**Comment by phase1geo** [comment]
Well, that is odd that the compiler is giving you that error message. I will have to do a bit more work on my end to make this work.

**Comment by shooterjet** [comment]
I compiled and installed libarchive 3.4.2. However there is still an error during compile.

Master branch
'../src/exports/ExportPortableMinder.vala:78.23-78.26: error: Argument 1: Cannot convert from `int' to `Archive.FileType''

Devel branch
'../src/exports/ExportPortableMinder.vala:74.24-74.39: error: The type name `Archive.FileMode' could not be found
      entry.set_perm( (Archive.FileMode)0644 );'

next, ill try compiling the vala versions to see if that helps.

**Comment by shooterjet** [comment]
I managed to get Minder running after compiling the latest vala package. I also retested the libarchive versions and both version 3.3.3 and 3.4.2 works.  

So the issue now seems like its due to valac. Compiling and installing valac 0.48.3 works. 

Hope this helps

**Comment by phase1geo** [comment]
Thanks giving some various things a go. I have updated the README.md to recommend the valac version to use. The rest of the changes will also be applied and made generally available in the next Minder release.
