### ISSUE TITLE
Problem with export when nodes are manual arranged

### ISSUE THREAD

**Issue by przepior** [phase1geo/Minder#128]
When nodes are manually arranged then an exported file is cropped. It doesn't happen when Minder organizes nodes.

**Comment by phase1geo** [comment]
Which export file type was not working?

**Comment by przepior** [comment]
I checked png, bmp and pdf. There is a simple example.
[Pobrane.zip](https://github.com/phase1geo/Minder/files/4499344/Pobrane.zip)

**Comment by phase1geo** [comment]
I believe I have fixed this problem in the development branch which will be generally available in the next stable release.
