### ISSUE TITLE
Unable to initialise; line 6: meson command not found

### ISSUE THREAD

**Issue by Vaigyanik-Jinger** [phase1geo/Minder#130]
I am on ubuntu 18.10 lts.
Did a git clone. traversed to directory Minder-master
tried ./app run
received error:

> line6 : meson command not found

> Unable to initialise

please help

**Comment by phase1geo** [comment]
Take a look at the readme file. It lists several package dependencies that will need to be installed on your system to build properly. One of those packages is the meson build utility. You can install them via the ‘apt’ command (I.e., ‘sudo apt install meson’)

**Comment by Vaigyanik-Jinger** [comment]
I tried solving a few dependencies using the sudo apt command. However the issues with '**libarchive**' package still persists. I am unable to resolve this dependency with the same command. Can you please point out where am I going wrong?

P.S. Sorry for troubling. Newbie to building apps from source code. I  tried finding a solution on stackoverflow and slack. I didn't quite understand much

**Comment by phase1geo** [comment]
What is the compile issue with libarchive? Can you post the error output here?

**Comment by Vaigyanik-Jinger** [comment]
Sorry for being so naive to not put the error message.
`./app run`
Output:

> Version: 0.45.1                                                                                                                                                                                 
Source dir: /home/vaigyanik/Public/Git Based App/Minder- Mind Maping/Minder-master                                                                                                              
Build dir: /home/vaigyanik/Public/Git Based App/Minder- Mind Maping/Minder-master/build                                                                                                         
Build type: native build                                                                                                                                                                        
Project name: com.github.phase1geo.minder                                                                                                                                                       
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")                                                                                                                      
Native Vala compiler: valac (valac 0.40.19)                                                                                                                                                     
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.56.4
Configuring config.h using configuration
Native dependency gtk+-3.0 found: YES 3.22.30

> meson.build:43:0: ERROR: Native dependency 'libarchive' not found
> 
> A full log can be found at /home/vaigyanik/Public/Git Based App/Minder- Mind Maping/Minder-master/build/meson-logs/meson-log.txt
> Unable to initialize, please review log


On running 
`sudo apt install libarchive `
OutPut:

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libarchive

**Comment by Vaigyanik-Jinger** [comment]
I have resolved that dependency. However, Here is the dependecy error for the next issue.
`./app run`

> Version: 0.45.1
> Source dir: /home/vaigyanik/Public/Git Based App/Minder- Mind Maping/Minder-master
> Build dir: /home/vaigyanik/Public/Git Based App/Minder- Mind Maping/Minder-master/build
> Build type: native build
> Project name: com.github.phase1geo.minder
> Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
> Native Vala compiler: valac (valac 0.40.19)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.29.1)
> Native dependency glib-2.0 found: YES 2.56.4
> Configuring config.h using configuration
> Native dependency gtk+-3.0 found: YES 3.22.30
> Native dependency libarchive found: YES 3.2.2
> Library m found: YES
> 
> meson.build:55:0: ERROR: C library 'markdown' not found
> 
> A full log can be found at /home/vaigyanik/Public/Git Based App/Minder- Mind Maping/Minder-master/build/meson-logs/meson-log.txt
> Unable to initialize, please review log

I am unable to understand How do I install C library 'markdown'. 
Help is appreciated

**Comment by phase1geo** [comment]
Try installing the libarchive-dev package.

**Comment by phase1geo** [comment]
Sorry about that last response.

If you run the command:

sudo ./app install-deps 

Does that resolve your dependency issues?

**Comment by Vaigyanik-Jinger** [comment]
The command prima facie doesn't resolve the issue. I am posting the error message here.

> ./app: line 71: dpkg-checkbuilddeps:: command not found

**Comment by phase1geo** [comment]
The markdown library should be installed with:

sudo apt install libmarkdown2-dev
