### ISSUE TITLE
Update of Minder Icon

### ISSUE THREAD

**Issue by ECFE** [phase1geo/Minder#131]
This is a proposal to update the icon of the Minder application that is utilized for the dock and in the store.

The minder application is pleasure to work with and produces good looking mind map diagrams. The current icon associated with Minder application does not fully convey the premium feel of working with the current application. To some extent the current icon stands out when seen next to/side by side with other stylized icons such as on the Elementary store, or in the dock.

This can be addressed by evolving the design of the icon such that it fits in next to the designs utilized for other applications. The benefits of evolving the icon for the application would be: a sharper visual identity, better conveying the good feel of the underlying application, a more eye catching look in the application store, a more pleasing look of the application in the dock next to other programs.

# Potential areas of improvements
- The current icon mixes different shapes (rounded cloud shapes against square mind-map nodes)
- Mind-map boxes apply a shaded gradient and depth effect that clashes with the current design utilized for most other applications.
- As a result of the above 7 different colours are used in a small space, giving a cluttered impression (2 per shaded node, 1 for the main node 2 for the cloud and the shading)
- Use of a shaped icon that deviates a fair bit from the more common icon shapes (square and circle)

**Comment by phase1geo** [comment]
Do you have any suggestions or alternatives to choose from? I’m mostly happy with the current icon and don’t have the artistic chops and time to mess with its design; however, if there were some alternatives to evaluate, I would be willing to entertain the idea of choosing something different. I believe the current icon conforms to the elementary OS HIG which is important to the project.

**Comment by ECFE** [comment]
I do not have an alternative as of right now, and only posses limited skills in design. However, if you are willing to at least have a look at the idea I would be happy to come up with a proposal (i.e. a suggestion). Even if that does not work straight away it could serve as a basis for discussion. 

Thanks for having a look and not rejecting it straight away :).

**Comment by phase1geo** [comment]
The only issue you mention that I disagree with is the shape of the icon.

The elementary HIG recommends/encourages the use of icon shapes that differentiate themselves from other applications. The Minder icon shape is distinctive and conveys meaning about the purpose of the application in the shape of a thought bubble. I think that making the icon a circle, rectangle or square would be a step backwards from following the HIG.

If an iconographer wants to create a Minder icon for a themed icon set that has similar shapes, so be it. The default theme used by elementary doesn’t have this design restriction.

**Comment by Fatih20** [comment]
> I do not have an alternative as of right now, and only posses limited skills in design. However, if you are willing to at least have a look at the idea I would be happy to come up with a proposal (i.e. a suggestion). Even if that does not work straight away it could serve as a basis for discussion.
> 
> Thanks for having a look and not rejecting it straight away :).

I'm the creator of the original icon. I'm looking into this.
> Mind-map boxes apply a shaded gradient and depth effect that clashes with the current design utilized for most other applications.
What do you mean?

**Comment by Fatih20** [comment]
If there are no further argument, can we close this issue?

**Comment by phase1geo** [comment]
I think that I'm going to close the issue as the originator of the issue hasn't provided alternative ideas in almost a month. If the originator of the issue wants to contribute to this, feel free to reopen but until then, I'm going to close this issue out.

Thanks for your help, @Fatih20 !
