### ISSUE TITLE
Allowing Adding Images from the Clipboard

### ISSUE THREAD

**Issue by RojoC** [phase1geo/Minder#132]
In cases where the  need to use of the pictures that found on the internet or screenshots using clipboard to add images can be useful.

**Comment by phase1geo** [comment]
That sounds like a very good idea.

**Comment by phase1geo** [comment]
I have just merged code changes which support (among other things) the ability to paste an image into the currently selected node (keyboard shortcut is Control-Shift-V).  You can also paste a new node with the current contents in the clipboard (includes text and images) attached as a child of the currently selected node.

These changes exist in the development branch and will be generally available in the next stable release of Minder.

**Comment by phase1geo** [comment]
I have improved the clipboard code in the development branch now.  I believe this should be the final version that will be in the next stable release.
