### ISSUE TITLE
[Feature Request] Edit Nodes with Quick Entry

### ISSUE THREAD

**Issue by anishbajpai014** [phase1geo/Minder#134]
Thank you for this awesome tool.

Quick Entry is pretty useful when you want to add a lot of nodes at the same time, but at the moment, it is limited to adding new nodes. It would be really useful if it could be used to edit a child tree itself.

The text input could automatically load the current children in the text format, (which is almost exactly the same as the `plaintext` "Export"), and on save it would overwrite the current child tree.

This will be useful to make large changes to the tree quickly.

I don't use connections as much, and I realize they might get lost in the current scheme.

As an alternative, Copying a node and pasting it into a text input could paste the `plaintext` representation of the same in the textbox, which could be used in tandem with `Add nodes with Quick Entry` to achieve the same.

**Comment by phase1geo** [comment]
Sounds like a pretty reasonable request to me.

**Comment by phase1geo** [comment]
I have checked in changes to provide this new functionality in the 'devel' branch.  The feature will be a part of the upcoming 1.8 stable release.  Note that there is a new keyboard shortcut and contextual menu item that allows the user to either "insert" (Control-Shift-E) new nodes via Quick Entry or "replace" (Control-Shift-R) currently selected node (and its subtree) with new nodes.
