### ISSUE TITLE
Add Flatpak or Snap Support

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#135]
Hello.
Firstly, I found this app today, it is very amazing.
Everything in it is impressive, very practical, useful and perfect.
I would like to thank you for this distinguished work.
I just have a request if you can add Flatpak or Snap to facilitate installation, or maybe a ppa. currently i'm using the version 1.5 in Ubuntu 20.04 and can't find a way to update it without building it every time.

**Comment by wada3n** [comment]
Hi  @phase1geo  Today, When I built the last version, I got this error:

`Settings schema 'com.github.phase1geo.minder' does not contain a key named 'rotate-main-link-colors'
./app: line 44: 24168 Trace/breakpoint trap   (core dumped) ./com.github.phase1geo.minder "${@:2}"
`

**Comment by phase1geo** [comment]
You will need to install the application before you can run it.

**Comment by wada3n** [comment]
Yes it worked now
Frankly, this app should be in every distribution.
Thanks again.

**Comment by tim77** [comment]
https://github.com/phase1geo/Minder/issues/52

**Comment by tim77** [comment]
Minder now available on [Flathub](https://flathub.org/apps/details/com.github.phase1geo.minder) :tada:

**Comment by phase1geo** [comment]
As @tim77 mentioned, Minder 1.8.0 is now available as a Flatpak on Flathub. Huge thanks to those involved on making this happen. Thank you!
