### ISSUE TITLE
Adding Attachments to Nodes

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#136]
Hi,
**Describe the solution you'd like**
I think adding attachments to nodes, PDF files, and others will make things a lot easier.
![2020-05-18_17-29](https://user-images.githubusercontent.com/13304792/82237654-e99a4100-992d-11ea-8548-142788993e61.png)

**Describe alternatives you've considered**
The file is either a name of the node directly, or is contained within it in the form of attachments.
Attachments can be added via an icon under image attachment, or by drag and drop within the node.

**Additional context**
By the way, it is possible to add a feature in the pictures: When the mouse is hovered over it, it appears as a popup, to show the details of the whole picture, while remaining small in the map.

**Comment by phase1geo** [comment]
Question about this feature request.  Does adding the attachment require copying the document into Minder or does adding an attachment only require storing the URI of the file?

**Comment by wada3n** [comment]
I think it is best to add the clip icon only with a URI when pressed opens the file in the system, if the file is deleted, of course it gives a message that the file does not exist.
adding the file itself will make the minder's files very large especially if huge and many files are attached!

**Comment by phase1geo** [comment]
I believe that this functionality exists in the 1.13.1 version of Minder.  Attachments can be added in either the notes or node title.  Holding the Control key and clicking on the attachment link will open the link in the file browser.  This also works with URLs (opens the link in the web browser) and e-mail addresses (creates a new e-mail message).
