### ISSUE TITLE
Crash when setting map node layout to "Vertical" or "Horizontal" with animations enabled

### ISSUE THREAD

**Issue by hus3h** [phase1geo/Minder#137]
The problem happens only when choosing "Vertical" or "Horizontal" node layouts with the animations being enabled. When "Enable animations" is set to off, it doesn't crash. The problem happens for other layouts when animations are disabled then enabled then a node layout is chosen (in this case the crash happens randomly, it could work multiple times first).

ABRT report: https://retrace.fedoraproject.org/faf/reports/2922870/

Version: 1.8.0
OS: Fedora 32

**Comment by phase1geo** [comment]
I may need a .minder file appended to this bug report to help reproduce the problem.

**Comment by hus3h** [comment]
I prepared a file (zipped because not all file types are supported).

While doing that I noticed something interesting, the problem never happens if you have more than one root node. For example if you have two root nodes, even if only one of them has children.

[minder-sample.zip](https://github.com/phase1geo/Minder/files/4651369/minder-sample.zip)

**Comment by phase1geo** [comment]
Thanks for the additional information. I’ll take a look at this later today.

**Comment by phase1geo** [comment]
I have fixed this issue in the devel branch which will be generally available in the next stable release.

**Comment by hus3h** [comment]
Good to know! Thank you.

**Comment by ayoungethan** [comment]
Thank you for the workaround of disabling animations until the fix is released!
