### ISSUE TITLE
Connection options not apply until create new one

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#138]
If the connection options are changed, the result does not appear directly, until when a new connection is created.
this produce only when choose: changes affect all

I am using the latest version 1.8 built from source in Ubuntu 20,04

**Comment by phase1geo** [comment]
I have fixed this issue in the development branch which will be generally available in the next stable release.

**Comment by wada3n** [comment]
u r the best @phase1geo :) 
You do a great job.
