### ISSUE TITLE
Connections not visible in dark theme

### ISSUE THREAD

**Issue by sandorex** [phase1geo/Minder#145]

**Comment by phase1geo** [comment]
I have checked in a lighter shade of the default link color used in the dark theme.  This change is in the development branch and will be generally available in the next stable release.

**Comment by phase1geo** [comment]
On a side note, you can change the color of any link by selecting it and in the "Current" sidebar pane, change the color there.  The theme color is only the default color that is used.

You can also create a custom theme of your own and set the default link color to anything that you want.  If you select the dark theme and then click on the plus (+) button at the bottom of the theme selection pane, it will allow you to create your custom theme, starting with the dark theme settings.
