### ISSUE TITLE
Add additional task properties

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#150]
Since the app have the task feature, why not add some related features.
Such as starting and ending dates, deadlines, importance and perhaps resources as well.
The addition takes place in a special tab in the properties sidebar.And it is activated only if the task feature is turned on.
e.g: This is from the iThoughtsX app

![2020-06-02_21-00](https://user-images.githubusercontent.com/13304792/83566428-e56a4800-a517-11ea-8134-718da9852b13.png)

**Comment by phase1geo** [comment]
This is another area, like the sidebar, where I am hesitant to add code for. Ideally, I would like to have Minder export task information to a task management application. I have reached out to a the Planner project to ask for a way to do this. There was interest in the idea, but it has not been implemented yet.

**Comment by wada3n** [comment]
Actually, compatibility with Planner will be better and will give a big plus.
Waiting for that :)

**Comment by phase1geo** [comment]
I agree.
