### ISSUE TITLE
Quick Entry problems

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#152]
Bonjour @phase1geo 

While using the Quick Entry Mode, I noticed three main problems:
**1-** When several root nodes are added together, they appear interlaced in the canvas
**2 -** Normally, a tab cannot be added at the beginning, while it can be done by copying and pasting, and after pressing Insert, application crashes.
You can try this:
(copying everything including spaces after the return key)
``` 
  - Hello


```

**3 -** When selecting a node, then entering the quick entry mode and trying to enter many nodes, only one node appears in the canvas
eg:
```
- Node 1
- Node 2
- Node 3
```

Only Node 1 appears in the canvas after pressing Insert

**Comment by phase1geo** [comment]
I will take a look later today. Thanks!

**Comment by phase1geo** [comment]
If you would like to test it out, I have updated the devel branch with fixes/modifications for this issue.  Let me know if there are any issues or unexpected behaviors with this implementation.  If everything holds up this issue will be generally available in the next stable release.

**Comment by wada3n** [comment]
This work you do is special,
my respect and gratitude to you.
I think a problem occurred during the solution, which is when entering Quick Entry and writing, you cannot write the space, and return to a new line, only you have the right to one line :)

**Comment by phase1geo** [comment]
Yes, I unintentionally messed that up. I will get that fixed shortly.

**Comment by phase1geo** [comment]
Okay, let's give this another try. The devel branch has been updated to fix issues with manual entry.

**Comment by wada3n** [comment]
Now it's just as cool as it should be
Thank you very much for this
