### ISSUE TITLE
Connection color overwrite in every app restart

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#153]
bonsoir @phase1geo 
This evening I had some experiences with the app and found two minor problems:

1- After choosing a color for connection, then restarting the app, the chosen color is replaced with the default gray each time.

2- On the shortcuts sheet for quick entry
The correct shortcuts are : Shift + Ctrl +E and Shift + Ctrl + R

**Comment by phase1geo** [comment]
Both of these issues should now be fixed in the devel branch.  The fixes will be generally available in the next stable release.
