### ISSUE TITLE
Control-motion and hyperlinks

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#155]
Bonsoir,
Today I have come across this little problems in minder
**1-** If the hyperlinked text is selected the delete and edit link items does not appear in drop down menu, it only appears if the text in the link is clicked directly

**2-** in the versions currently in development, the movement method in the canvas has been changed to the CTRL key (Control-motion) , which is the same button for displaying links, I think it is better to  be replaced by a Shift key, or Alt.

Have a nice day!

**Comment by phase1geo** [comment]
I have fixed this issue in the devel branch now (Alt + mouse motion is used to pan the canvas). This will be generally available in the next stable release.

**Comment by wada3n** [comment]
that's cool
what about the first part ? ( Remove a hyperlink without needing to delete text)

**Comment by wada3n** [comment]
that's cool!
