### ISSUE TITLE
Callout & Boundary feature

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#157]
Bonsoir,
I suggest adding two properties to the app:
**1-**  Callout as a visual component to allow for a better understanding of mind maps. It will contain eg: "it's important" or "critical" or "don't forget this", etc. 
Where sometimes the node contains certain information, and you want to add a visual content as a clarification to it and not as an internal content that will be good to add as a textbox, this element is attached to and clung to the place where it was attached first and always follows so that no confusion occurs during changing the display of the map.
The component will also help solve the enhancement addressed here #81 

**2-** Boundary: It can be added as a space containing the nodes to be grouped together (vertical, horizontal, or both).
You can change the fill color, border color, border style, shape style (cloud, star or rectangle...), shadow etc, via the Style tab.

![Sélection_009](https://user-images.githubusercontent.com/13304792/84575964-17499d00-ada9-11ea-9574-0e38df04264b.png)

**Comment by phase1geo** [comment]
Both of these feature requests were on my personal todo list for future versions.  Good to see that someone else also would like these type of features.

**Comment by wada3n** [comment]
I always wish you the best
This app will grow and grow to be essential and necessary in the Linux world, and I am sure of that.

**Comment by phase1geo** [comment]
I have the boundary feature (in Minder, it's referred to as group) implemented in the 'devel' branch which will be generally available in the next feature release of Minder.  The callout feature will be deferred to a later version.

**Comment by wada3n** [comment]
Nice step, I imported files from Freeplane and the result was great,
but I didn't know how to add it directly in the app? Is there a shortcut for that?

Thank you very much for every step you take in this masterpiece.

**Comment by wada3n** [comment]
Nice step, I imported files from Freeplane and the result was great,

~~but I didn't know how to add it directly in the app? Is there a shortcut for that?~~

mod: I was working on the initial version, now I have found how it works.
It remains only to add the shortcut to the Shortcuts cheatsheet.
Thank you very much for every step you take in this masterpiece.

**Comment by phase1geo** [comment]
Will get that added very soon. Thanks again!

**Comment by phase1geo** [comment]
Keyboard shortcut has been added.  I'm going to call this feature essentially complete (I still see a few issues in the alpha version).  The callout feature will be moved to a new issue as I don't intend on implementing that feature by the next version.
