### ISSUE TITLE
Clip-art/Stickers Support

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#160]
Hi @phase1geo ,I hope you're doing well.

What do you think if a new layer of flashiness is added to the application, it would be very nice to add clipart or colored icons in SVG format, you can resize it according to the need inside the nodes.
In fact, I did some research on the best stickers in the open source market and found that the best ones are [icons8/flat-color-icons ](https://github.com/icons8/flat-color-icons) with MIT license, almost 312 free icons for personal and commercial use. No credits required.
![2020-06-29_17-21](https://user-images.githubusercontent.com/13304792/86030939-0ea1c980-ba2d-11ea-994c-fe13f8f3547d.png)

The beautiful thing about this package is that it is already divided into [categories](https://icons8.github.io/flat-color-icons/), I think it can be added to a new tab in the application, and through each category you can choose, drag and drop the desired icon to the canvas and nodes.
Outside of the emoji, these stickers can be better controlled and give an aesthetic and technical dimension to understanding and arranging ideas in maps.

What do you think?

The idea exists in many applications of the same type as XMind:
![XMind-Screenshot-550x300](https://user-images.githubusercontent.com/13304792/86030707-bec30280-ba2c-11ea-9f5a-197c6cd89e6b.png)

**Comment by phase1geo** [comment]
I will look into it.

**Comment by phase1geo** [comment]
I have implemented sticker support in the devel branch of Minder.  You can add stickers to nodes, connections or simply drag them to any other space on the mind map.  If the latter is used, the sticker position doesn't automatically change if the layout is changed, so just be aware of that limitation.  Otherwise, I am reasonably happy with the result.

Thanks for suggesting the flat-color-icons set.  The lack of a decent set of stickers was one of the things keeping me from being able to make progress on this issue.

**Comment by wada3n** [comment]
Bonjour @phase1geo, 
I was following with interest everything you were doing in the branches, great job frankly.
I only have a slight point, when adding a sticker inside a connection, the background color of the sticker stays gray.
![Sélection_010](https://user-images.githubusercontent.com/13304792/90281402-6a50d680-de64-11ea-97b1-afbd87d1ee98.png)

I guess the issue was previously in the node filled with color but you've solved it ;)

**Comment by phase1geo** [comment]
I will get that fixed shortly. Thanks for reporting this.

**Comment by wada3n** [comment]
By the way, is there a possibility to work on changing the size of the sticker inside the node, and changing its location to the right, left, bottom or top of the text?

**Comment by phase1geo** [comment]
I'll probably leave the sticker size and location alone for the upcoming release.  I could see about adding something in the future.  Adding something to change the size of the sticker shouldn't be too bad, but changing the location of the sticker in the node is going to make the UI cumbersome and it makes the node drawing algorithm more complicated.  Two things I don't like:  make the UI more difficult for the user and make the coding more difficult for the developer.  So I may not end up implementing that feature request.

**Comment by wada3n** [comment]
Well I agree, a lot of things can be sacrificed for the sake of smoothness and ease of development ;)

**Comment by phase1geo** [comment]
I'll look into adding a way to provide custom stickers. If interested, I am always interested in expanding the current set of built-in stickers, too.

**Comment by DVegGyver** [comment]
Why I can't find the Stickers options? (Ubuntu 20.04, installed by package)

**Comment by phase1geo** [comment]
Stickers can be found in the Stickers tab of the sidebar. Just drag and drop them onto nodes, connections or an empty space in the canvas to add them to your mindmap.

**Comment by DVegGyver** [comment]
I upgraded ubutnu to 22.04 and the system reinstall me the last version of minder with all the functionality.
I have a problem with the Favourite stickers, they don't last from one session to another. When i close Minder and reopen, the Favourite become empty.
The favourite.xml file are located in my home directory but it seems that was not readed on new sessions.

How can I help to find why?

**Comment by phase1geo** [comment]
Which version of Minder is available on Ubuntu?

**Comment by phase1geo** [comment]
That version is fairly old, to be honest. I'm fairly confident that favoriting works in the latest 1.14.x version as well as the GitHub master branch. If you wanted to try building from source, you could confirm/deny that statement.
