### ISSUE TITLE
Crash upon attempt to change layout back to horizontal

### ISSUE THREAD

**Issue by ayoungethan** [phase1geo/Minder#163]
$ uname -a
`Linux pop-os 5.4.0-7634-generic #38~1592497129~20.04~9a1ea2e-Ubuntu SMP Fri Jun 19 22:43:37 UTC  x86_64 x86_64 x86_64 GNU/Linux`

Installed from Pop! Shop via flatpak

I had a mind map ~1/3 done, with one of four branches off the made node completely filled out (including tasks) and lots of notes. Then I changed the "node layouts" from "horizontal" to "vertical." When I tried to change back to "horizontal" the program crashed. I reopened the program and it crashed consistently. Finally, I rebuilt the mind map from scratch and so far I cannot reproduce the issue.

**Comment by ayoungethan** [comment]
Ah, this is a duplicate of https://github.com/phase1geo/Minder/issues/137

Also, I notice that connections are corrupted upon crash. One end of the connection is preserved, but the other end becomes connected to a completely different node than before the crash.

**Comment by ayoungethan** [comment]
Some but not all node links also become corrupted and linked to completely different nodes than before the crash.

**Comment by phase1geo** [comment]
I believe that this problem is fixed in the devel branch.  The next stable release will be coming very shortly.
