### ISSUE TITLE
Set text width

### ISSUE THREAD

**Issue by armaccloud** [phase1geo/Minder#167]
Hi there,

It would be nice if it was possible to set the allowed amount of text to be displayed in one line.

As an example, I'd like to achieve the following (one bullet point per line)

![image](https://user-images.githubusercontent.com/9272078/86522977-1535a400-be66-11ea-8f3d-e44ccd02c6a4.png)

But in Minder, this is shown as followed (the text is cut off too quickly for the following line)

![image](https://user-images.githubusercontent.com/9272078/86522987-31394580-be66-11ea-860d-88ab478f71c8.png)

**Comment by phase1geo** [comment]
Should be doable.

**Comment by phase1geo** [comment]
The devel branch has support for setting the width of nodes and connection titles via the style inspector.  This will be generally available in the next release.
