### ISSUE TITLE
Unexpected behaviour modifying text

### ISSUE THREAD

**Issue by armaccloud** [phase1geo/Minder#168]
I am using Minder on Pop!_OS 20.04 LTS, the latest version from the Pop Shop, flatpak.

When selecting the text in a node, it is then not possible to place the cursor in a specific spot, since the full text stays highlighted. Only by using the arrow keys on the keyboard can I navigate to a certain place in the text.

**Steps to Reproduce**

1. Make a node with text of a few lines
2. Click another node so the newly created node is not highlighted anymore
3. Select the newly created node text by double clicking it
4. Click anywhere within the text to set the cursor to that spot
5. Verify that nothing happens, the text stays selected and the cursor isn't set to the spot where you click

**Expected behavior**
The text is not highlighted anymore and the cursor is present where I have mouse-clicked

**Screencast**
Note, you don't see anything happening to the selected text, however I am clicking at multiple places within the text

![minder_cannot_place_cursor](https://user-images.githubusercontent.com/9272078/86523156-79f1fe00-be68-11ea-90da-f359065f6efa.gif)

**Comment by phase1geo** [comment]
I haven’t seen this issue come up on elementary OS, and I can’t seem to repeat it. With the text selected, can you start typing and make  the text change?

**Comment by armaccloud** [comment]
Hi, when I try to reproduce it myself, I am unable to. In a new minder, I don't get this issue.
However, the minder file I get the issue in, I just created yesterday, just text no fancy things.
Can I send you a private email with the actual file? I suspect it is a corruption that has creeped into the file somehow.

**Comment by phase1geo** [comment]
Sure.

**Comment by phase1geo** [comment]
I have found and fixed the problem in the master branch which will be generally available in the next stable release.

The problem was due to not properly scaling the X and Y mouse values when the left button was pressed, so it only occurs if you attempt to edit a node when the zoom factor is not 100%.  The file that was given to me had scaling set to 75% which lead to the issue.

**Comment by armaccloud** [comment]
Great to hear that you were able to solve it so quickly!
Thank you for picking this up so quickly.

Regards,
Arno

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by phase1geo** [comment]
Fixed in 1.9.1 release.
