### ISSUE TITLE
Ability to increase note text size

### ISSUE THREAD

**Issue by armaccloud** [phase1geo/Minder#169]
I tend to make use of notes a lot. However, they are quite difficult to read since the text is so small.
Therefor it might be nice to have a setting with which to increase the text size for the notes, so they are shown larger in either/both the popup dialogue and the sidebar.

**Comment by phase1geo** [comment]
I think you can increase the font size via the gnome tweak tool since those widgets use the standard Gtk widgets.

**Comment by phase1geo** [comment]
Change the “default” font size to something larger.

**Comment by phase1geo** [comment]
I can certainly add a preference option going forward, but this should get you what you are looking for without waiting for a new release.

**Comment by armaccloud** [comment]
Ah, I wasn't aware this was a default setting from the operating system. I increased the size a bit for as far as it doesn't mix up the menu's of other applications. I think there is a difference between reading application text menu's and reading longer text comfortably. It would be nice if this could be set in the application separately, but thank you for the workaround!

**Comment by phase1geo** [comment]
I have checked in a change to the devel branch that adds support for setting the font size used in Minder's text widgets via gsettings "text-field-font-size".  This will be generally available in the next release.

**Comment by armaccloud** [comment]
Thanks! @phase1geo
