### ISSUE TITLE
broken Files (Flatpack) (Linux Mint 20 Cinnamon)

### ISSUE THREAD

**Issue by josterburg** [phase1geo/Minder#172]
I worked on a project and even saved several versions to be save. But nearly all files seam to be broken, so minder **just shows a blank page**, as if there never where anything in it.

The attached file contains one of this broken files.
[Story-Baum_v7.minder.zip](https://github.com/phase1geo/Minder/files/4908633/Story-Baum_v7.minder.zip)
I just saved them the normal way.

Except this, minder is pretty cool software

**Comment by phase1geo** [comment]
It appears that your Minder file (from an XML perspective) was too deep for the standard XML parser.  I have updated the master branch with a fix for the issue.  I will create a 1.9.1 version shortly to resolve the issue for Flatpak users.

**Comment by phase1geo** [comment]
Available in 1.9.1 release.
