### ISSUE TITLE
blank screen issue after build last devel

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#173]
After building the new version of the devel branch, a strange issue occurred:
When I open one of the previous files, the screen becomes black as in the picture.

The problem appeared in both Ubuntu 20.04 and elementary OS
![Peek 2020-07-15 14-44](https://user-images.githubusercontent.com/13304792/87556374-794e3880-c6ae-11ea-9383-8d7f57294b7c.gif)

**Comment by wada3n** [comment]
[log.log](https://github.com/phase1geo/Minder/files/4925832/log.log)

Log file

**Comment by phase1geo** [comment]
I have seen this happen once before. Could you email me (or attach to this issue) the file that is causing the issue?

**Comment by wada3n** [comment]
The file was sent via email.
The problem arose two days ago in elementary OS, and today, the same problem occurs with me in Ubuntu, in all files already saved.

**Comment by phase1geo** [comment]
I got the email and will look into it later today. Thank you!

**Comment by phase1geo** [comment]
Good new and bad news.  The good news is that I have updated the devel branch to fix this issue.  The bad news is that your Minder file that you sent me is empty which means that this bug has caused you to lose whatever data you had in it.  I am sorry about that. The devel branch is not considered to be a stable branch and data loss can occur from time to time though I typically try to avoid that from happening.

**Comment by wada3n** [comment]
Well no problem, the file contained a little of my work for my studies, but believe me this app deserves to sacrifice some information and effort for it :)
It was my mistake, at least, if I saved another copy or exported it to another format.

Thank you very much for the distinguished work you do, my curiosity and certainty that you add unique things every time it makes me try everything new in the devel branch : D

**Comment by phase1geo** [comment]
I have no problem with people using the devel branch as long as they can live with the consequences ;)  Did you verify that the latest devel branch fixes the issue?

**Comment by wada3n** [comment]
Yes, I think so, from my experience with several files, I never encountered the issue again.
