### ISSUE TITLE
Determine nodes by mouse selection for style affects

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#174]
Hi,
According to new changes after removing the ability to change the style affects value.
When selecting multiple nodes by passing the mouse, the app does not specify these nodes for "changes effect" ​​and remains only in all nodes, as only work is done through the Shift key for choose the desired nodes.
It would be better if the nodes were determined directly through the mouse by easily dragging on them.

**Comment by phase1geo** [comment]
I believe that I have fixed this issue in the devel branch which will be generally available in the next stable release.
