### ISSUE TITLE
Duplicate Connection title

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#175]
In devel branch:

![2020-07-16_11-56](https://user-images.githubusercontent.com/13304792/87663203-5f1e6400-c75b-11ea-9bc2-8d3e54326264.png)

**Comment by phase1geo** [comment]
I have "fixed" the issue by removing the title editing field in the sidebar.  I did the same previously in the node sidebar and it makes sense to also remove it from the connection sidebar for consistency.  The change was made to the devel branch which will be generally available in the next stable release.

**Comment by wada3n** [comment]
Yes this is better, I like the consistency between all parts of the app!

I think it would be nice to make the edit mode default while adding a connection, for two main reasons:
- The new user of the app will never guess that the edit means adding a title.
- Often in use when adding a connection, there is a reason or comment about it, and I think it is rare that nothing is written on it.

In my opinion, it is better to make the edit mode the default when adding a connection, and in the event that nothing is written and pressure anywhere in the panel enters the normal mode as it is now.

**NB:** In the current situation when you press Edit, then not to write anything and exit the connection, the writing position in the connection remains small and does not contain anything.
It is assumed that nothing is written that remains as it was in the beginning and does not change, is it?

**Comment by wada3n** [comment]
A strange issue occurs sometimes, not always
connection changes its place.
Where the connection is between two nodes and after several changes in the file and adding new nodes when exiting and returning to the application, I find that the connection has changed to another node!
This issue has happened to me twice so far and I don't understand why.
