### ISSUE TITLE
Connection losing track of connected nodes

### ISSUE THREAD

**Issue by phase1geo** [phase1geo/Minder#177]
A strange issue occurs sometimes, not always
connection changes its place.
Where the connection is between two nodes and after several changes in the file and adding new nodes when exiting and returning to the application, I find that the connection has changed to another node!
This issue has happened to me twice so far and I don't understand why.

_Originally posted by @wada3n in https://github.com/phase1geo/Minder/issues/175#issuecomment-660083986_

**Comment by phase1geo** [comment]
@wada3n is there any way to reliably replicate this issue?  If not, could you e-mail a .minder file which draws the wrong mind map after restarting?  I would like to inspect the contents for errors.

**Comment by wada3n** [comment]
Hello @phase1geo , I hope you are always well.
In fact, I could not repeat the issue again, I do not know how it happened and for what reason, I think that opening several tabs was the reason, it's strange but it did not happen to me again.
I will try to create this issue again, in case I will send you the files responsible for that.
