### ISSUE TITLE
Connection lines don't appear.

### ISSUE THREAD

**Issue by YavBav09** [phase1geo/Minder#183]
When I connect an idea with another one, the connection line does not appear. 
![Screenshot from 2020-07-22 10 26 33](https://user-images.githubusercontent.com/62641282/88147558-0db42000-cc06-11ea-9a74-a6976d7ff653.png)

**Comment by phase1geo** [comment]
Is “Another idea” a child of “Main idea” or are these nodes in separate trees?

**Comment by phase1geo** [comment]
Also, what theme are you using?

**Comment by phase1geo** [comment]
Why I am asking is just to confirm that the issue isn't that the background color and the link color are the same (black in this case).

**Comment by phase1geo** [comment]
@Yavor-aaa Any results related to my last few questions?
