### ISSUE TITLE
Crash on clicking layout buttons

### ISSUE THREAD

**Issue by wpfan1000** [phase1geo/Minder#188]
Hi,
If I am at Map > Node layouts and click a layout button eg Horizontal, then Minder shuts down.

I am running Fedora 31. 

minder - 1.8.0-1.fc31.x86_64

I have a report but unfortunately have no way to copy it, I can only do so line by line, eg:

Reason - com.github.phase1geo.minder killed by SIGSEGV
crash_function - animator_positions_new_x

Its for me the best mindmap software becuase it has a dark theme and so I would love to try and work this out with you.

Please let me know if you need more info.

**Comment by phase1geo** [comment]
So this problem was fixed in version 1.9.0.  The latest version available in GitHub is 1.9.1.  I'm not sure who maintains the Fedora packages, but they would be the one to talk to.  Otherwise, you could also download the source code from GitHub, install the dependencies listed in the README.md file for the project and install that way.  If you go down that route, you may need to uninstall the Fedora package to eliminate any issues.

**Comment by wpfan1000** [comment]
PS I installed it using Fedora dnf from a Fedora repo so maybe there are some dependancy issues

**Comment by wpfan1000** [comment]
Thanks very much for your quick and helpful response.
I have never manually installed a program so my first try will be to contact the Fedora repo maintainer....

**Comment by phase1geo** [comment]
The crash isn't a result of dependency issues.  It was a bug in the code base.

**Comment by wpfan1000** [comment]
I just wanted to say that I think you have done a great job in writing Minder! I think it is intuitive, very nice in terms of how it  layed out, love that it has a dark theme, and much more! Much nicer than Freeplane, etc. Thanks for making it :)

**Comment by wpfan1000** [comment]
PS I just also experienced clicking a layout button and this time minder did not crash, but the mind map disappeared, and when I re-opened the file I saved the map in, the file had an empty map in it - has this been fixed as well?

**Comment by phase1geo** [comment]
Yes, that is essentially the same issue.

**Comment by wpfan1000** [comment]
Fedora 32 repo now has Minder 1.9.1
Issue resolved
