### ISSUE TITLE
How to move the map around?

### ISSUE THREAD

**Issue by wpfan1000** [phase1geo/Minder#193]
Sorry if I am missing something.
I found I can use my mouse wheel to move the map up and down.
But I dont see how to move the map left or right.
I don't see any scrollbars. I tried dragging the map. I tried left and right arrow keys.
I looked thru the Issues and Docs and did not see how to do this.
Is there a way to do this?
I did see how to center a node but it would be nice to move the map horizontally.
Thanks ahead of time.

**Comment by phase1geo** [comment]
Sure, hold down the Shift key while scrolling.  This will scroll the mind map left/right.  If you want to 'pan' the mind map, you can do that by holding the Alt key while moving the mouse cursor.

I plan on including these mouse-related keyboard shortcuts in the "Shortcuts Cheatsheet" within the tool, but that won't be available until the next feature release is made. Surprisingly, the GtkShortcuts widget doesn't have built-in support for mouse-related events so I'm struggling a bit to provide this information there in a good-looking way :(

**Comment by Fatih20** [comment]
Using middle click to pan around like in Inkscape or GIMP would be nice.

**Comment by wpfan1000** [comment]
Awesome!
Thanks for the rapid and helpful response
