### ISSUE TITLE
Feature request: keyboard shortcut for "Zoom to Fit"

### ISSUE THREAD

**Issue by Partmedia** [phase1geo/Minder#196]
I find myself using the "Zoom to Fit" button often. Would it be appropriate to have a keyboard shortcut for "Zoom to Fit"?

**Comment by phase1geo** [comment]
Sounds good to me! Do you have a suggestion for the keyboard shortcut?

**Comment by Partmedia** [comment]
Glad you like the idea. It doesn't seem to me that CTRL-A is mapped to anything right now. In other GUI contexts CTRL-A is like "select all," but here it would be "zoom to fit all". Or, you could stay consistent with the existing CTRL-0 ("zoom to actual size") and make "zoom fit" CTRL-1.

**Comment by phase1geo** [comment]
I have added Control-1 to the list of keyboard shortcuts for 'Zoom to Fit' in the 'devel' branch.  This change will be generally available in the next stable release.

**Comment by Partmedia** [comment]
Hooray, thank you!
