### ISSUE TITLE
executable

### ISSUE THREAD

**Issue by hamidrjafari** [phase1geo/Minder#198]
File name to start is obscure:
com.github.phase1geo.minder %f

installed via: sudo apt install minder
system Kubuntu 20.04

**Comment by phase1geo** [comment]
Could you clarify the issue?  I don’t understand what the problem is.

**Comment by hamidrjafari** [comment]
To run the application from command prompt it is required to
$ com.github.phase1geo.minder
Is that the apelation of the application?

**Comment by phase1geo** [comment]
That is the correct name of the application.  It is in RNDD format which is mandated by all elementary applications.  You can always create a symbolic link to this application and call it "minder" (or setup an alias in your shell initialization script) if you want to launch it from the command-line often.

**Comment by hamidrjafari** [comment]
elementary and can't be run from the command line like the usual executables?

**Comment by phase1geo** [comment]
To clarify, it is mandated by elementary OS (i.e., the Linux distribution / platform) applications.

**Comment by phase1geo** [comment]
Minder is build to run on the elementary OS platform as a native application in that environment.  So the application conforms to the elementary OS HIG, which also includes the naming of the application in the RNDD style.  This isn't considered to be a bug in the naming convention of the application.

That being said, if you want to run the application to look more like other applications on your platform, you can do that using one of the methods I mentioned above.  I would suggest creating an alias in your environment as that is what they are primarily used for in a Linux command-line environment.

**Comment by hamidrjafari** [comment]
Is the executable compiled binary or it requires interpretation?

**Comment by phase1geo** [comment]
Compiled binary.
