### ISSUE TITLE
Crash on delete

### ISSUE THREAD

**Issue by gibranlp** [phase1geo/Minder#203]
Hi again,

I'm running version 1.10.0 Arch, and everytime i try to delete a node (any node), the program crashes.

This is the output.

(com.github.phase1geo.minder:30261): Gtk-WARNING **: 15:31:05.827: gtk_widget_size_allocate(): attempt to allocate widget with width -20 and height 939
[1]    30261 segmentation fault (core dumped)  com.github.phase1geo.minder

**Comment by phase1geo** [comment]
Oops.  This problem came from the last commit.  I have fixed the issue in the master branch which will soon be available in the next stable release.
