### ISSUE TITLE
[Feature request] Export/import from/to plantuml format

### ISSUE THREAD

**Issue by bekenz** [phase1geo/Minder#204]
PlantUML allows to create mindmap, it would be great if minders provides the possibility to export/import map mind from/to plantuml format [https://plantuml.com/]

Example :
``` @startmindmap
* Debian
** Ubuntu
*** Elementary OS
*** Linux Mint
*** Kubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
``` 

Then a map min can be created on Minder, exported to plantuml format to be shared or published in a wiki. 
Also, a plantuml mapmind could be imported into minder in order to graphically update the mapmind initially created on PlantUML.

**Comment by phase1geo** [comment]
I was just doing a quick internet search for "PlanUML".  I keep coming with search results for "PlantUML".  Are these the same thing?

**Comment by bekenz** [comment]
Indeed I meant plan**T**uml, let me correct this.

**Comment by phase1geo** [comment]
Support for this export filetype will probably go into the stable release following the one that I'm releasing today.  If you can't wait for the feature, it appears that the Org-Mode export would get you close (I think you just need to wrap the output with the proper prefix and suffix lines.

**Comment by phase1geo** [comment]
I have added PlantUML import/export support added to the devel branch which will be generally available in the next stable release.

If you can, could you try grabbing the devel branch from GitHub and compile/run/try out the support on your end?  Just curious to know if the syntax that I am supporting for the import is suitable for your needs.

**Comment by bekenz** [comment]
I've testing and this is exactky the expected syntax

Thanks !!!
