### ISSUE TITLE
during node edit, auto save text

### ISSUE THREAD

**Issue by kvdz** [phase1geo/Minder#21]
it is really annoying to hit enter every time i edit a node title or head node title.

**Comment by phase1geo** [comment]
Could you elaborate on this? Are you talking about editing titles in the node inspector or in the canvas? If it’s the former, this issue has already been resolved in the development tree and will be available in the next release.

**Comment by kvdz** [comment]
it is in both when you edit it on the map itself. and when you edit it in the node inspector.

**Comment by phase1geo** [comment]
Could you grab the new version of Minder from AppCenter and let me know if this issue persists?
