### ISSUE TITLE
problems with undo

### ISSUE THREAD

**Issue by daveiro** [phase1geo/Minder#210]
Hi there,

I noticed 2 problems with undo with minder not behaving as expected and losing information which otherwise would be recovered with undo.

Here's how to reproduce the first issue: I create a node with text: "testing undo", then I press E key to edit and put text "changed text", then I press enter key and text is changed. If I press CTRL+Z to undo I would want that the node would revert to "testing undo" but it just becomes a node with an empty string. If I press CTRL+Z again then the node is removed (it seems to be undoing the node creation which is ok). So the node content to recover with undo seems to be somehow lost.

The second issue seems to be related or the same. If I edit some node to add a link, after pressing Enter, it's ok, now the node is clickable to access the webpage. Now if I press CTRL+Z, the node becomes an empty string when it just should revert to the text without link.

Thanks!

**Comment by phase1geo** [comment]
This issue should be fixed in the devel branch and will be generally available in the next stable release.

**Comment by daveiro** [comment]
:+1:
