### ISSUE TITLE
[Feature Request] Setting default map theme

### ISSUE THREAD

**Issue by FjorgeTheHuman** [phase1geo/Minder#211]
I'm a dark theme person and find it slightly annoying how we can't (or at least I haven't been able to) set a default map theme for new maps to use. Being able to set a default map theme would allow me to create maps faster without having to set it to dark every time I make one.

**Comment by phase1geo** [comment]
Sounds doable to me.  I'll work on something.

**Comment by phase1geo** [comment]
Question:  Would you rather be able to set a default theme via a preferences window or would you rather have Minder use the last used theme when creating a new mind-map?  I'm thinking the latter would be easier for the user, but what are your thoughts?

**Comment by FjorgeTheHuman** [comment]
> Question: Would you rather be able to set a default theme via a preferences window or would you rather have Minder use the last used theme when creating a new mind-map? I'm thinking the latter would be easier for the user, but what are your thoughts?

I think a preferences window would be nice, so you can have certain mind maps be a different theme without affecting future maps, and in the future should you choose to add more settings you could put them in the preferences window too.

**Comment by phase1geo** [comment]
Okay, that sounds good to me.  I'll have this ready in a little while.

**Comment by phase1geo** [comment]
I have this feature implemented in the devel branch which will be generally available in the next stable release.

**Comment by FjorgeTheHuman** [comment]
> I have this feature implemented in the devel branch which will be generally available in the next stable release.

Cool, thanks for listening to my suggestion!
