### ISSUE TITLE
Add keyboard shortcut for displaying contextual menus

### ISSUE THREAD

**Issue by phase1geo** [phase1geo/Minder#212]
When node text is selected, pressing Fn+"properties" key should bring up the "right click menu" so one can add a link or realize some other operation. I use this a lot to add links to nodes.

_Originally posted by @daveiro in https://github.com/phase1geo/Minder/issues/202#issuecomment-682013058_

**Comment by phase1geo** [comment]
I have added support for pressing either the Menu key or Shift+F10 to display the contextual menu within Minder in the devel branch.  This will be available in the next stable release.

**Comment by daveiro** [comment]
Great! Thank you!! :+1:
