### ISSUE TITLE
Shortcuts only work in the English layout

### ISSUE THREAD

**Issue by gavr123456789** [phase1geo/Minder#214]
I write tasks in Russian and English and constantly switch between them. I often need to copy and paste using ctrl + c / ctrl + v, but they only work in the English layout.

**Comment by phase1geo** [comment]
This is correct. Most shortcuts only work with an English keyboard setting. I haven’t figured out how to get non-English keyboard setting to work properly at this point. It may be a while before this issue can be properly addressed.

**Comment by gavr123456789** [comment]
https://discourse.gnome.org/t/the-values-of-key-identifiers-in-gdk-depend-on-the-language-layout/7225

**Comment by phase1geo** [comment]
I believe that I have fixed this issue in the master branch. If you could try running the branch and let me know if there are any issues, I would appreciate that.
