### ISSUE TITLE
Paned prevents you from change window size horizontally

### ISSUE THREAD

**Issue by gavr123456789** [phase1geo/Minder#216]
![Peek 2020-09-07 12-42](https://user-images.githubusercontent.com/30507409/92373961-c88d7400-f107-11ea-8c50-1d52c7dec436.gif)

**Comment by phase1geo** [comment]
I’ll try to get this fixed shortly.

**Comment by phase1geo** [comment]
This issue should now be fixed in the devel branch which will be generally available in the next stable release.
