### ISSUE TITLE
Not an issue. I just want to say thanks.

### ISSUE THREAD

**Issue by therealrobster** [phase1geo/Minder#218]
Hi all,

I've been using FreeMind for years.  I loved it and still do.
I did look for alternatives over time but never really found anything.  Really more just to get something more visually pleasing.  FreeMind is just fine.  So are new things though.

I came across this tonight and after some fiddling, getting comfortable, then really getting into a proper project with Minder I simply wanted to put a note here to say thank you to the contributors.  

It's a great piece of software and you've found a convert.  Be proud. It's highly usable.  Very attractive.  Configurable.  It's great. (love the vertical (downward) layout).

Anyway.  Great work to all involved and thank you.

**Comment by SevereOverfl0w** [comment]
If we are appreciating minder, I would also like to weigh in.  Minder is really wonderful!  Really great piece of kit, just works, does what I want and makes sense.  Makes me happy.

**Comment by phase1geo** [comment]
I'm going to close out this thread just to keep the issue list clean, but I appreciate the encouragement and support!
