### ISSUE TITLE
Unexpected increasing the indent

### ISSUE THREAD

**Issue by gavr123456789** [phase1geo/Minder#223]
![Peek 2020-09-20 20-37](https://user-images.githubusercontent.com/30507409/93717891-4aa67f80-fb81-11ea-92e9-e1f4fa70f7b2.gif)
DE: GNOME
Builded from Arch AUR (Master)

**Comment by phase1geo** [comment]
I will look to this later today. Thanks!

**Comment by phase1geo** [comment]
I have submitted a change to the devel branch to help improve the auto-adjustment of tree layout to hopefully work better in this instance.  If you are able, can you grab this git branch and try it out?
