### ISSUE TITLE
Crash when data is cut out

### ISSUE THREAD

**Issue by nerdpferd** [phase1geo/Minder#224]
![Screen record from 2020-09-21 13 17 54](https://user-images.githubusercontent.com/57867806/93760771-ef21d380-fc0c-11ea-8a8c-d053367d5d07.gif)

Hi, I'm experiencing random crashes. At first minder was crashing when I tried to rename root nodes, after reboot it's only crashing when data is cut out.. thanks for your time!

OS: elementary OS 5.1.7 Hera x86_64 
Kernel: 5.4.0-47-generic 
CPU: AMD Ryzen 5 3400G (8) @ 3.700GHz 
GPU: AMD Picasso
Memory: 2152MiB / 13986MiB 

**Edit 1:**
Added minder version

com.github.phase1geo.minder —version
1.10.0

**Comment by nerdpferd** [comment]
![Screen record from 2020-09-21 13 29 04](https://user-images.githubusercontent.com/57867806/93761703-86d3f180-fc0e-11ea-9932-7258d44fb39f.gif)

Fyi - continues crashing when renaming root nodes..

**Comment by phase1geo** [comment]
Version 1.11.0 is awaiting review in AppCenter. Curious to know if this problem still exists in that version. I’m not seeing any issues on my end with the latest. I’ll keep this issue opened until you can confirm that 1.11.0 is working.

**Comment by phase1geo** [comment]
@nerdpferd Can you let me know if version 1.11.0 contains this problem or not?

**Comment by buschwa** [comment]
I'm experiencing both crashes in 1.11.0.

**Comment by phase1geo** [comment]
Version 1.11.1 is in the elementary OS approval queue.  I would like to know if the problem still persists with that version.  If not, I'm going to need to get stacktrace information on this issue so we can get to the bottom of this.  To get stacktrace information, you'll need to download the latest master branch version of the codebase and run Minder with the './app debug' command-line option when running from the top-level GitHub directory.

**Comment by nerdpferd** [comment]
Sorry for the late feedback - yes, the issue is still there :( 
I'll download the latest master branch tomorrow to get the stacktrace information - will get back to you then!

**Comment by jaslar** [comment]
I downloaded 1.11.1, and trying to edit the root node causes an immediate failure.

**Comment by phase1geo** [comment]
I have just released version 1.11.2 that should have this issue fixed now.  I thought that these changes were already in 1.11.1, but I was wrong.

**Comment by AnggaRifandi** [comment]
I can confirm this issue fixed with the latest release (1.11.2)
