### ISSUE TITLE
Undo Add Root Node doesn't undo

### ISSUE THREAD

**Issue by sl-thomassaliou** [phase1geo/Minder#226]
After creating a root node, undoing creation is not possible.
Expected behavior from my perspective, would be do be able to undo a node creation.

Reproduce:
- Hit Enter on a new map (or right click New Root Node)
- Hit CTR-Z (or try undo button)

**Comment by phase1geo** [comment]
Are you using version 1.11.0?

**Comment by sl-thomassaliou** [comment]
Indeed not, 1.10.0-1.fc32 from fedora 32 repos...
Sorry if that's already fixed then :)

**Comment by phase1geo** [comment]
I just checked 1.11.0 and was surprised to see that I don't have code support for undo'ing a root node (yikes!).  I will get this fixed ASAP.  I am planning on releasing a 1.11.1 version which fixes a few issues including this one sometime in the near future.

**Comment by phase1geo** [comment]
I have fixed this issue in the devel branch which will be generally available in the next stable release.

**Comment by sl-thomassaliou** [comment]
Awesome ! Thanks :+1:
