### ISSUE TITLE
Shortcuts dissapear on white theme

### ISSUE THREAD

**Issue by gavr123456789** [phase1geo/Minder#229]
![Peek 2020-09-30 10-06](https://user-images.githubusercontent.com/30507409/94653739-b5378800-0304-11eb-92dc-287b16a02b3f.gif)
(It doesnt on dark)

**Comment by phase1geo** [comment]
That sounds like a Gnome or Granite theming issue. I’m using the Granite.AccelLabel widget to display shortcuts.

**Comment by phase1geo** [comment]
I don't think there is anything that I can do from within Minder to fix this issue so I'm going to close this issue.
