### ISSUE TITLE
bug:  nodes can overlap 

### ISSUE THREAD

**Issue by kvdz** [phase1geo/Minder#23]
![test](https://user-images.githubusercontent.com/4341214/43528883-fefd25f0-9577-11e8-974a-94638260adcf.png)

see image. this should not happen

**Comment by phase1geo** [comment]
I agree with this statement. Refactoring the layout of trees outside of the tree being edited is not currently supported. It is on the task list. For now you will have to move the trees in the canvas with the mouse cursor (as you have noticed). The position of the root node of each tree will not move by itself so it shouldn’t start to “fix” itself when edits occur which should lessen the number of times you need to move the trees around by hand. It’s not as good as automatic tree adjustment, but it shouldn’t happen often if you give each tree enough white space around them.

**Comment by kvdz** [comment]
oke cool, so it is on the roadmap to fix this then?

**Comment by kvdz** [comment]
also do you see the text color is green.  i used black map it doesn't give me the black background with white text.

**Comment by phase1geo** [comment]
The text color is really strange. I am specifically setting that color from currently selected theme and the foreground color is NOT green for any of the themes. I haven’t seen this behavior occur before.

**Comment by phase1geo** [comment]
Which OS are you running?

**Comment by phase1geo** [comment]
Are you saying that changing from the default theme to the dark theme isn’t taking effect?

**Comment by phase1geo** [comment]
The text color issue, I just realized, is a PNG artifact with making the image transparent. I don’t have an immediate fix for this issue; however, the latest version of Minder in AppCenter has support for exporting opaque PNG files (these images contain the background color of the selected theme). This issue is captured in a separate issue.

**Comment by mauriaguilar** [comment]
elementary os Juno
The new version only work in manual mode :(

![minder](https://user-images.githubusercontent.com/8943997/61190550-54c31900-a674-11e9-995d-4b14defca086.gif)

**Comment by phase1geo** [comment]
I have come up with a solution that I think will work well in practice. Root nodes of trees can be manually placed anywhere on the canvas; however, when nodes in other trees are changed such that tree overlapping can occur, the other tree nodes will be automatically moved, keeping their current spacing, to avoid this overlap issue.

The fix has been checked into the development branch.  It seems to be basically working at this point, but more testing will be done prior to the next official release.
