### ISSUE TITLE
Bad node placement

### ISSUE THREAD

**Issue by HROMANO** [phase1geo/Minder#236]
I often have overlaps and crossings between branches (without manual positioning). Maybe a bug in the positioning algorithm?

See attachment for example.

And thanks for that nice software.

![Capture d’écran de 2020-11-18 23-02-20](https://user-images.githubusercontent.com/5294632/99593744-72378e00-29f2-11eb-89e6-d3dc95d38d02.png)

**Comment by phase1geo** [comment]
Is the issue happening when you are folding and unfolding nodes? If so, that is a known issue that I hope to address in the next release.

**Comment by HROMANO** [comment]
It's when unfolding nodes for sure, but not completely sure for other cases. I will try to watch more carefully next time (and wait for the next release!).

If there's another ticket for that problem (I didn't find it before opening this one), just close.

Thank you

**Comment by phase1geo** [comment]
I believe that I have this issue fixed now in the devel branch which will be generally available in the next stable release.
