### ISSUE TITLE
Regarding funding

### ISSUE THREAD

**Issue by lrmodesgh** [phase1geo/Minder#239]
Hi,

It would be good if there is a explicit payment link, apart from elementary app center. I tried donating from it. Since banking issues still persist based on countries, i cannot either go fight with banks in india. It costs time. 

So please provide a bank account of librapay way to fund. I doubt that many have left funding just because the formal card payment method through app center is not working.

If possible please raise the issue in elementary app center development, to include internet payment or mobile payment.

**Comment by phase1geo** [comment]
I have enabled GitHub Sponsors if that would work for you.
