### ISSUE TITLE
No option to color node

### ISSUE THREAD

**Issue by dagelf** [phase1geo/Minder#245]
Should be trivial to add, right? Shall I go ahead?

**Comment by phase1geo** [comment]
Node colors use the same color as their link to their parent node.  You can change the color of a node by changing the link color in the current sidebar tab.

**Comment by phase1geo** [comment]
I have changed the "Link Color" label to just "Color" in the node sidebar to help indicate that changing the color will not just have an impact on the link.  Hopefully, this helps to clarify what this option does.

I have committed the change to the devel branch which will be generally available in the next stable release.
