### ISSUE TITLE
F10 keyboard shortcut should toggle Hamburger menu

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#248]

**Comment by phase1geo** [comment]
Minder doesn’t implement a hamburger menu.

**Comment by nekohayo** [comment]
What is this delicious thing, then?

![Screenshot from 2020-12-09 23-02-56](https://user-images.githubusercontent.com/479401/101720129-caeacb80-3a72-11eb-9ccb-311a92becdc1.png)

**Comment by phase1geo** [comment]
In elementary it's represented as a cog. At any rate, it's not a menu subsystem any more than any of the other header bar buttons are.
