### ISSUE TITLE
Export node notes as annotation comments in exported PDF

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#249]
It would be really nifty if the resulting exported PDFs had the nodes' "notes" text set as a PDF annotation comment, so that people viewing the results in Evince or Adobe Reader could read the node's notes by hovering the mouse over them.

**Comment by phase1geo** [comment]
The process of creating PDFs is something that I get by using a Gtk draw area widget. I am not able to layer this type of functionality without writing a custom PDF generator which I do not plan to implement.

**Comment by phase1geo** [comment]
This is a cool idea, but I'm going to close it out since making it work would require a crazy amount of work for not much feature gain.
