### ISSUE TITLE
Sorting of top-level children nodes is broken when switching to "Horizontal" or "Vertical" global node layouts

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#251]
When switching from the left/right/top/bottom-aligned node layouts to the "Horizontal" or "Vertical" (circular/two-sides) layouts, the custom sorting of your top-level nodes gets changed, and does not get restored when switching back to the left/right/top/bottom-aligned single-side layouts.

**Comment by phase1geo** [comment]
Horizontal and vertical layouts automatically balance their child nodes; therefore, both child order will be lost.  Maintaining child positions will not cause the tree to be properly balanced. I believe that undo'ing a layout change should restore everything to its previous state.

I'm not going to fix this as it would break tree balancing and adds unneeded code complexity and data storage.
