### ISSUE TITLE
It is possible to confuse the "Focus" mode

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#253]
1. Select a node
1. Click the Focus toolbar button
1. Deselect the node
1. Click the Focus toolbar button

Result: the Focus button now remains sensitive, and can be toggled back on even if no node is selected.

**Comment by nekohayo** [comment]
Food for thought: wouldn't it make more sense (and simpler to manage) to have the focus mode be a global state that does not depend on having a selected node to toggle it on, and that it would simply not make the things transparent when no node is selected?

**Comment by phase1geo** [comment]
Treating it like a global mode seems like it would make sense.

**Comment by phase1geo** [comment]
I have a revised implementation of focus mode to work as a global mode committed to the devel branch. This will be generally available in the next stable release.
