### ISSUE TITLE
In the contextual (right-click) menu for a selected node, combine the Add actions into a submenu (at least on smaller screen heights / resolutions)

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#255]
The "Select >" actions are all grouped into a submenu, which makes sense.

The "Add"-related actions should also be a submenu, for consistency and for space savings. On my 1366x768 ThinkPad laptop (be glad I'm not running on a 600px-high screen resolution; some people do have that), this stuff can't fit on my screen without scrolling and, well, scrolling sucks :) Besides, it's kind of overwhelming visually speaking.

Either it should be in a submenu for everyone, or if you really want them to be "in your face" on big screens, then it could be done dynamically only on smaller screen resolutions.

**Comment by phase1geo** [comment]
This has been implemented in the devel branch and will be generally available in the next stable release.
