### ISSUE TITLE
Provide a GtkEntry widget for the editable node title in the sidebar

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#256]
Instead of relying just on people using keyboard shortcuts or double-click, I believe the selected node's name/title should be shown in a GtkEntry in the sidebar. Not only could you edit the "notes" (a.k.a. description) for it, you could change the title in the same spot. It would be more accessible, and there's plenty of space for that in the sidebar anyway...

**Comment by phase1geo** [comment]
It used to be there, but was removed because of its redendancy. Editing node titles is more than simply editing text as you can syntax highlight and interact with that text (ex. Click on URLs, etc.). It’s inclusion in the sidebar made for a lot of additional code.

**Comment by nekohayo** [comment]
Ah OK then, I thought it was just an afterthought. But then, why would you have clickable URLs in the names but not in the notes?

**Comment by phase1geo** [comment]
Note URLs are clickable also.

**Comment by nekohayo** [comment]
I had no idea (especially since there is no hyperlink-like blue+underlining formating), and attempting to click them now didn't seem to work until I accidentally held Ctrl while mousing over them in the notes field. Well if it meant a lot of extra code that couldn't be shared with the notes field's code and you don't want the name field to be in there, then I guess I'll just close this ticket.
