### ISSUE TITLE
Branch colours overlap

### ISSUE THREAD

**Issue by Visualvengeance** [phase1geo/Minder#261]
Hey, thank you for creating such a useful piece of software!

Seems like when creating multiple branches with the squared style (it happens with other styles too, but harder to notice) the colours for certain branches are overlapped by the last created branch. This looks weird, since in the upper part of the map colouring seems to work fine, but the mid to lower part is covered by the last node's branch colour.

Here's a screenshot:

![Screenshot from 2020-12-21 09:07:08](https://user-images.githubusercontent.com/23021041/102755973-7ba87300-436f-11eb-999b-c6be86d7a4f7.png)

**Comment by phase1geo** [comment]
The nodes were being drawn from first to last in each parent, leading to the type of display shown.  I have checked in a change to the devel branch which changes the order that nodes are drawn to make the links be drawn in a more pleasing way.  This change will be generally available in the next stable release.

**Comment by Visualvengeance** [comment]
Your work is amazing, thank you very much for fixing this, your software helps me a lot. 

Thank you and happy holidays to you!!
