### ISSUE TITLE
Crash on first type

### ISSUE THREAD

**Issue by aral** [phase1geo/Minder#262]
## To reproduce

1. Install from App Centre
2. Launch app using Open button
3. “Main idea” node is selected; start typing

## What happens?

Crashes.

## What should happen?

Should not crash.

## Reproducibility

On restart, the same thing happens every time when I select the “main idea” node and start typing.

## System details

Running on latest stable elementary OS on StarLabs LabTop MkIV.

```
OS: elementary OS 5.1.7 Hera x86_64 
Host: LabTop Mk IV 
Kernel: 5.4.0-58-generic 
Uptime: 3 days, 2 hours, 17 mins 
Packages: 2045 
Shell: zsh 5.4.2 
Resolution: 1920x1080 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 6093MiB / 15883MiB 
```

**Comment by phase1geo** [comment]
I’m not sure what happened when 1.11.3 was built for elementary, but if you download Minder from GitHub master branch and build/install it from source, you shouldn’t see this issue. Hopefully, when the next stable release it made, the App Center issue will not rematerialize.

**Comment by aral** [comment]
Thanks for the update and hope you track down the issue with the App Center build (it happens, had it happen to an App Store update on iOS for one of my apps once).

Looking forward to using it once the new version is out :)

Hope you’re having a lovely end of year.

**Comment by Fatih20** [comment]
This still happens to me.

**Comment by jessbringlarsen** [comment]
Just installed Minder from App center and ran into this issue. One workaround I found is to deselect the text and only then can I edit the text...

**Comment by phase1geo** [comment]
I have a new 1.12.0 revision waiting in the elementary OS app approval queue.  I'll be interested to know if this issue still exists with this new version.

**Comment by panoskouf** [comment]
For me it happens If text is selected but cursor is not shown, in this case I click the text until the cursor appears and text is not selected then I can type without it crashing

**Comment by phase1geo** [comment]
I'm assuming that this issue no longer exists with the 1.15.6 version.  Feel free to close this issue if that is the case.

**Comment by aral** [comment]
Confirmed as working in 1.15.6. Thanks, @phase1geo :) Closing.
