### ISSUE TITLE
Hyperlink is not saved

### ISSUE THREAD

**Issue by r-vorlicek** [phase1geo/Minder#265]
Hello.
I have a problem with saving a hyperlink attached to the node. When I add a link via "Add link" in context menu it is not written to file. It is working but when I restart Minder it disappears.

docs: https://github.com/phase1geo/Minder/wiki/Adding-URL-Links
version: 1.11.2
os: Fedora 33

Robert Vorlicek

**Comment by phase1geo** [comment]
I believe that I have this issue fixed in the devel branch which will be generally available in the next stable release.
