### ISSUE TITLE
issues with auto-layout - node overlap and strange floating of node

### ISSUE THREAD

**Issue by daveiro** [phase1geo/Minder#266]
Hi there, after importing a mindmap from freeplane, the import went ok, but I am facing some strange auto-layout issues. Some branches get their content overlapped, some float in a strange way just while panning through the canvas... Can I send you by e-mail the file having the issues and a small video of screen recording showing the issues? Since it has some private content I would not like to post it in public. Thanks!

**Comment by phase1geo** [comment]
Sure, you can email me the information.

**Comment by phase1geo** [comment]
I believe that these issues have already been fixed in the devel branch which will be generally available in the next stable release.

**Comment by phase1geo** [comment]
I believe this is a duplicate issue of #236.

**Comment by daveiro** [comment]
yes it seems related to issue 236, but I tested the mindmap I shared with you with the latest development branch (as of 6 days ago) and I was having the issues as reported...
