### ISSUE TITLE
when selecting several nodes one cannot drag and drop the selected set

### ISSUE THREAD

**Issue by daveiro** [phase1geo/Minder#268]
the expected behavior (happening in freemind/freeplane) is that: while clicking on one of the nodes in the selection, one can drag all of the selected nodes to a new parent or just change their relative position to some other place in the middle of their siblings; what currently happens is that the selection is lost and just the clicked node is selected

**Comment by daveiro** [comment]
sorry I noticed now this is a duplicate of issue #243 so this can be deleted/removed

**Comment by phase1geo** [comment]
Since this is a duplicate of #243, I'm going to close out the issue just to clean things up.  Keep in mind that #243 is not closed at this point.
