### ISSUE TITLE
Native Window Border

### ISSUE THREAD

**Issue by sebelk** [phase1geo/Minder#269]
Hi, happy new year!
I use the version 1.11.3.
The app is nice, powerful and user-friendly. The only thing that I've found something annoying is that that it uses its own window border. I'd like to use the kwin one (yup, I am a happy plasma user).
Is there a way to change to a native window border?
Thanks in advance

**Comment by phase1geo** [comment]
I have no idea. Minder doesn't make any window border manipulations (I'm not sure that application code has this capability).  It is built using Gtk, so possibly there is some sort of border display issue there that doesn't make it look like a Qt app.  This issue is beyond what I can do for you.
