### ISSUE TITLE
Use a GResource instead of installing icons

### ISSUE THREAD

**Issue by danrabbit** [phase1geo/Minder#27]
https://github.com/phase1geo/Minder/blob/aa5430de48820c74fdc6b43c54dc8f1655f789e7/data/meson.build#L31

Instead of installing icons to the filesystem, Minder should use a GResource to load them. This reduces the likelihood of IO errors and ensures that file naming conflicts won't occur.

It looks like you already have your stylesheet as part of a gresource so all you need to do is add your icon names here and then tell your app to load your resource as an icon theme source like so: https://github.com/lainsce/quilter/blob/6364189b90befe9316f36ddba5984fec45d3d914/src/MainWindow.vala#L141

**Comment by phase1geo** [comment]
I have made the recommended changes in the main branch of the project. They will be applied in the next release.
