### ISSUE TITLE
Properties sidebar gives root node link color.

### ISSUE THREAD

**Issue by Visualvengeance** [phase1geo/Minder#270]
Happy new year!

Ways to reproduce the bug:
Make sure the properties sidebar is hidden, now select the root node and bring up the properties sidebar back again and you should see that the root node displays a link color option, it even shows the last used color as an option.

Another way to reproduce this is by just having the root node selected with the properties sidebar on, hiding it then bring it back up again leads to the same result.

**Comment by phase1geo** [comment]
This issue should now be fixed in the devel branch and will be generally available in the next stable release.

**Comment by Visualvengeance** [comment]
Thank you for your amazing work!
