### ISSUE TITLE
Children group overlay still appears without shrinking when parent folds the children.

### ISSUE THREAD

**Issue by akaibukai** [phase1geo/Minder#272]
Hello,

First of all thanks for the tool..
If I have for example the following map:

    - ROOT
      - A
        - A1
        - A2
        - A3
      - B
        - B1

And that for example I only select children of A (Might be all or a subset) but without selecting the parent A.
And then make a group..
Then if I select A and fold its children, the Group overlay stay in place..

However, if I had selected A and made a Group (thus the overlay being on A and all of its children) and then folded A, the group overlay correctly shrink.

**Comment by phase1geo** [comment]
I have fixed this issue in the devel branch which will be generally available in the next stable release.

**Comment by akaibukai** [comment]
Hey!
Wonderful. Thanks. I would like to contribute, but unfortunately, I don't know vala..
Thanks for your software. I tried so many tools on linux, unfortunately many of them seem a legacy from the previous century :\
Your version is lean and do the job!

Anyway, I currently have version 1.11.3 installed have you an idea from when 1.12 will be out?
I'll probably try to build from source though.

Thanks again and hope the best!

**Comment by phase1geo** [comment]
It will be another month or so, I would think.
