### ISSUE TITLE
Appimage release

### ISSUE THREAD

**Issue by cgvirus** [phase1geo/Minder#276]
Hello thanks for this awesome app. Will there be an appimage release? Thanks.

**Comment by phase1geo** [comment]
I don’t create packages for Minder. I leave that up to motivated users ;). So that is a no from me, but I can’t speak for others.

**Comment by cgvirus** [comment]
Ok, If I make one can I PR it in this repo and here?:
https://www.appimagehub.com/

**Comment by phase1geo** [comment]
I would release the app image from the hub. We can add the location of the app image to the Minder  README.md file.

**Comment by cgvirus** [comment]
Alroght. Will let you know. Closing the issue for now. Thanks.
