### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by btd1337** [phase1geo/Minder#28]
```
meson.build:15:0: ERROR:  Resource "icons/16/minder-layout-up-symbolics.svg" listed in "data/com.github.phase1geo.minder.gresource.xml" was not found. If this is a generated file, pass the target that generates it to gnome.compile_resources() using the "dependencies" keyword argument.

A full log can be found at /home/arch/.cache/aurman/minder-git/src/Minder/_build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...
```

Correct file is: `icons/16/minder-layout-up-symbolic.svg`

**Comment by phase1geo** [comment]
Sorry about that. I made some edits from my iPad that I submitted but was not able to compile/run them as of yet. I’ll get everything compiling again in a few hours or so.

**Comment by btd1337** [comment]
@phase1geo I suggest u to create a develop branch.

**Comment by phase1geo** [comment]
The issue has been fixed in the main branch.

**Comment by ChristopherNugent** [comment]
Check out https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows for info on branching workflows.

**Comment by phase1geo** [comment]
Thanks for the feedback and link. I have setup a development branch to work on a new Minder feature that will take a while to develop.
