### ISSUE TITLE
Color fill decreases padding by one

### ISSUE THREAD

**Issue by Visualvengeance** [phase1geo/Minder#280]
Ways to reproduce: 

Increase padding size from default to any value, now turn on color fill. Padding size size decreases, this only happens once each time the padding size is changed. This bug also triggered the same way by color filling being turned off.

**Comment by Visualvengeance** [comment]
Something similar seems to happen with connection padding size, but I can't seem to get it reproduced reliably.

**Comment by phase1geo** [comment]
This issue has been fixed in the devel branch and will be generally available in the next stable release.

**Comment by Visualvengeance** [comment]
Thank you!
