### ISSUE TITLE
Property sidebar gear icon missing on ubuntu 20

### ISSUE THREAD

**Issue by alexjoverton** [phase1geo/Minder#283]
As per title, unless I am having a really bad day ..LOL I have no way of closing the property sidebar.
I have used many mindmapping programs, this one is by far the fastest and easiest to use. Simple keyboard shortcuts, that are logical. So thanks for sharing your work. Sorry if this has been reported already, I could not see anything obvious. I can't see the "about" menu to tell you which version.
I guess it's probably to do with the window manager.

**Comment by phase1geo** [comment]
An "About" function does not currently exist in the UI. This information is only accessible from the command-line. I will see about adding one though as I know most users probably don't invoke Minder from a command-line.

**Comment by phase1geo** [comment]
You you include a screenshot of Minder with the missing icon?

**Comment by phase1geo** [comment]
I have added an About window for non-elementary OS environments to the miscellaneous menu in the devel branch.  This will be generally available in the next stable release.

**Comment by alexjoverton** [comment]
> You you include a screenshot of Minder with the missing icon?
here you go
![Screenshot from 2021-02-01 09-47-11](https://user-images.githubusercontent.com/75419942/106435170-d1922f80-6472-11eb-90d5-c72574caa915.png)

**Comment by alexjoverton** [comment]
> I have added an About window for non-elementary OS environments to the miscellaneous menu in the devel branch. This will be generally available in the next stable release.

thanks

**Comment by phase1geo** [comment]
Looks like the gear icon is the hamburger icon in your environment.  That is probably a suitable icon for your environment.  The menu contains preferences and keyboard shortcuts menu items currently.  To close/open the sidebar with the header buttons, use the button to the right of the hamburger menu.  This button is used to open/close the sidebar.
