### ISSUE TITLE
Misleading Properties shortcut?

### ISSUE THREAD

**Issue by Keyikedalube** [phase1geo/Minder#286]
Properties shortcut `|` is actually a combination of Ctrl, Shift, and | keys
ie., `Ctrl + Shift + |`

![Screenshot from 2021-02-01 16-19-36](https://user-images.githubusercontent.com/24214509/106449061-95c68c80-64a9-11eb-96c4-b5b4269edf31.png)

I was browsing through the shortcuts window and noticed Properties keys mention only the vertical slash `|` symbol. Shift key is automatically implied because on my QWERTY keyboard that symbol lies above back slash `\` symbol.
I tried `Shift + \` which gives me `|` but that didn't work. Added control key just out of curiosity and that worked.

I use Fedora GNOME 33. Hope that behavior is not specific to only GNOME desktop.

**Comment by phase1geo** [comment]
The shortcut for this feature is changing in the next stable release. I have verified that the correct shortcut is documented in the keyboard shortcuts.
