### ISSUE TITLE
Export options to Markdown that include images, or directly export to static HTML

### ISSUE THREAD

**Issue by Luvata** [phase1geo/Minder#289]
Hi,
Thank you so much for publishing this awesome mind-map tool, it's so convenient and flexible, but also very powerful.

My use-case is I want to convert my mind map to a static html page (for github page), current Minder version hasn't supported it yet, so I guest I will convert it into Markdown, and then using [markmap js](https://markmap.js.org/) to convert it to html. But when exporting to Markdown, Minder didn't export the images (which I think should be saved in a sub folder, then have a soft link in the markdown file)

Maybe I'm missing something in Minder, how can I do that ?

**Comment by phase1geo** [comment]
This is not currently possible, but I can see about implementing it.

**Comment by phase1geo** [comment]
Out of curiosity, could you save the mind map as a PNG and just display the image in a web browser?

**Comment by Luvata** [comment]
Yes, but it's not as flexible as a Markdown file (can't search on image).
Most of my images in Minder was screenshot and pasted from clipboard
I found that I can overcome by export to XMind, then extract the xmind file to get my image folder, then fix the path in Minder to relative path to the images... Not the best way thought

**Comment by phase1geo** [comment]
Makes sense.

**Comment by phase1geo** [comment]
I have some local changes which add the ability to include image links to the generated Markdown.  I have installed VS Code and the Markmap plugin.  The mind-map is properly drawn; however, the images are not being displayed even though I'm providing the full pathname to the PNG image.  Do you have any ideas about image support by this plugin?  The Markmap documentation seems to be a bit lacking.

**Comment by phase1geo** [comment]
Okay. I have a working version checked into the devel branch which will be generally available in the next stable release.  If you want to give it a try before the stable release is available, that would be great.

**Comment by phase1geo** [comment]
Oops.  I missed the fact that you want to put this on GitHub.  The images are not portable in that sense with the current implementation.  I will need to copy the images out to a directory to help make the HTML portable.

**Comment by Luvata** [comment]
You are so efficient Trevor. Thank you so much ! I will definitely try it when I come home today

**Comment by phase1geo** [comment]
Okay, I believe that I have everything checked into the devel branch to support Markdown with images.  Give it a try and let me know your thoughts about it.

**Comment by Luvata** [comment]
Thank you so much !!!

I checkout the devel branch and every worked as expected ! :100:
