### ISSUE TITLE
Feature Request: alternate line interpolation choices

### ISSUE THREAD

**Issue by ChristopherNugent** [phase1geo/Minder#29]
It would be nice to have a few choices for the interpolation of the drawing of the lines between nodes. A curved line option or two to provide a more polished look to the application.

**Comment by phase1geo** [comment]
Thanks for the suggestion. I actually have that as a future feature enhancement. I am curious to know if it would be useful to make the link lines also become thinner the further from the root node of the tree (or potentially make it an option).

**Comment by phase1geo** [comment]
I have added support for this feature (as well as many other styling controls) in the current development branch which will generally available in the next release (1.2).
