### ISSUE TITLE
Exported image crops connector lines that are outside the main nodes' boundaries

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#292]
After connecting nodes, I often grab the middle of the connector lines to make them go "around" the big pile of nodes in the tree, so they look nice and clean.

The problem is that when you export (ex: to PNG), the app crops the image to roughly the rectangle comprising the mindmap's nodes plus a small margin, but that margin is insufficient to include the big curvy connector lines that go from one extremity of the tree to the other... ideally it should frame the export to tree + connectors, and then if I want to actually crop tighter I could use GIMP for that.

**Comment by phase1geo** [comment]
I have updated the master branch with a fix for this issue.  I was also not including stickers that were attached to the mind map to the overall document boundary calculation, so that issue has been fixed as well.  Both fixes will be included in the next stable release.
