### ISSUE TITLE
Inconsistent app state on startup when the last opened file was moved on the filesystem

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#293]
# Actual behavior
If you renamed/moved the last used Minder file(s), and launch Minder, it will "open" those files but display a blank canvas, and show the non-found files' name in the headerbar.

Using the Open button to load the new file from its new location then opens it in a new tab, with a remaining tab for the "ghost" open file.

# Expected behavior
If it fails to load/find a project file, it should display a truly default/empty app state, that gets replaced when opening a valid project file (unless there are unsaved changes in the blank project).

**Comment by phase1geo** [comment]
I haved fixed the issue with the tab contents being empty when the file could not be loaded properly in the master branch.  I still have a couple of bugs to fix related to opening a file, but this fix should take care of your issue.  This will be generally available in the next stable release.

**Comment by epsimpson** [comment]
I suspect this is related, though I never moved files, so I thought I'd just mention it to let you decide.

I have 3 files on disk, all in the same directory.  After a system update and reboot I reopened minder.  It opened 2 tabs, 1 empty and 1 containing the first map I had (ever) saved.  I closed the empty map tab telling it not to save when prompted.  Then opened the other 2 map files (double click in file manager) and they both displayed the map that was already open.  After a brief pause to express dismay, I closed minder completely, reopened the file I wanted, and it opened and displayed correctly (nothing had been lost).  Opening new files again all displayed THAT map.  Repeating with the 3rd map (closing minder completely, opening new file) repeated the experience with the 3rd map displayed no matter which map file I opened.

All file openings except the first were via double click in the kde Dolphin file manager.
The first was (I think) opening minder itself, which attempted to open the files by itself.

com.github.phase1geo.minder --version - 
displays:  "1.5.0"
sudo apt install minder
displays: "minder is already the newest version (1.5.1-1)"

system: kubuntu 20.04 64 bit

**Comment by phase1geo** [comment]
Version 1.5.0 is a pretty old version at this point.  The latest available in GitHub is 1.12.0.  The latest available in the elementary OS Debian repository currently is 1.11.2 (I'm waiting for 1.12.0 to be approved by the elementary development team).  I'm not sure why Kubuntu would be so far behind, but I'm not involved with their package management either, so I'm not sure what to say about this.
