### ISSUE TITLE
Connectors' drag handles for adjacent nodes are hard to grab

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#295]
I make extensive use of connector lines, sometimes across distant nodes, but also across adjacent nodes, and this is difficult to deal with:

![Screenshot from 2021-02-13 16-01-07](https://user-images.githubusercontent.com/479401/107861627-1de75300-6e15-11eb-8fd6-422b47bb78f6.png)

As you can see, the three blue circular drag handles are pretty much overlapping each other, and even if you set the desktop environment's accessibility settings to have a small mouse cursor size (instead of large, which I normally use) it's nearly impossible to accurately grab the handle you want to grab, which, in my case, is typically the middle one, because I want to curve the connector line significantly so that we can see the connector line, and make out the arrows as well. It often takes me 15-20 tries to be able to successfully grab the middle handle by chance.

I'm not sure how to solve this other than auto-curving the connectors by default when they are connecting adjacent nodes? Or allowing to attach the connectors to a particular cardinal side of a node (instead of just the center of the node) like you can do in LibreOffice Draw (it allows both approaches)...

**Comment by phase1geo** [comment]
I will see what I can come up with.

**Comment by phase1geo** [comment]
I have submitted changes to the master branch to help with this issue.  I have done three things here:

1.  The drag handle is colored yellow to help differentiate it from the connection handles.
2.  The drag handle is drawn on top of connection handles if they are too close together.
3.  The drag handle has precedent when the mouse cursor is over the drag handle and one of the connection handles, such that clicking and dragging over the drag handle will always move the drag handle.

This should make using short connections much easier to deal with.  Feel free to give it a try and let me know if it helps. This change will be generally available in the next stable release.
