### ISSUE TITLE
When two nodes are selected, shortcuts for linking or connecting are not available

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#296]
I just discovered now that there is a shortcut for connector lines, "x", and a shortcut for linking, "y". I had never realized because I naïvely selected two nodes before right-clicking to connect them (I guess I'm too used to inefficient software :) ...but even then, wouldn't it make sense to also allow the same shortcuts to work when two nodes are selected (to connect) or more (to link)?

Again thanks for this wonderful app of yours, it keeps surprising me as you can see ;)

**Comment by phase1geo** [comment]
I have added support for the x and y keyboard shortcuts when multiple nodes are selected in the master branch.
