### ISSUE TITLE
[Feature Request] Minimum Node Width setting

### ISSUE THREAD

**Issue by cesar404** [phase1geo/Minder#298]
Currently on Minder we can set the maximum node width using the option "width" on the side bar. It would be great if we had a "minimum node width" setting as well so that we could define the minimum width any node is allowed to have. Surprisingly this simple setting has a significant effect on mind map aesthetic. You can see this feature working on Freeplane; it's incredibly useful. 
![minimum node width](https://user-images.githubusercontent.com/2542431/109398425-a8eb4180-791b-11eb-9016-5b59cfb72bbb.png)

**Comment by phase1geo** [comment]
I have just checked in support for a new node "Fixed width" style setting.  This accomplishes the same effect as the minimum width mode that you show above.  This change is checked into the devel branch and will be generally available in the 2.0 stable release.

**Comment by cesar404** [comment]
Thanks a lot! 
BTW, sorry for opening too many requests in a short time. I've just found Minder and I'm very excited about it. I have some experience using mind map sofware, mostly Freeplane. Freeplane is an amazing piece of software, feature rich, but it unfortunately has some UI problems and doesn't work properly on high definition screens. Mind is a fantastic tool, despite being new. Obviously some features are still missing, which is why I'm making suggestions based on my personal use.
