### ISSUE TITLE
[Feature Request] Drag and drop nodes as siblings

### ISSUE THREAD

**Issue by cesar404** [phase1geo/Minder#299]
Currently we can drag and drop a node "A" over a node "B" so that A will become a child of B. It would be great if, as we drag A over B, we could choose wether A will be moved as a child node or as a sibling node of B according to a specific place where we drop it. In order to do this, we would need some visual cue/sign (as we hover over the target node) to decide where to drop the moving node. We could also, for example, choose wether A will be a sibling above or below B. You can see that more clearly on this video of mindmapper:
https://www.youtube.com/watch?v=FRr6cDmEyuo
Freeplane also has a similar feature.

**Comment by phase1geo** [comment]
I have this feature implemented in a feature release branch currently.  This will be generally available in the 2.0 release.

**Comment by cesar404** [comment]
Wonderful! Many thanks!

**Comment by phase1geo** [comment]
This functionality is available in 1.13.1.  Closing issue.
