### ISSUE TITLE
Use non-symbolic icons in HeaderBar

### ISSUE THREAD

**Issue by cassidyjames** [phase1geo/Minder#3]
The elementary HIG is to use full color icons in primary toolbars and headerbars. The symbolic icons look a bit out of place compared to other apps on elementary OS.

**Comment by phase1geo** [comment]
I have switched the header bar icons from symbolic to the associated non-symbolic icons. I have also increased the size from small to large to better match other elementary apps.

The changes have been committed to the master branch and will be available in the next AppCenter release.
