### ISSUE TITLE
[Feature Request] Show the number of collapsed nodes inside the folding symbol

### ISSUE THREAD

**Issue by cesar404** [phase1geo/Minder#300]
When we fold nodes/branches, a 2-dot symbol is shown; it indicates the existence of folded/hidden nodes at that spot. It would be nice if instead of the 2-dot symbol we had a circle (or other symbol) with the number of folded nodes in it. It would provide useful information about the size of the branch which is hidden.
Here are some videos showing it on Mindmanager:
https://www.youtube.com/watch?v=E7wrFFKaj24
https://www.youtube.com/watch?v=Prz-I8hn6ZE

**Comment by phase1geo** [comment]
I have implemented a new tooltip for the fold indicator that displays the number of folded children and descendants.  This is available in the devel branch and will be generally available in the 2.0 stable release.

**Comment by cesar404** [comment]
Many thanks! Maybe it's not exactly what I suggested, but I think it will, at least partially,  solve my needs.

**Comment by phase1geo** [comment]
I realize this isn't exactly what you were asking for, but it is a solution in keeping with the design language of the application and it provides the information that you are looking for, I believe.

**Comment by phase1geo** [comment]
Fair warning to you.  The 2.0 release changes the save file format from the one used in the 1.x releases which is non-reversable.  Testing this feature with Minder files saved in 1.x format will result in Minder files that will not be readable by a 1.x version.

**Comment by cesar404** [comment]
Thanks for the heads up!
