### ISSUE TITLE
[Feature Request] Show a fold symbol

### ISSUE THREAD

**Issue by cesar404** [phase1geo/Minder#301]
To fold nodes/branches we can use the "F" key, the context menu or the sidebar. But there is no "fold symbol" on the map branches, only an "unfold symbol". A folding toggle/button would allow us quickly fold/unfold branches just using the mouse. Faster than using the contex menu or the sidebar option. In some situations we want to use only the mouse. But I certainly don't want create needless visual pollution . That is why the fold symbol should appear only when we hover the mouse pointer over the folding spot. It would be fairly inconspicuous. That's how it works on Freeplane. 

Here are some videos showing it on Mindmanager:
https://www.youtube.com/watch?v=E7wrFFKaj24
https://www.youtube.com/watch?v=Prz-I8hn6ZE

**Comment by cesar404** [comment]
That feature would be particularly useful in presentations. In those situations you want to use mostly the mouse, folding and unfolding nodes/topics. Using the keyboard during presentations is not ideal.

**Comment by phase1geo** [comment]
I'll try to get this feature added for the 1.12.3 release.

**Comment by cesar404** [comment]
Great! Thanks.

**Comment by phase1geo** [comment]
I have added support for this feature in the master branch.
