### ISSUE TITLE
[Feature Request] Alignment commands on the sidebar

### ISSUE THREAD

**Issue by cesar404** [phase1geo/Minder#302]
When a map is set to "manual" layout, we can align a group of selected nodes based on the position of one of these nodes. We can only do that through keyboard shortcuts. It's a very nice feature and I'd like very much these alignment commands to be shown on the sidebar as well. There are many reasons for that. Firstly, discoverability. It took me quite some time to find that feature; it's kind of hidden. Also I personally am very bad at remembering all those keyboard commands. The possibility of accessing these functions on the sidebar would be much more convenient for me.

Here are some visual examples of the aligment feature on other sofware GUIs:

![alinhamento](https://user-images.githubusercontent.com/2542431/109436963-22a92b00-7a01-11eb-8c9c-b03772cf7a92.PNG)
![alinhamento illustrator](https://user-images.githubusercontent.com/2542431/109436967-29d03900-7a01-11eb-954d-0cbf23a3c324.PNG)
![alinhamento illustrator 2](https://user-images.githubusercontent.com/2542431/109436970-2e94ed00-7a01-11eb-8472-2a7fc7596d3b.PNG)
![Alignment-Tool-Icons-in-Editor-1](https://user-images.githubusercontent.com/2542431/109436972-3359a100-7a01-11eb-96bc-f30eefaab6ec.jpg)
![alinhamento impress](https://user-images.githubusercontent.com/2542431/109436973-381e5500-7a01-11eb-90e6-0b2dcc71e106.PNG)

**Comment by phase1geo** [comment]
This feature has been implemented in Minder versions 1.16.0 and later.  The alignment tools are located in the Map sidebar panel when manual layout mode is selected.
