### ISSUE TITLE
White border around arrowheads

### ISSUE THREAD

**Issue by cesar404** [phase1geo/Minder#307]
When "Link Arrow" is enabled and the branch is on a non-white background (inside a Group, for example) we can see a white border around the arrowheads. I suspect that border should be the same color as the link/node. Interestingly arrowheads always looked kind of "detached" from the arrow line. Is that intended?

![arrowhead](https://user-images.githubusercontent.com/2542431/109573016-fa86fe00-7acc-11eb-8fa6-5f44f2ba33ed.png)

**Comment by phase1geo** [comment]
The reason for the white outline on the arrowheads is more of a technical reason that helps the arrowhead to stand out from the line that it is attached to.  Ideally, it might be nice to have this outline not be as evident when in a group.  If I "fix" anything related to this issue, it might be to attempt to make the outline better match the group color that it is in.

**Comment by cesar404** [comment]
Okay. 
Just another minor issue that I'm not sure is related to that: When I enable "Link arrow" it doesn't align nicely  relative to the other links.
![arrow alignment](https://user-images.githubusercontent.com/2542431/109592874-c91f2a00-7aee-11eb-97de-7a90685978d8.png)

**Comment by phase1geo** [comment]
I have fixed this issue in the devel branch will be generally available in the 2.0 stable branch.

Note:  The 2.0 development version of Minder changes the save format on mindmap load that is not compatible with older versions of Minder.  If you want to test out this feature, mindmaps loaded or created in the development version will not be usable in older versions.
