### ISSUE TITLE
Arrows and node text vanished

### ISSUE THREAD

**Issue by iverik-no** [phase1geo/Minder#311]
First all the arrows vanished. After I tried to drag and drop a root node on another, several of them flew to far off corners of the map so that I had to zoom way out to move them back. The arrows was then gone.
Some of the nodes had text that was invisible until highlighted.

I've closed the program, reloaded the save file, created new project, reinstalled the app, reinstalled as Flatpak (1.12) instead of apt (1.9), and back again, and then back to Flatpak, but the issue persists accross all of them now. Even in new projects. 

And all writing is now gone or hidden too, except that which is under Notes. The boxes are the size of the writing that was there, but when clicking in the, they go back to "no writing" size.

Sorry if this "report" is a bit all over the place, but I genuinely don't quite know what to write except that stuff just vanished x)

As mentioned, this issue happened first in the apt version, then carried over to the Flatpak version. I've restarted (app and PC), uninstalled, reinstalled, tried creating new files etc.

**System details:**
Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2
Kernel Version: 5.10.9-051009-generic

![Screenshot_20210307_220251](https://user-images.githubusercontent.com/8539609/110254790-ef324780-7f90-11eb-9049-16324527729d.png)

**Comment by phase1geo** [comment]
Can you send me (or attach it to the report) the .minder file that is causing grief? I'd like to see the contents of the file.

**Comment by iverik-no** [comment]
Here you go:

[Videreutdanning-2021.zip](https://github.com/phase1geo/Minder/files/6097992/Videreutdanning-2021.zip)

**Comment by phase1geo** [comment]
Looks like the text is actually missing from the .minder file that you sent me.  I also don't see any connections in the .minder file also (thus the missing arrows).  Using the 1.12.0 version of Minder for creating the mind map should work better than the 1.9 version.  Unfortunately, it looks like the text is going to have to be recreated (unless you have a backed up version of the mindmap somewhere).

**Comment by iverik-no** [comment]
Aha. Well, it was fortunately not a huge and complex map, so it's not a disaster having to recreate it. 

However, the strange thing is that any new file I create is also missing the arrows. This for both 1.9 and 1.12. Even after reinstalling and creating fresh mindmaps.

**Comment by iverik-no** [comment]
Update: After purging the Flatpak and removing all config files/directories in the dot-directories of User/, I was able to get it to work as it did prior to arrows and text flying off into oblivion.

**Comment by phase1geo** [comment]
Could you send me a copy of the latest .minder file that exhibits this behavior?

**Comment by iverik-no** [comment]
[123.zip](https://github.com/phase1geo/Minder/files/6109242/123.zip)
123.zip contains one of the borked .minder files i made trying to see if it was just my main file that was broken, or if it happened to others as well. It's missing arrows, but the text is there.
[asd.zip](https://github.com/phase1geo/Minder/files/6109247/asd.zip)
asd.zip contains a new .minder file, created just now, which works as it should.

**Comment by phase1geo** [comment]
I'm not exactly sure what happened to cause this, but the linkwidth value for all links got set to a negative value.  You should be able to fix the broken map just by adjusting the "Line Width" option in the "Link Options" when no nodes are selected.  Changing the value will correct the 123.minder file, if it matters to you.

**Comment by iverik-no** [comment]
The 123.minder was just for testing purposes, so it's really just a junk file :) I've recreated the original map, more or less, and as mentioned it wasn't very complex so it wasn't a big deal. Hopefully there's something usefull to be gleamed from the broken files that might help you track down what caused it.
