### ISSUE TITLE
Build Error on Ubuntu 20.04

### ISSUE THREAD

**Issue by junghan0611** [phase1geo/Minder#312]
Project name: com.github.phase1geo.minder
Project version: 1.12.1
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Vala compiler for the host machine: valac (valac 0.48.6)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Configuring config.h using configuration
Dependency gtk+-3.0 found: YES 3.24.20 (cached)
Message: Using VALAC048
Library m found: YES
Library markdown found: YES
Dependency gobject-2.0 found: YES 2.64.6 (cached)
Dependency glib-2.0 found: YES 2.64.6 (cached)
Dependency cairo found: YES 1.16.0 (cached)
Dependency gee-0.8 found: YES 0.20.3 (cached)
Dependency granite found: YES 5.3.0 (cached)
Dependency gtk+-3.0 found: YES 3.24.20 (cached)
Dependency libxml-2.0 found: YES 2.9.10 (cached)
Dependency libarchive found: YES 3.4.0 (cached)
Dependency gtksourceview-3.0 found: YES 3.24.11 (cached)
Program meson/post_install.py found: YES (/home/junghan/Downloads/Minder/meson/post_install.py)
Build targets in project: 11

Found ninja-1.10.0 at /usr/bin/ninja
[123/123] Linking target com.github.phase1geo.minder.

**(com.github.phase1geo.minder:17601): GLib-GIO-ERROR **: 04:39:12.746: Settings schema 'com.github.phase1geo.minder' is not installed
./app: line 44: 17601 Trace/breakpoint trap   (core dumped) ./com.github.phase1geo.minder "${@:2}"**

**Comment by phase1geo** [comment]
You will need to install the application before running it for the first time.

**Comment by junghan0611** [comment]
> You will need to install the application before running it for the first time.

Wow, It works!!
Thanks
