### ISSUE TITLE
right click enhancement

### ISSUE THREAD

**Issue by cesar404** [phase1geo/Minder#313]
Let's say node "A" is selected and I want to execute an action on node "B". So, using my mouse, I right-click on node "B" and then a context menu appears. I choose an option on the context menu, but unfortunately the action is applied to node "A", not "B", since "A" was selected. I should have selected "B" before right-click on it. 

I would like to be able to right-click on any node and perform an action on it, even if another node was previously selected. So, when we right click on a node two things should happen simultaneously: the node would be selected and a context menu would appear. That would be a more efficient behavior and would save us some time. That's how it works on Freeplane.

**Comment by phase1geo** [comment]
I need some additional clarification.  If multiple nodes are selected and you accidentally right click on any node (selected or not), should I still perform the specified behavior?

**Comment by cesar404** [comment]
> If multiple nodes are selected and you accidentally right click on any node (selected or not), should I still perform the specified behavior?

In that case we would have 2 possibilities:
1) if you (accidentally or not) right click on one of selected nodes: the behavior should be applied to all selected nodes.
2) if you (accidentally or not) right click on any unselected node: the behavior should be applied only to that unselected node you have just right-clicked on.

**Comment by phase1geo** [comment]
Makes sense to me. Thanks!

**Comment by cesar404** [comment]
3) If multiple nodes are selected and you right click on the background: the behavior should be applied to all selected nodes.

**Comment by phase1geo** [comment]
I believe that I have this issue addressed in the master branch.
