### ISSUE TITLE
Change required for AppCenter: Crash on initial input

### ISSUE THREAD

**Issue by cassidyjames** [phase1geo/Minder#319]
The [1.12 release from the AppCenter testing repo](http://packages.elementary.io/testing/pool/main/c/com.github.phase1geo.minder/com.github.phase1geo.minder1.12.0-dad64c.deb) seems to crash on initial input on elementary OS 5.1.

**Comment by phase1geo** [comment]
I need a debuggable version of this application to get proper stack trace information to help understand what is going on.  The application doesn't crash when built with ninja locally on my elementary OS 5.1 machine, but the last couple of versions do.  Unfortunately, the .deb file doesn't contain a version that is built with debug symbols enabled.

Could you provide me the build command(s) to create my own .deb file that should match what is being built by AppCenter?

**Comment by phase1geo** [comment]
It appears that the 1.13.1 version that is currently available in the AppCenter is working as expected.  Closing issue.
