### ISSUE TITLE
Variances in font sizes across computers are reflected in Minder's nodes, requiring manual intervention to force them to resize

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#341]
On my desktop workstation, my font scaling factor (which you can set in gnome-tweak-tool) is 1.10 to compensate for my screen's too-high-DPI and my old eyes, whereas on my laptop's tiny screen I have set the font scaling factor to 0.90 to be able to fit more things on the screen.

The problem is that Minder seems to depend on the rendered font sizes to determine the width of the nodes, text wrapping, etc., and does not update that on startup/open, which leads to this result when opening on my workstation a minder file that was created on my laptop:

![Screenshot from 2021-04-21 09-47-23](https://user-images.githubusercontent.com/479401/115565106-16b24a80-a287-11eb-848f-2b65cfb16d69.png)

Only when you select each node, one at a time, do they then get autoresized to the correct width.

I'm not sure how to tackle this problem, to either make the node sizes calculated in a resolution-independent manner somehow, or if they simply  need to be all refreshed upon file opening...

**Comment by phase1geo** [comment]
Valid issue. Minder uses stored values to do the initial drawing operation. Sounds like this is inadequate in this situation. Hadn't thought of that. I'll see what I can do.

**Comment by phase1geo** [comment]
I have attempted to fix this issue in the master branch.  Could you try building it and giving it a try on your end?
