### ISSUE TITLE
Home/End keys go to the beginning/end of the node's entire text, rather than the current line

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#342]
I've been encountering this issue multiple times so I'm now reporting it, as I keep getting weirded out by the behavior (so it's not just a question of "getting used to it"): when I'm editing a node's text directly in the canvas, I use:
* the up/down/left/right arrow keys to go to lines above/below,
* ctrl+left/right to jump from word to word (and Ctrl+Shift+left/right to select whole words),
* "Home" and "End" to go to the beginning or end of the line where the text cursor currently is.

The last one doesn't work as expected, it doesn't take lines into account and just goes to the beginning/end of the whole text, which isn't what I want, and it isn't consistent with other applications, particularly text editors (gedit, libreoffice, the browser's text fields such as this github comment, etc.). If I wanted to go to the "absolute beginning" or "absolute end", I would use Ctrl+Home or Ctrl+End (or I could use the up/down arrow keys and then Home/End).

**Comment by phase1geo** [comment]
I have fixed this in the master branch which will be available in the 1.12.2 release.
