### ISSUE TITLE
Data loss can sometimes occur when selecting whole words at the end of a node's text to remove them

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#343]
1. Type a multiline node name such as "Lorem ipsum dolor sit amet blah blah banana", hit Enter
2. press E to edit it
3. click to put the mouse cursor just before "banana" (after "blah ")
4. Ctrl+Shift+Right-arrow, which selects the word "Banana"
5. Hit the "Delete" key on the keyboard

Result: nothing seemingly happens, the word is still there, but if you close the app/document (ctrl+W) and then reopen the document, the node will now be an empty text string, having lost its data. This happens to me surprisingly often.

**Comment by nekohayo** [comment]
Potentially found another way to trigger it. It might have something to do with the fact that I use ctrl+left/right to move across words in editable texts?

1. Have a node called "Same-sign-on (directory server authentication; typiquement LDAP)", which on my computer, is wrapped onto 3 lines.
2. Go back to edit it (with the "e" key).
3. right-arrow key (to deselect all), which puts your cursor at the end
4. up-arrow key to go up one line
5. ctrl+left to move the cursor just before the "authentication" word, after "server"
6. shift+down to select from "authentication" to the corresponding character position on the line below it

Notice then that the selection is incorrect, it's missing random parts of the string; sometimes just "aut", sometimes "authenticat", sometimes "authentication; typique", etc.:

![Screenshot from 2021-04-21 12-23-45](https://user-images.githubusercontent.com/479401/115588628-f097a500-a29c-11eb-8f67-9541a8b8f3b4.png)

![Screenshot from 2021-04-21 12-26-43](https://user-images.githubusercontent.com/479401/115588637-f2f9ff00-a29c-11eb-9e4b-8d0527caab30.png)

I don't know how exactly this behaves, or even if that's _the_ cause, but maybe it's a contributing factor. As soon as you start playing with selections, especially with Ctrl and Shift, I suspect you may encounter various manifestations of this problem too.

**Comment by phase1geo** [comment]
I have fixed two issues in the master branch.

1. When text was selected at the end of the text and the Delete key was used, the text was not being deleted.  When text was selected at the beginning of the text and the Backspace key was used, the text potentially would not be deleted.

2. Changing the selection immediately after moving the cursor by a word would cause issues with the selection.

I have not been able to reproduce any data loss issues as described in this issue to date.  If you could attempt to test the master branch and let me know if there is a way to reproduce the data loss issue, I would appreciate it.

**Comment by nekohayo** [comment]
FWIW, I've still been experiencing some weird unpredictable corner cases where I do get Minder confused and lose some words when using various movements/insertions/deletions of words, this happens on 1.14.0 still, but I so far have been unable to have an obvious ah-ha moment of what triggers the _data loss_ danger scenario specifically, it always seems to happen when I don't expect it (even 2 minutes ago, it happened to me); when I try to explicitly test/trigger it, of course it doesn't happen...

However I have found a couple more issues when using Ctrl+Shift + arrow keys selection combos, which you can see demonstrated in this video (really hard to explain textually otherwise): https://youtu.be/3etf8TVfrLo

Maybe they're somehow related? If not, fixing them would at least clear the view for whatever remains in terms of bugs there, as it currently might be under the fog of war.

**Comment by nekohayo** [comment]
Alright, in addition to what's shown in the video above, I found at least _one_ instance of reproducible data loss now, here's a video demonstration of it: https://youtu.be/QzWTIt2NGww

I don't know if that's the only case where this sort of thing might happen though, so feel free to testsuite the hell out of this ;)

**Comment by phase1geo** [comment]
Okay, the good news is that all of these issues are related to the same underlying issue.  I'll get to work on a fix soon.

**Comment by phase1geo** [comment]
By the way, I appreciated the screencasts of the issue.  It made it easy to identify the root cause or the problem.
