### ISSUE TITLE
minder 1.12.1 crashes when i want to create a new theme and i can't open old document created with an old version

### ISSUE THREAD

**Issue by MartineMin** [phase1geo/Minder#348]
I have now installed the new version 1.12.1 but first i can't open my documents created with the version 1.5. and when i creat a new document when i want to create a new theme. Minder crashes. 
My system is Ubuntu 20.04
Could you help me?

**Comment by phase1geo** [comment]
You will need the latest from the master branch (1.12.2) to get things to work.

**Comment by MartineMin** [comment]
ok thanks
