### ISSUE TITLE
Guy who uses Minder

### ISSUE THREAD

**Issue by jgraves1q2w** [phase1geo/Minder#351]
Minder crashes immediately when I try to run it on PopOS 20.10.  Worked last night wont open today.  Really like the software so far.

**Comment by phase1geo** [comment]
I have fixed an issue in master that fixes a startup application crash in Manjaro.  I'm in the middle of getting a Pop! OS 20.10 installed in a VM so that I can test it out there.  If you want to try beating me to it, grab the code from GitHub master branch, compile and run it.

**Comment by mochiballs** [comment]
I have the same issue with running Linux Mint 19.3 Tricia. 

Something to note though is that when I delete the folder com.github.phase1geo.minder in ~/.var/apps, and then start the application, it starts up fine. However, after starting the application, even if I don't do anything and simply close out the Minder application and restart it, Minder crashes just like it did before.

**Comment by mochiballs** [comment]
Linux Mint 19.3 Tricia, Cinnamon Desktop
Minder version 1.12.2, Flatpak install

Also, I just noticed that after the application starts up after deleting the ~/.var/app/com.github.phase1geo.minder folder, if I try to open an existing .minder file, the application crashes again. I realize this comment is a duplicate of my comment https://github.com/phase1geo/Minder/issues/349#issuecomment-826434080 , however, I've added the mention to this bug report in case the context is relevant.

**Comment by jgraves1q2w** [comment]
Thank you I was able to install it via .deb and its running great.  I love the program and so far the best mindmapping program that I have ever used on any platform. Again thank you for the response.
________________________________

**Comment by mochiballs** [comment]
Linux Mint 19.3 Tricia, Cinnamon Desktop
Minder version 1.12.2, Flatpak install

@jgraves1q2w That's great! Where can I get the .deb package? I'd love to try a .deb install

**Comment by kden416** [comment]
Minder crashes, when i change theme from default to any other.

With dark theme i get in term: 

> free(): invalid pointer

With Solarized dark theme i get in term:

>  double free or corruption (out)

I have 1.12.2 version from flathub

**Comment by almereyda** [comment]
Please also see #357 and #359 where similar regressions are described.

The comment https://github.com/phase1geo/Minder/issues/357#issuecomment-841128437 describes a way to downgrade the Minder flatpak to the working `1.12.1` version for the time being until this is fixed.
