### ISSUE TITLE
[Feature Request] Style > Branch Options > Radius/Rounded corners

### ISSUE THREAD

**Issue by mochiballs** [phase1geo/Minder#354]
It would be really wonderful if there were an option for a branch style with rounded corners, perhaps with radius adjustment :)

<img width="765" alt="minder-rounded-corner-branch-option" src="https://user-images.githubusercontent.com/71861263/116019625-a0a93d00-a612-11eb-8dee-a884024a8e3a.png">

**Comment by phase1geo** [comment]
I'm going to add this feature into the 1.12.3 release.  It is not a big ask and doesn't lend itself to breaking existing functionality.

**Comment by mochiballs** [comment]
Thanks Trevor, you're awesome! Cheers! :)

**Comment by phase1geo** [comment]
I have updated the master branch with support for this feature.
