### ISSUE TITLE
Backspace in node name removes a byte instead of a character

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [phase1geo/Minder#36]
Because of the UTF-8 encoding, characters are encoded in uneven number of bytes (1 for ASCII, 2 for commonly used, and 3 for uncommonly used). When pressing backspace during editing of the node, only one byte is removed, instead of the whole character. This means that multiple backspace presses are required to delete a single character, and if the number of presses is less than the size of the character, the node name becomes unresponsive (probably due to the corruption of the byte code). Analogous thing happens with the Delete key.

Example of a two-byte character: ž
Example of a three-byte character: 他

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch which will be available in the next release.
