### ISSUE TITLE
Crash on second startup

### ISSUE THREAD

**Issue by 04ELY** [phase1geo/Minder#363]
I installed Minder as Flatpak from Flathub. It worked on first startup but I see it can't save to Documents even tough it has xdg-documents access by default.
Closed it to give home folder permissons
And never launched again.
Deleting  ~/.var/app/com.github.phase1geo.minder/ works until it launched again.

**Comment by mbnoimi** [comment]
+1
I've a similar bug under Linux Mint 20.1 xfce

**Comment by mbnoimi** [comment]
@phase1geo you set a `duplicte` label without mention which issue is related to!
BTW, This bug occurs since months ago which forced me to use xmind (the old open source version) as a temporary solution until fixing this bug.

**Comment by 04ELY** [comment]
It is solved in 1.12.3 with 0b937bb
Looks like he meant the issue #357
Closing this, thanks!
