### ISSUE TITLE
Edit title makes a long line over the page and it doesnt show the title and sometimes crash the app

### ISSUE THREAD

**Issue by Radical4ever** [phase1geo/Minder#367]
i have this issue when i edit the map and i want to add a title on the conection it makes a long line that doesnt show me what i write and in some cases when i press a key it closes the program.

**Comment by phase1geo** [comment]
Could you add a screencast of the long line issue and add it to this issue?

**Comment by Radical4ever** [comment]
![Captura de pantalla de 2021-05-31 11-09-49](https://user-images.githubusercontent.com/83252104/120217556-e4452700-c20e-11eb-87b4-816bbb5ad260.png)

**Comment by Radical4ever** [comment]
i leave a video if you need more details of the issue

https://user-images.githubusercontent.com/83252104/120242391-24ba9a00-c23b-11eb-86ff-04ec72b59f9b.mp4

**Comment by phase1geo** [comment]
Could you e-mail me a copy of the .minder file that exhibits this drawing problem?  The "line" that you are seeing is the connection title background.  It should have an initial width of the connection padding * 2.  For some reason, this title width is initializing to some huge value.  I'm hoping that the associated .minder file might provide me a clue as to what is going on.

**Comment by Radical4ever** [comment]
done, i send you the file 👍️

**Comment by Radical4ever** [comment]
if you click on these long lines you will be able to see the text typed in the title but when you edit these lines you cant see what are you typing until you stop editing it.

**Comment by Radical4ever** [comment]
ok i think this is a bug from the 1.12.2 bc i installed minder from the appcenter and later on i installed it with flatpak (which is 1.12.4) that has the bug solved, soo update from flatpak;the app is the best one and is more up to date.

**Comment by Radical4ever** [comment]
just a last question, how do i change the language of flatpak minder?
