### ISSUE TITLE
Bug: Adding an image to a node can cause the window to stretch beyond the screen

### ISSUE THREAD

**Issue by ChristopherNugent** [phase1geo/Minder#37]
Adding an image to a node can cause the window to stretch beyond the screen. 

![image](https://user-images.githubusercontent.com/21992673/46308043-73d13e00-c56d-11e8-80c8-5b3106000ab6.png)

![image](https://user-images.githubusercontent.com/21992673/46308090-995e4780-c56d-11e8-80f1-e05a0c8ba648.png)

Maybe make the sidebar scrollable?

**Comment by phase1geo** [comment]
I should have this issue fixed in the master branch and will be generally available in the next Minder release to AppCenter. I changed the minimum height of the text widget from 300 pixels to 100 pixels.
