### ISSUE TITLE
Crash when deleting text

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#371]
1. Set text cursor in the middle of a long node text
2. Press down the Del key and keep it pressed to continuously delete characters
3. When there are no more characters to delete and the Del key is still pressed — BOOM, segfault

100% reproducible on up-to-date git master build.

**Comment by phase1geo** [comment]
Is the text that you are using Russian text?  I can't reproduce the problem with English text, but I'm wondering if using non-English text characters cause the problem.

**Comment by prokoudine** [comment]
Spot on! It really only happens with non-latin scripts. I've just tried Cyrillic and Arabic texts, and Minder crashes in both cases.

**Comment by phase1geo** [comment]
I have replicated and fixed the issue in the master branch. This fix will be generally available in the next 1.12.5 stable release.

**Comment by prokoudine** [comment]
Thanks a lot! Also, please see my email from June 4 :)
