### ISSUE TITLE
Task toggle doesn't work on multiple selected items

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#373]
If you select multiple sibling nodes and press T, nothing happens. Only a single node can be task-toggled. Meanwhile, F works very well for folding/unfolding multiple sibling nodes. So I have high hopes that this is merely an oversight and not a feature :)

**Comment by phase1geo** [comment]
Not a feature, but rather a lack of one :)  when multiple nodes are selected, right clicking with bring up the contextual menu for supported operations that you can perform on those nodes. Task toggling is currently not one of the supported features.

I'll add it to the list...

**Comment by phase1geo** [comment]
I have checked in support for this feature in the master branch.  Currently, I am planning on the feature being available in the 2.0 stable release.

**Comment by prokoudine** [comment]
Kudos, thanks!
