### ISSUE TITLE
Chinese input method not working on connections

### ISSUE THREAD

**Issue by rongcuid** [phase1geo/Minder#389]
I see an old issue for node: https://github.com/phase1geo/Minder/issues/125

However, nodes are working. The Connection (X) label does not accept IBus input, however. When a Chinese IM is selected, eg PinYin, typing _should_ open the IBus candidate list, but instead the characters directly appear in the label.

I am using versino 1.9.2, as supplied by Pop OS 21.04.

**Comment by phase1geo** [comment]
The latest version of Minder is 1.12.5.  Is there any way that you could try building Minder from source and re-testing to see if the issue persists?

**Comment by rongcuid** [comment]
Hi, I installed the latest in FlatPak, and in the latest version it does work. However, in both the older version and the latest, the candidate window is not where the cursor is. This is a minor inconvenience.

On another note, it would be great if a hotfix can be backported so those using Ubuntu repositories can benefit from the fix.

**Comment by phase1geo** [comment]
I don't control distributions, so this is something I cannot fix.

**Comment by phase1geo** [comment]
I will consider this issue closed.
