### ISSUE TITLE
All hotkeys don't work in Cyrillic keyboard layouts

### ISSUE THREAD

**Issue by elzenar** [phase1geo/Minder#390]
I use Ukrainian and Russian keyboard layouts. And all keyboard hotkeys (Ctrl-C, Ctrl-V, E, etc) don't work in Minder.

I use Minder in Ubuntu 18.04.5 as flatpack package
```
$ flatpak list |grep Minder
Minder	com.github.phase1geo.minder	1.12.5	stable	system
```

#### Preparations
1. Add Russian or Ukrainian keyboard layout
2. Open Minder. Create a new document

#### Steps to reproduce
1. Fill text 'test' to the root node.
2. Press 'Ctrl-c'
3. Press 'Ctrl-v'. A new child node should be shown
4. Click to the root node
5. Change keyboard layout to Ukrainian/Russian 
6. Press 'Ctrl-v'

**Expected result:** the second child node should be shown 
```
    'test' -> 'test'
    'test' -> 'test'
```

**Actual result:** nothing is happened.

The same is actual for the other keyboard hotkeys

**Comment by prokoudine** [comment]
Yeah, I can confirm that on a regular git master build, no flatpak :)

**Comment by gavr123456789** [comment]
https://discourse.gnome.org/t/the-values-of-key-identifiers-in-gdk-depend-on-the-language-layout/7225

**Comment by phase1geo** [comment]
I don't currently know of a way to know the hardware key pressed for a given letter as different keyboards may have different hardware assignments for keys.

**Comment by phase1geo** [comment]
I believe that I have fixed this issue in the master branch.  If you could try running the branch and let me know if there are any issues, I would appreciate that.

**Comment by elzenar** [comment]
Thank you for the fix.

I tried to run the application but I have got another issue because I still use Ubuntu 18.04 :)
Ubuntu 18.04 does not contain 'gtksourceview-4' library. Only 'libgtksourceview-3.0-1' presents.

    meson.build:69:0: ERROR: Native dependency 'gtksourceview-4' not found
        
So I will run the application on Ubuntu 20.04 somehow and will write after about results.

**Comment by elzenar** [comment]
> I believe that I have fixed this issue in the master branch. If you could try running the branch and let me know if there are any issues, I would appreciate that.

It works.

I have created 'minder.flatpak' bundle file (on Ubuntu 20.04) and then I have installed it on my Ubuntu 18.04 and it works! :) 

I didn't find any issues.

**Comment by phase1geo** [comment]
Excellent to hear.
