### ISSUE TITLE
Resizing images on a centered node leads to the node obscuring the children on the right

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#392]
Hi! Just a drive-by bug report to show this, in case you hadn't already fixed it somewhere:

https://user-images.githubusercontent.com/479401/126532177-e4b067e2-a932-4067-82ed-a6b8b05b7247.mp4

Observed with 1.12.3 (haven't tested a newer version if any)

**Comment by phase1geo** [comment]
This issue has been fixed in the master branch and will be generally available in the 1.12.6 stable release.
