### ISSUE TITLE
Add your stripe key to appdata

### ISSUE THREAD

**Issue by danrabbit** [phase1geo/Minder#393]
In the new version of AppCenter Dashboard, we're no longer modifying your appdata before publishing, so you'll need to add your stripe key to appdata.xml to continue to monetize your app in elementary OS 6

For your convenience, your public stripe key is:
`<value key="x-appcenter-stripe">pk_live_Uhb96elhovWNRGkq07m2FRO9008Ia8OtVa</value>`

**Comment by phase1geo** [comment]
Closing issue.
