### ISSUE TITLE
Connections change their positions after the saved document is reopened.

### ISSUE THREAD

**Issue by gavr123456789** [phase1geo/Minder#395]
Here the problem project file.    
[GridId.zip](https://github.com/phase1geo/Minder/files/6892120/GridId.zip)

  
Here how it was look before reopen:  
![image](https://user-images.githubusercontent.com/30507409/127304077-b04c8685-fa71-4a21-88ce-c0f46bd472d0.png)  
![image](https://user-images.githubusercontent.com/30507409/127304100-5e3616b2-9f98-4b9f-b675-6b2fd86d8563.png)
  
P.S. best mindmapping software! thanks for dev this, I like to use minder at work when designing.

**Comment by phase1geo** [comment]
I believe that I have identified and fixed the issue in the master branch.  After running with the fixed source, you should notice that your mindmap will still be drawn incorrectly; however, if you fix the incorrect connections, the issue should not crop up in the future.

**Comment by phase1geo** [comment]
If this issue has been fixed for you, could you close out the issue?

**Comment by gavr123456789** [comment]
Yea, looks like fixed, thatn you!
