### ISSUE TITLE
When editing a node, end button does not move cursor to the end

### ISSUE THREAD

**Issue by tronta** [phase1geo/Minder#396]
User is editing node name, user presses end button --> cursor is before last character

I was not able to install the necessary dependencies in order to compile and try it, but I suspect a missing +1 in this line:
https://github.com/phase1geo/Minder/blob/43aad64ac179eccb04f5ce9764f85ee0b01eee0d/src/CanvasText.vala#L552

**Comment by phase1geo** [comment]
The End key will move the cursor to the last position in the current line (Control-End moves the cursor to the end of the text).  As such, the suggested fix location was the wrong area to fix the code.

I have updated the master branch to fix this issue.
