### ISSUE TITLE
 Property sidebar gear icon missing on Arch Linux

### ISSUE THREAD

**Issue by renaldofreire** [phase1geo/Minder#399]
OS: Arch Linux x86_64

Minder version 1.12.4 has an error in the "Show property sidebar" icon.

Is this a local problem?

![image](https://user-images.githubusercontent.com/35435780/128664566-d409ba58-2ee4-4560-bbaf-7f348d358885.png)

**Comment by louwers** [comment]
I reported this bug on the Arch Linux bug tracker: https://bugs.archlinux.org/task/75920

**Comment by louwers** [comment]
There is a [elementary-icon-theme](https://archlinux.org/packages/community/any/elementary-icon-theme/) packge.  It installs the icons to:

```
usr/share/icons/elementary/actions/symbolic/pane-show-symbolic.svg
usr/share/icons/elementary/actions/symbolic/pane-hide-symbolic.svg
```

How can we make sure that Minder picks these up?

**Comment by louwers** [comment]
I can see that the icon has been replaced in `master`.

So I guess this can be closed.
