### ISSUE TITLE
i can't get accents like "á" or "ã" in Brazil portuguese language

### ISSUE THREAD

**Issue by andrefcorreia** [phase1geo/Minder#40]

**Comment by phase1geo** [comment]
Are you inputting text using a compose key? Or are you entering the character another way?

I am definitely missing support in the key handler for the mind map canvas. I’ll try to get this fixed as soon as possible. As a workaround until this is fixed, you should be able to add these characters using the node tab in the sidebar.

**Comment by andrefcorreia** [comment]
i am entering pressing the a key  "~" and "a" for example and i am only getiing "a" instead of "ã"

**Comment by phase1geo** [comment]
I have this feature implemented in the master branch and just submitted a new release to App Center.

**Comment by andrefcorreia** [comment]
ty, its working now :)
