### ISSUE TITLE
[Feature request] Save folded state of child

### ISSUE THREAD

**Issue by 04ELY** [phase1geo/Minder#401]
Currently, if we unfold the parent node, we also unfold the children. Is it possible to keep the child's state?

https://user-images.githubusercontent.com/60751519/129385582-239e3344-ad43-4d95-a46c-c1c6faa07d83.mp4

Maybe something like F to fold/unfold and Shift+F to Fold all/Unfold all ? Can be useful for big and detailed maps.

**Comment by phase1geo** [comment]
Sounds doable!

**Comment by 04ELY** [comment]
Yes I noticed, it was c339dd4 if I am correct, though I couldn't know which release will include this Thanks! 
Will test master!

**Comment by 04ELY** [comment]
The GUI works, yey!

https://user-images.githubusercontent.com/60751519/139744033-5ae8ffc3-e9f5-4a4a-9ee9-07b230e0f587.mp4

But Shortcuts does not 
- F jumps back to parent node. (Like pressing A)
- Shift + F does nothing.

**Comment by 04ELY** [comment]
Noticed "F jumps to parent" also occurs on latest stable 13.1 
Strange thing is, 
I tested it with en-us and tr-q (both are standard "qwerty") and bug happens
-- tested with an alternative layout: tr-f (which starts as "fgğıod") and bug doesn't happen. 
-- bug doesn't happen on en-dvorak either

Should I open a separate bug report for this?
- Open latest stable minder
- try to fold a node with F shortcut on standard/qwert layout 

https://user-images.githubusercontent.com/60751519/139747296-206040f6-b2e1-41c4-b96d-2a4bdc210375.mp4

--
While on master: Shift + F on alternative layouts still doesn't work.

**Comment by phase1geo** [comment]
The keyboard shortcuts issue is related to something completely different, so I’ve created a new issue for that.
