### ISSUE TITLE
Use Inter as Default Font

### ISSUE THREAD

**Issue by candiedoperation** [phase1geo/Minder#402]
@phase1geo, Using **Inter as the Default Font** as Elementary OS Odin Uses, Makes the whole chart look awesome.'

![image](https://user-images.githubusercontent.com/47198395/129835492-765aa9cf-4d9f-435c-80e1-5046177bc306.png)

In the above image, the words **Stoichiometric** and **Non Stoichiometric** are in `Sans 11` but, the rest are in `Inter 11` font

**Comment by phase1geo** [comment]
I'm going to WontFix this request.  If you want to make all nodes and connections use the Inter font, make sure that nothing is selected, go to the Styles tab and change the node and connection font to Inter (at whatever size you would like).  All nodes and connections will change to that font size immediately and any new nodes and connections within the mind map will be given that font type as well.

At some point, I will probably make a preference pane to allow the user to customize default style options that will work for all  new mind maps made within the application.  Font types/sizes will be included in those defaults.  But that feature will be tracked separately from this issue.
