### ISSUE TITLE
Color choice for root nodes

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#407]
For some reason, it seems impossible to set a color to a root node. It would be nice to have this limitation removed.

**Comment by phase1geo** [comment]
Root node colors can be changed within the theme colors.

**Comment by phase1geo** [comment]
Technically, you can change node colors either.  You only change the link colors to the child node.  Nodes inherit the same color as their links.

**Comment by prokoudine** [comment]
> Root node colors can be changed within the theme colors.

That's where it gets hairy. What if I need different colors for different root nodes, the reason being color coding?

**Comment by neoscopio** [comment]
+1 need it too.

**Comment by phase1geo** [comment]
Support for this feature has been added to the master branch.
