### ISSUE TITLE
Improved release planning

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#408]
I'd like to propose a slightly different approach to release planning where you would update AppData, then wait a few days for translators to pick it up, and then cut the release. That way, for actively maintained translations, the translatable list of changes would stay up to date. And it would give translators (overall) the incentive to review UI translation as well.

Ideally, there would be some communication channel where you could say "Folks, I'm about to release an update, please bring your translations up to speed, you have X days". But even giving us a bit of a head start without notification would be a win :)

**Comment by phase1geo** [comment]
Excellent suggestion.

In fact, I am doing just that with two of my other projects, TextShine and Annotator. I will plan on continuing to do that for Minder and Outliner.

Do you have a suggestion for how to best indicate to everyone that translations should be updated?

**Comment by prokoudine** [comment]
> Do you have a suggestion for how to best indicate to everyone that translations should be updated?

The only GitHub-native solution I can think of right now would be creating a dedicated thread in the Discussions section and asking all translators to subscribe to updates in it.

**Comment by phase1geo** [comment]
I have added a new GitHub discussion board for release updates and calls for translations for all of my projects and have added some release info for TextShine and Annotator.
