### ISSUE TITLE
Pick better images in screenshots

### ISSUE THREAD

**Issue by peteruithoven** [phase1geo/Minder#41]
The clip art you've used in the mindmap in your screenshot is seriously bringing down your app. It deserves better.

**Comment by phase1geo** [comment]
Do you have any suggestions? I didn’t spend a lot of time picking images for the screenshots — I mostly just wanted to show that it was possible to add images. In the next big release, I will need to update the screenshots to demonstrate some new features so it would be the perfect time to do something better.

**Comment by peteruithoven** [comment]
Some ideas: 
Create a mindmap on the Juno release. Then you could add screenshots of PIP, Fund button in AppCenter, the new style switcher, night light etc. 
You can probably use the images from: https://medium.com/elementaryos/elementary-os-5-juno-is-here-471dfdedc7b3 if you credit Cassidy. 

Or a mindmap on a recipe, add nice pictures of ingredients, preferably with matching background color. 

A mindmap on a type of animal, with animal pictures, related races. 

Or maybe something with icons from https://thenounproject.com ?

**Comment by nateswart** [comment]
Made a few examples in case that helps generate ideas (based on the suggestions above)

![screenshot from 2018-11-04 17 09 20](https://user-images.githubusercontent.com/839888/47970843-a7195800-e058-11e8-9d33-e4a5f79e00ff.png)

![screenshot from 2018-11-04 17 37 20](https://user-images.githubusercontent.com/839888/47970848-ac76a280-e058-11e8-9032-72defa3dfff4.png)

**Comment by phase1geo** [comment]
Do you happen to have the .minder files for these examples? If so, could they be attached to this issue?

**Comment by phase1geo** [comment]
I have went ahead and updated the screenshots to show a brief mindmap for Minder development. Hopefully, the images used are less hokey and make more sense :)
