### ISSUE TITLE
Bug working with cloud share :: Check for changes before autosave

### ISSUE THREAD

**Issue by neoscopio** [phase1geo/Minder#412]
Maybe more like an annoying feature,  if you sync files using a cloud service (e.g. dropbox, owncloud) the autosave feature is always syncing every change, but if you have the same file opened in another computer, (like office-home), when you get to the other location, and the older version is still opened (because you e.g. activated sleep in the computer),  a newer version is already on disk, so autosave will erase all the changes.
I guess the guidelines require autosave, but this can be avoided by checking if the file on disk has changed outside minder before saving.
Keeping the state in a different way, not changing the file before the explicit save action, would be better, in my opinion.

**Comment by phase1geo** [comment]
Minder is currently designed to work well in "mutli-user" paradigms such as the one that you describe above.  I am making some significant changes in an upcoming release (2.0) that changes the way that Minder saves data along with a change to the .minder file format.  I will try to make sure that usage scenarios (such as this one) will work with the new paradigm.

**Comment by phase1geo** [comment]
Until then, you will need to make sure that you one and only one instance of Minder with an opened file.
