### ISSUE TITLE
Minder for Windows?

### ISSUE THREAD

**Issue by Netherquark** [phase1geo/Minder#419]
Hi. I'm using Manjaro, and I found the application to be great for mindmapping. However, my friend, who only uses Windows, can't use Minder at the moment, because it is Linux only. Do you think it would be possible for you folks to create a Windows build as well? Will it possibly work via WSL?

**Comment by wtechgo** [comment]
@Netherquark I was wondering about that too.
You can try exporting your mind maps, many formats seem to be supported, and have your friend import, and vice versa.
Have you tried that and if so, can you tell us if that was a workable solution.
I agree that workflow is more inconvenient than it could be but I'm curious if it is an option.

**Comment by Netherquark** [comment]
unfortunately I switched to draw.io a while back. sorry!
