### ISSUE TITLE
how can i separate the text with "enter"?

### ISSUE THREAD

**Issue by andrefcorreia** [phase1geo/Minder#42]
i cant use "enter"?
example:

"here is my text - where is the 
'enter' space?"

in this

"here is my text 
           - 
where is the 
'enter' space?"

i try "enter" key, Alt+Enter, Ctrl+Enter and AltGr+Enter
is there a way?

**Comment by phase1geo** [comment]
There is currently no support for the Enter/Return key when editing a node within the mind map canvas. I will work on that.

For longer form text, nodes have the concept of a “notes” field that is accessible within the Node sidebar area. That is a a free-form text field that will allow you to have vertical white space.

**Comment by andrefcorreia** [comment]
thank you

**Comment by megatux** [comment]
Related to this,  the "edit textbox" control does not support the usual moving between words with Ctrl-[left/right], Home/End keys, selections, etc. Looks like a _custom_ widget without all the expected text-edit functionality.

**Comment by phase1geo** [comment]
Yes, create a new issue for this. Thanks!

**Comment by phase1geo** [comment]
I have added support for adding newlines and tabs to the node's title and have checked it into the current development branch. This feature will be generally available in the next Minder release (1.2).

**Comment by andrefcorreia** [comment]
Thank you

**Comment by megatux** [comment]
Generally, I'd leave issues _open_ until the change is released.
