### ISSUE TITLE
Note text is unreadable (regression?)

### ISSUE THREAD

**Issue by savchenko** [phase1geo/Minder#420]
Issue is present in 1.13.1, but not in 1.9.2, Debian package:
![image](https://user-images.githubusercontent.com/300146/138197788-e6b3280e-20d8-4911-aa9f-f87a282064d0.png)

**Comment by phase1geo** [comment]
I will take a look.

**Comment by phase1geo** [comment]
The connection's title and note are distinct entities. When a note is attached to a connection, it will display the note icon (as seen in your image). You can view/edit the note in the sidebar or just view it by hovering the mouse pointer over the icon. To create a title for the connection, double click the connection or, while the connection is selected, right click to display the contextual menu and select the "Edit Title..." option. Title's are both edited and viewed directly in the map canvas, just like node titles.
