### ISSUE TITLE
When changing the Node Layouts, my nodes shoot off about 10 lightyears away from each other

### ISSUE THREAD

**Issue by tmanok** [phase1geo/Minder#428]
Unfortunately while using the application for the first time, I had built a significant mind map and then decided to check out the styling and map options. When I clicked on a different Node Layout, my nodes separated in north-south directions. I tried a different layout to see if this would fix the issue, it made it worse, and then I reverted which made it worse. Then I pressed CTRL+Z a few times and things got so bad that I have tried dragging the map to find my nodes for about 10 minutes without success (they had "connections in dotted lines and I followed those but never reached the end). 

My "solution" will be to search for each node and build the map again, but the problem is that in the next map, to avoid this issue, I will have to make everything a child node instead of having multiple root nodes if I want to avoid disaster and this greatly limits what I can do. 

Lastly, I attempted to restore from my saved file, but it did not solve the problem despite having not saved since changing Node Layouts. If anyone has a better solution to re-centering everything, please let me know, in the meantime this bug exists on Ubuntu Focal, installed via APT, it is possible that the problem no longer exists in a future release. 

Tmanok

**Comment by phase1geo** [comment]
Layouts only have implications on nodes in a tree. In fact, each tree can have a different layout within the same map. Layouts do not have an impact on the relationships between root nodes.  Though it is possible that root nodes will be repositioned when the layout changes.

Map changes are auto-saved, so reopening a mind map will not have the effect of "fixing" the map.

**Comment by phase1geo** [comment]
What version do you have installed?

**Comment by tmanok** [comment]
Good morning,

I have 1.5.1-1 installed according to apt. 

"Map changes are auto-saved, so reopening a mind map will not have the effect of "fixing" the map." It's nice to have autosave, but unfortunate that I had to rebuild the mindmap. I'll try it again on another OS today to see if this bug is repeatable. Additionally, I will try to make another mindmap with the same characteristics and take a screenshot for you.
Cheers,


Tmanok

**Comment by tmanok** [comment]
I've made a slight discovery. The fewer root nodes you have with connections from the original, the less distance you will gain between them when you click on a node layout selection. This also applies if you click on the node layout that you're already using (interesting). However, the changes can be reverted early on (the nodes can contract together if you haven't separated them too much) if you spam the "To the right" or "upwards" node layouts. Strange. Also if I leave it alone for a bit after spreading them apart and then attempt to change the layouts again, they do not gain distance, turns out this is very time dependent. 

I don't understand how my findings work, but that's the observed data folks. Also, I have witnessed that this does not happen if there are no children attached to any of the root nodes.  I'm going to try reinstalling to see if that fixes the problem, but I don't expect that it will because this started on a fresh installation that I had only just begun using.

**Comment by phase1geo** [comment]
The lastest version available is 1.13.1 (Flatpak). Your version is pretty old.

**Comment by tmanok** [comment]
As is the case with many apt packages, despite running a 2020 OS with updates from this year. I'll try out the latest version, I have a pretty good feeling that the issue will no longer exist, in the meantime, it might be worth alerting Yanfl (mmyangfl@gmail.com) who is the Ubuntu maintainer, not sure if he is the Debian Maintainer as well. If you have a manpage, they could probably add that too. Cheers,

Tmanok

**Comment by phase1geo** [comment]
If you are still using Minder would you try out the latest version 1.15.3 on this issue?  Though I did not specifically address this problem in that release, other changes that I made to fix other (potentially related) issues may have taken care of this.  Just curious to know if the problem continues to persist.
