### ISSUE TITLE
Garbled layout

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#432]
I sometimes get this kind of rendering, usually in a busy mindmap with ~100 nodes:

![image](https://user-images.githubusercontent.com/57467/143214238-b2085621-4a36-41dc-af64-d948a54ea437.png)

I can locally fix it by dragging the Margins slider around. Even increasing/decreasing Margins value back and forth will fix it.

In this particular case, all other root nodes with their child nodes appear to be gone, and using "Zoom to fit" makes this group invisible maybe because it scrolls elsewhere (a minimap would probably help)

**Comment by phase1geo** [comment]
What caused the tree layout to get messed up?

**Comment by prokoudine** [comment]
> What caused the tree layout to get messed up?

I think I saw this two or three times after using the quick entry feature.

**Comment by phase1geo** [comment]
Are you still seeing this as an issue with the 1.15.3 release?
