### ISSUE TITLE
Export adds black background to black text

### ISSUE THREAD

**Issue by franekma** [phase1geo/Minder#44]
Just feedback:

On a live USB elementary OS, installed Minder to test it, had this issue:

Export to opaque background in .png, .jpeg and .bmp, the image had a black background for the black text. Restarted application and exported, this time got two strange black margins to the top and right.

Apologies, the screenshot is messy.

EDIT: Further testing confirms the black background happens when you reposition the notes within the main window. Dragging the notes back to the top-left corner results in the black margins. Keep repositioning and you can get the normal white background.

I'm new here, apologies if this is a non-issue and I'm just wasting time.
Regards!

![screenshot from 2018-11-02 08-44-40](https://user-images.githubusercontent.com/44696578/47903721-f6eef800-de7b-11e8-96e8-06ef43c0683a.png)

**Comment by phase1geo** [comment]
I'm finally looking into this issue now.

**Comment by phase1geo** [comment]
I believe that I have this issue fixed in the master git branch. It will be generally available in the next release.
