### ISSUE TITLE
CTRL Backspace does nothing

### ISSUE THREAD

**Issue by FineFindus** [phase1geo/Minder#440]
Hi, I recently found this amazing application (thanks for creating it) and noticed that when you press **Ctrl backspace** it does nothing.
Usually this shortcut deletes the word before the cursor.

**Steps to reproduce**
1. Create a node with text
2. Try to delete the text with Ctrl backspace, this should delete the word before the cursor, but nothing happens

I am using 1.13.1 as a flatpak.

**Comment by phase1geo** [comment]
I have added support for Control-Backspace (delete the previous word) and Control-Delete (delete the next word) when editing node or connection text in the mindmap.  This feature has been committed to the master branch.
