### ISSUE TITLE
Ability to set connections to have bidirectional arrows

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#442]
Currently you can "connect" two nodes to have an arrow pointing from one to the other, which is great, however there are many cases where you want to illustrate a reciprocal relationship (ex: a bidirectional sync, or collaboration, or something) and you would need to have arrows on both ends.

The only workaround I found was to select the nodes again in the reverse order and "connect" a second time, but that's kind of abusing the feature, and it also tends to look imperfect as it either creates a big spaghetti of lines (twice the amount of everything) or it creates hard-to-align overlapping lines.

**Comment by phase1geo** [comment]
After creating the first connection, make sure the connection is selected, go to the style inspector panel and select the connection arrow drop down. You can change the style of the arrow to be bidirectional from there.

**Comment by nekohayo** [comment]
Oh, my bad, I somehow had this reflex of looking for an "Edit connection" action in the right-click menu, I totally didn't think to look for the sidebar for this property. So I guess that is good enough (hence closing this ticket), unless one wants to make it more obvious-in-your-face in the contextual menus.
