### ISSUE TITLE
UX enhancement on adding web links to nodes

### ISSUE THREAD

**Issue by daveiro** [phase1geo/Minder#447]
I add web links to nodes in mind maps with a high frequency and, currently, the steps needed for this are a bit cumbersome in terms of UX, namely: press e key to edit node; right click or menu key; select and press Add link option; CTRL+V to paste link; press Enter once to add link; press Enter again to finish editing node; that is around 7 key pressings.

Suggestion of enhancement is: use the same shortcut as used in many apps to add links: CTRL+K to add link to selected node which opens the link box and, if there is a web link in the clipboard it immediately "pastes it" to the link box (I could live with the need to use CTRL+V to paste, but many apps are using this "automatic paste" which is really handy); then, pressing Enter, immediately, the link is added to the node.

Thanks!

**Comment by phase1geo** [comment]
Web links can be added in a quick way by heading into preferences and making sure the that "Automatically make embedded URLs into links" option is selected.  After that, edit the node text and just paste the link in.

**Comment by daveiro** [comment]
yes it's common that I create new nodes in maps just pasting links and that feature of making embedded URLs into links automatically is useful, but the use case I am referring to is different and it was not clear in my initial post: my issue is on adding links to already existing nodes with already existing text, while keeping the text the node has already; while composing e-mails or editing text in most word processors, it's common to use CTRL+K to quickly add a link to selected text and the idea is to make it easier/quicker to add links to already existing nodes in minder

**Comment by phase1geo** [comment]
I see the difference now.  I will do two things in regards to this request:

1. Implement Control-K when editing text and with text selected, display the link creation UI when the keyboard shortcut is used.
2. Whenever the link creation UI is displayed (whether with the shortcut or with the "Add Link" menu option, check to see if the clipboard contains a URL and, if so, automatically add it to the entry field.

I believe that should handle your request and it also makes the current method of adding a link a bit smarter than it currently is.

Is Shift-Control-K used to remove links from selected text?  If so, I could add that functionality as well.

**Comment by daveiro** [comment]
That is wonderful! Thanks!

If I may add/clarify a third thing (which I implied in my original request and makes it even snappier): while having a certain node selected, Control-K will immediately display the link creation UI (no need to press "e" to edit the node) and the whole text of the node will become a link; then when pressing Enter/Apply, the node is "closed" immediately (currently one needs to press Enter twice in this case scenario).

The most usual case scenario (probably 99% of the time) is that one wants that the whole text of the node is part of the link so no need to "lose time" editing the node and selecting text.

Microsoft Word has a shortcut to remove links from which is not Shift-Control-K, but I like a lot the idea of shortcut to remove links also, as it is something I also do in my maps sometimes and it makes sense to use this key combination.

**Comment by phase1geo** [comment]
Okay, makes sense to me.

**Comment by phase1geo** [comment]
I have updated the master branch with support for this feature.  I'm sneaking this feature into 1.14.0 stable release (to be released this evening in GitHub).

**Comment by daveiro** [comment]
works perfectly and exactly as imagined/requested 😊 thank you so much for your excellent work with minder!! 👍🙏
