### ISSUE TITLE
Projects saving wrong/not showing in open dialog

### ISSUE THREAD

**Issue by ChildishGiant** [phase1geo/Minder#450]
my projects are getting saved as `.xdp-FILENAME.minder-RANDOMCHARS` and don't show up in the dialog to open existing projects

https://user-images.githubusercontent.com/13716824/150849201-4530f0ce-19ea-41fc-a08d-a564f3c76bb4.mp4

.

**Comment by phase1geo** [comment]
Out of curiosity, did you give Minder permissions to access your home directory via the Flatpak portal?

**Comment by ChildishGiant** [comment]
I just installed default from the AppCenter on elementary OS. Using flatseal to allow access to all system files fixed this. 
![image](https://user-images.githubusercontent.com/13716824/151617012-d72ec1cb-1435-44d0-8f99-5b539222a246.png)
IIRC there's a portal to fix this issue so you don't need to just save in the user dir

**Comment by phase1geo** [comment]
As of Minder 1.15.0, the home directory filesystem permissions are enabled by default.  This issue should no longer occur going forward.  Closing.
