### ISSUE TITLE
Feature: Add Image From Clipboard

### ISSUE THREAD

**Issue by AminM-here** [phase1geo/Minder#452]
I think if it become possible to add image from clipboard, it will give this software a super cool functionality.

Loading and choosing images from a dialog box is cumbersome and slow (you need to save an image in a folder then open a dialog box and find it in that folder) it is waste of time and lots of distractions.

By just pasting an image by pressing `ctrl+v` it creates a super fast connection to the web, image search engines, other diagramming tools or any software that has image output even you can use screenshots.

**Comment by phase1geo** [comment]
You can also drag and drop images onto an existing node in a mindmap

**Comment by nigo81** [comment]
> add image from clipboard, it will give this software a super cool functionality.
> 
> Loading and choosing images from a dialog box is cumbersome and slow (you need to save an image in a folder then open a dialog box and find it in that folder) it is waste of time and lots of distractions.

Thanks for your awesome software.
I often to use icons for mind map creation. After copying image from clipboard to a node of minder, I couldn't adjust image size as stickers.
![1](https://user-images.githubusercontent.com/38601513/152541428-dc3f1cc9-4fb7-4c29-97ce-58ab9b30052c.png)

`left`: the size of the sticker in minder, it's suitable with fonts.
`right`: the size  of image from clipboard if connection with fonts, when I scale small the size of image, the width of fonts go down. So  I can't adjust the size of image suitable for fonts.

Is there any method to solve my problem?

Thanks.

**Comment by phase1geo** [comment]
Image sizes follow node sizes (there is only a single resize handle on a node), so the short answer is that you can't have a small image on a large node (due to excessive text).

Possible workarounds would include the following:

- split the image node and text into two separate nodes.
- place node text into the note field of the node
- replace the image with either an existing sticker or use an emoji as the image.

With all of that said, I can look into providing support for images that do not follow the node size, but this will make the UX more cumbersome, I believe. There are several technical issues this could cause as well.

**Comment by nigo81** [comment]
> * place node text into the note field of the node

thanks for your reply.

**Comment by phase1geo** [comment]
Okay, here's where I'm at so far on an implementation for this feature.  I have all of the base coding support completed to support resizing a node without modifying the icon size checked into the master branch.

Currently, if you drag the node resize handle, the image will grow/shrink to match the width of the node.  However, if you hold down the Control key, the image size will remain fixed and centered in the node at its current size.  I think this code is working pretty well; however, I'm wondering if that UX strategy is acceptable or not.  It's simple and straightforward (as long as the user knows about the Control key behavior) and it doesn't require fiddling with settings, menus or the like.  But I'm not sure if it's the best way to deal with the issue.

If you would be willing, could you grab the latest master branch code and give it a try and give me your feedback?

**Comment by phase1geo** [comment]
I am going to consider this issue as fixed with the current implementation in the master branch.

**Comment by Xeriaz** [comment]
On what version does image from clipboard work?
Because I've used `sudo apt install minder` which is telling me that `minder is already the newest version (1.5.1-1).` but pasting image from clipboard does not work.

**Comment by phase1geo** [comment]
I don't control the packaging for your OS, so I can't comment on why it is so far behind. The latest in GitHub is 1.14.0; however, the master branch in GitHub pretty much contains what will be in 1.15.0.

**Comment by Xeriaz** [comment]
Interesting, because on Ubuntu software store it also display Version: `1.5.1-1`. Same as apk install. 
Well I guess I'll just install GitHub version. Thanks.
