### ISSUE TITLE
can't open old Mindmaps after system change from Manjaro to Ubuntu, cause the XML-Format seems to differ

### ISSUE THREAD

**Issue by JennyPre** [phase1geo/Minder#453]
Hello there
I got version from September 2021 installed on my Manjaro System. When I than try to open the files on my newly installed Ubuntu System, they just wont open. Is there a way to open them without fuzzing around with the file format? (I got it to open, by changing the XML file a bit, but the formatting was still wrong) And do the file formats differ depending on the system ? 
Thanks already for your help

**Comment by phase1geo** [comment]
Do you know what version of Minder was used on the old system? If it was pretty old, there may be issues with compatibility.

**Comment by JennyPre** [comment]
Not sure anymore, what version it was. But I kind of found the Problem. The .xml Format in Ubuntu and Manjaro differ. I installed Minder in a new Manjaro-VM and I can open the files there.

Thank you for writing me though 😄
________________________________
Von: Trevor Williams ***@***.***>
Gesendet: Freitag, 4. Februar 2022 15:40
An: phase1geo/Minder ***@***.***>
Cc: JennyPre ***@***.***>; Author ***@***.***>
Betreff: Re: [phase1geo/Minder] can't open old Mindmaps after system change from Manjaro to Ubuntu, cause the XML-Format seems to differ (Issue #453)


Do you know what version of Minder was used on the old system? If it was pretty old, there may be issues with compatibility.
