### ISSUE TITLE
Connections fold inconsistently

### ISSUE THREAD

**Issue by marcarneg** [phase1geo/Minder#458]
Example:
![image](https://user-images.githubusercontent.com/52791267/152985122-91ca37f9-463a-487a-bd3f-14dde71f51e6.png)

Fold Sub:
![image](https://user-images.githubusercontent.com/52791267/152985204-251ef708-211a-4503-bbe6-a02015849302.png)

Fold Root:
![image](https://user-images.githubusercontent.com/52791267/152985251-0191c3dc-e465-403d-a6d1-d0ba40c9a1e6.png)

Tested with 1.14.0 / freshly compiled masterbranch on 08.02.22 12:15UTC. Added minderfile as zip.
[mindr-bug.zip](https://github.com/phase1geo/Minder/files/8023722/mindr-bug.zip)
.

**Comment by phase1geo** [comment]
This issue has been fixed in the master branch.  It will be generally available in the upcoming 1.14.1 update.

**Comment by marcarneg** [comment]
Perfect! Thank you for this very quick fix! :)

**Comment by DVegGyver** [comment]
I don't Know if there are other issue open on this.
if I fold a Sub-Branch that have a connection.. the connection remain in the middle of map
![Schermata a 2022-10-09 16-08-43](https://user-images.githubusercontent.com/99847466/194761782-499f7095-6673-44df-90f2-f6e60e94937d.png)

**Comment by phase1geo** [comment]
The fix for this issue is in the GitHub master branch currently. It is not available in a packaged release at this time.

**Comment by DVegGyver** [comment]
Perfect, thank you.
