### ISSUE TITLE
Shortcut to open properties tab

### ISSUE THREAD

**Issue by alvelvis** [phase1geo/Minder#46]
This tab is important to be easily opened/closed in a single tap. I've been thinking about Ctrl |, the same shortcut to opening the sidebar in elementary's Code

**Comment by phase1geo** [comment]
I went ahead and used this shortcut (Control-|) to open/close the properties sidebar. Is there a particular tab within the panel that you would like to see when it opens? There are currently two tabs: Node and Map; however, there will be a third tab "Style" that will also be available when the next version of Minder is released. The current behavior is to simply open the sidebar with the shortcut which will display whichever tab was last displayed in the sidebar.

**Comment by alvelvis** [comment]
Great! I think it's the most adequate to open the last displayed tab. Thank you
