### ISSUE TITLE
Warning when opening file created with previous version "The file /run/user/.../X.minder was modified outside of the application"

### ISSUE THREAD

**Issue by aumouvantsillage** [phase1geo/Minder#461]
I have created a mind map with Minder 1.13, installed from Flathub and running in Ubuntu 21.10.
Now I am trying to reopen it with Minder 1.14, installed from Flathub and running in Fedora 35.

The document opens successfully, but when I try to make a modification, or even to scroll or zoom, I get a dialog with the following warning:

> The file /run/user/1000/doc/89769c48/my-map.minder was modified outside of the application.

* The first button "Discard changes and reload" restores the document in its previous state. Every action triggers the same dialog again.
* The second button "Save local version and overwrite" overwrites the .minder file and I can edit it normally afterwards. When closing and reopening the document, I don't get the warning dialog.

At first, I was reluctant to use the "Save local version and overwrite" option, and I took care to create a backup of my files before attempting to click that button.

**Comment by phase1geo** [comment]
I believe this feature is new to 1.14.0.  This was a pull request created by a user that wanted to avoid issues with editing a mind-map that was being edited in two places at the same time (ex. if the mind-map was edited on a desktop and kept open while editing on a laptop, Minder should detect this case and issue the message that you received).

In my evaluation of the pull request, it seemed that the implementation was fairly secure, but I don't think it does exactly the right thing when an older mind-map is edited by a version of Minder that is 1.14.0 or above -- as you have described.  I think the correct thing to do would be to detect that the mind-map precedes the feature and automatically save the mind-map as the new version to avoid the popup.

**Comment by phase1geo** [comment]
That being said, you have done the right thing to save locally.

**Comment by phase1geo** [comment]
This issue has now been fixed in the master branch.
