### ISSUE TITLE
segmentation fault (core dumped)  

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#463]
Hi,
When i open a file created with previous version 1.13, after upgrade to 1.14 the app crash, and gives a message in the terminal: "segmentation fault (core dumped) "

Tried building from source to latest version, same issue.

**Comment by phase1geo** [comment]
Which Linux distribution are you using?

**Comment by wada3n** [comment]
Manjaro Linux, last update

**Comment by phase1geo** [comment]
Can you find out what version of valac is being used to compile?

**Comment by wada3n** [comment]
Vala compiler for the host machine: valac (valac 0.54.7)

**Comment by yy57** [comment]
> Can you find out what version of valac is being used to compile?

same problem with me. Archlinux, vala 0.48.24,builded from source.

firtly, I installed minder with pacman, and used minder for a while, after I made some adjustment about the node style, minder crashed, restart it: "segmentation fault (core dumped)  ./com.github.phase1geo.minder".

rebuild it from source, same problem

**Comment by phase1geo** [comment]
I *think* that this issue should now be fixed in the master branch and will be generally available in the 1.15.6 release coming up soon.
