### ISSUE TITLE
No Italian language.

### ISSUE THREAD

**Issue by albanobattistella** [phase1geo/Minder#466]
Hi, I have a problem with Minder on Zorin Os (Ubuntu 20.04 based) installed via Flatpack does not appear the Italian language.
The software is in English only and it is not possible to choose other languages.
Could you please check it?
Thank you.
Regards.
Albano

**Comment by ChildishGiant** [comment]
There are the correct [localisation](https://github.com/phase1geo/Minder/blob/master/po/it.po) files and it should pickup on your system language, just confirming that is Italian?

**Comment by albanobattistella** [comment]
> There are the correct [localisation files](https://github.com/phase1geo/Minder/blob/master/po/it.po) and it should pickup on your system language, just confirming that is Italian?

I confirm that the system is in Italian, but the language remains in English.

**Comment by phase1geo** [comment]
I have been trying to research this issue and have tested my application Flatpaks as well as Flatpaks from other applications.  I'm seeing the same problem with other Flatpaks that I have tried.  I've been trying suggestions found by searching the problem, but nothing seems to change the behavior.  I'm not seeing anything missing from a code perspective that is keeping the translation from working.

**Comment by phase1geo** [comment]
Can you find a Flatpak that works properly when the translation is changed?

**Comment by albanobattistella** [comment]
> Can you find a Flatpak that works properly when the translation is changed?

Hi, I tried too ... all packages, but nothing ... it seems that the language doesn't change.
How she couldn't hear the language of the system.
We need to solve the problem for the users.

**Comment by DVegGyver** [comment]
I read this conversation and I notice that in my Minder there is no option to change the Language. Mine is installed on Ubuntu 20.04 (no flatpak).

**Comment by albanobattistella** [comment]
> I read this conversation and I notice that in my Minder there is no option to change the Language. Mine is installed on Ubuntu 20.04 (no flatpak).

Hi,
yes, the same problem also for me.

**Comment by DVegGyver** [comment]
UPDATE: Installing the 1.13.1 version of minder in the Ubuntu Mate Package i have the App in Italian.

**Comment by albanobattistella** [comment]
>

**Comment by albanobattistella** [comment]
> UPDATE: Installing the 1.13.1 version of minder in the Ubuntu Mate Package i have the App in Italian.

In the gnome software I have 1.14 version but Minder is not in Italian.

**Comment by phase1geo** [comment]
Does anyone understand why translations aren't working with Flatpak? I added a Help tag to this issue quite a while ago because I don't understand how translations and Flatpak work together (and there is surprisingly little information about it online as if it should "just work"). Trying out other Flatpak and changing the system translation had no impact on those apps either, so I don't think this is a problem isolated to Minder.

**Comment by albanobattistella** [comment]
> Does anyone understand why translations aren't working with Flatpak? I added a Help tag to this issue quite a while ago because I don't understand how translations and Flatpak work together (and there is surprisingly little information about it online as if it should "just work"). Trying out other Flatpak and changing the system translation had no impact on those apps either, so I don't think this is a problem isolated to Minder.

Hi,

Italian language is not available.
Any suggestions?
thanks!
Albano

**Comment by phase1geo** [comment]
I believe I have figured out how to fix this issue.  I will be creating a 1.15.1 version of Minder this evening which should address the issue.  The master branch has been updated with the fix already if you would like to pull this change, build the flatpak (run './app flatpak' in the main Minder repository directory), and test it out.

**Comment by albanobattistella** [comment]
> 

Hi,

now, Italian translation, after the last update, is available.
Thanks.
R,
Albano

**Comment by phase1geo** [comment]
Minder 1.15.1 should now be available in elementary AppCenter.
