### ISSUE TITLE
`E` keyboard shortcut key to edit a node's title doesn't work in Minder 1.14.0

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#467]
At least while running GNOME under Xorg/X11, I can't seem to have the "Change Node > Edit Text..." action work when I have selected a node, whether it is called from the clickable menu or from the `E` keyboard shortcut. Calling that action does nothing more than open the sidebar, if it isn't shown already. The only way I am able to edit the text of the node's title is by double-clicking the node, then clicking at the end of it to deselect the text and append some more text.

This is using Minder 1.14.0 from the Fedora repositories. I don't recall if this was a problem in versions from a few months ago...

**Comment by phase1geo** [comment]
The menu does look like it's wrong. I'll fix that. The 'e' command should put you into editing mode for the node title. Shift-e will allow you to edit the node note.

**Comment by phase1geo** [comment]
This issue has been fixed in the master branch.  The contextual menu's "Edit Text..." option should now work as expected.
