### ISSUE TITLE
New nodes are always in Sans 12 font

### ISSUE THREAD

**Issue by tomatic** [phase1geo/Minder#472]
When I change the font for all nodes to Sans 10, new nodes still have Sans 12. If I go in again and change the font for all nodes to Sans 10, the new node also changes to Sans 10. It's the same with any other font too, new nodes are apparently always Sans 12.

### Steps to reproduce

1. Click anywhere on the canvas so nothing is selected.
2. In Node Options change the font to Sans 10 (or something else except Sans 12). All nodes are changed to the new font.
3. Create a new node by selecting an existing node and pressing Tab to create a child node.

### Expected result

The newly created node has the font that was set previously.

### Actual result

The newly created node has Sans 12 font.

### Environment

Minder version: 1.14.0
Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-49-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 12 × Intel® Core™ i7-8700K CPU @ 3.70GHz
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2070/PCIe/SSE2

**Comment by phase1geo** [comment]
This issue should now be fixed in the master branch.
