### ISSUE TITLE
When exporting, auto-fill filename of exported file from filename of the .minder file

### ISSUE THREAD

**Issue by fpesari** [phase1geo/Minder#474]
Hello,

right now, when I try to export a Minder map (e.g. to PNG), the filename field inside the file dialog is empty. I think that rather than keep it empty, it would be nicer if it were set to a sane default, which IMHO is the filename of the .minder file (if it exists, else it could be "Untitled Document"), so that users can just press Enter and be done with it (or type the filename, which they would have done anyway in the current situation).

**Comment by phase1geo** [comment]
I have implemented this feature request in the master branch.
