### ISSUE TITLE
Selecting a new node after deletion

### ISSUE THREAD

**Issue by Zurnaz** [phase1geo/Minder#48]
While working via mainly keyboard and deleting a node the current node gets reset to nothing, requiring me to either click a node near where I was working on or navigate from the root.

I think ideally a sibling node to the deleted node would be selected and if one isn’t available the parent of the deleted node.

**Comment by phase1geo** [comment]
This issue should now be fixed in the git master branch. When a node is deleted, the next sibling node is selected. If the next sibling does not exist, the previous sibling is selected. If a sibling does not exist, the parent is selected.

**Comment by Zurnaz** [comment]
Tested, works great thanks!!
