### ISSUE TITLE
Markdown export bug

### ISSUE THREAD

**Issue by r0bis** [phase1geo/Minder#488]
**Main bug:** If there is a mindmap containing several root nodes, then no newline is inserted on export after the note, hence next `lvl 1 heading` is not on its separate line. (If I move other root nodes as subordinate to one root node, this behaviour disappears).

```
# Main Idea

  > main note# Another Idea

  > note another one# Another Idea

  > another last note
```
**Other relevant bits:** Overall I noticed quite a bit of problems with the note thing. `Shift-E` does not work as a shortcut. Also Markdown export (which is the most useful export, given pandoc style conversion is so prevalent these days) is a bit peculiar - instead of treating at least second and third level headers as headers on export, it puts it all notes as blockquotes under bulleted list under the root node. Which then begs the question - why allow markdown in notes at all. See below:

But the application as such is really good and simple. It is a vast improvement over freemind and others - just put your ideas down and export them quickly, work on your ideas some more and export again. So I am not complaining, I just wish this got a little better:
```
# Main Idea

  > main note  - second to main

  - Another Idea
    > note another one

    - Another Idea
      > another last note
      > 
      > ## This will be a bulleted list under this note heading
      > 
      > * bullet one
      > * and two
      > * and three
      > 
      > Why are all they exported as blockquotes? 

```

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch which will be available in the 1.15.3 stable release.  Unfortunately, this issue slipped through the cracks or it would have made it into the 1.15.0 release.
