### ISSUE TITLE
Keyboard shortcuts don't work with non-latin keyboard layout selected

### ISSUE THREAD

**Issue by novns** [phase1geo/Minder#49]
When one has multiple keyboard layouts, `en` and `ru` for example, it's not comfortable to switch between them for activating shortcuts.

Usually this is not a problem for Gtk apps.

**Comment by phase1geo** [comment]
Can you educate be a bit on this issue? How do keyboard shortcuts work on ru keyboards in typical Gtk applications?

**Comment by novns** [comment]
It looks that [`add_accelerator`](https://valadoc.org/gtk+-3.0/Gtk.Widget.add_accelerator.html) must be used instead of `add_accel_label`.
The difference is that `add_accelerator` uses numeric keyscans from GDK.

I don't know Vala and could not patch your code, but this simple example works as expected:
https://gist.github.com/novns/5c7518761e98139eef3066c63b3eba9a

**Comment by phase1geo** [comment]
I think that this problem has been addressed in the git master branch; however, I would like this to be confirmed or denied.

**Comment by HennadiiM** [comment]
Hey. Does shortcuts now really working with non latin layout?
I installed from [aur](https://aur.archlinux.org/packages/minder/) version 1.8.
And in my case shortcuts doesn't work with `ru` layour.
