### ISSUE TITLE
Keyboard shortcut for "Zoom to fit selected node"

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#492]
Just started using the "Zoom to fit selected node" feature and it's wonderful. I would like to use it so frequently that I would want a keyboard shortcut for it, since other zoom actions already have shortcuts.

Since Ctrl+6/7/8/9 already are taken by other things, maybe `Ctrl+2` could be used here?

Side notes:
* "Zoom to fit selected node" lacked a bit of clarity for me when first using it, as I thought it was meant to be used for multiple selected nodes, but I realize now the intent is "Zoom to fit selected node _and its children_ "; would it make sense to make its label more explicit like that?
* I noticed the zoom shortcuts are not present in the shortcuts cheatsheet dialog, I don't know if that's on purpose (as the menu reveals them) or if they were simply forgotten?

**Comment by phase1geo** [comment]
The zoom keyboard shortcuts already exist in the keyboard shortcuts cheatsheet (in the General tab).

I have created a new keyboard shortcut (Control-2) for the "Zoom to Selected Node Tree" menu item in the master branch.
