### ISSUE TITLE
Support for importing and exporting to md files via CLI

### ISSUE THREAD

**Issue by distbit0** [phase1geo/Minder#493]
Hi I have a script which syncs changes made between md files I store in Obsidian and minder files. I currently have to implement the conversion between md and minder xml files manually by reverse engineering the minder format.

It would be great if minder supported cli functions for converting an md file to a minder file and vice versa, so that I can call these from my script rather than need to implement these conversions manually! :)

Thanks for creating Minder.

Distbit

**Comment by distbit0** [comment]
I am ofc willing to release the sync script if anyone is interested, to make this feature more worthwhile to implement.

**Comment by distbit0** [comment]
It seems the exporting part of this issue has been resolved, but importing (converting MD to minder) is still not supported via cli.

**Comment by phase1geo** [comment]
Importing Markdown doesn't seem like a straightforward process, in my opinion since Markdown is really just text with some special markup syntax.  It's not inherently conducive for mindmap rendering.

I mean, I could just create a Markdown importer that understands what the exporter produces (reversing the process, so to speak), but I think that the plain text importer already does this essentially.

My primary concern is creating an importer that creates strange results (for example, if the user had a letter written in Markdown and then tried to import it into Minder -- what would the result be?  Additionally, header syntax is used to represent node titles and their depth in the tree, we would be limited to only a depth of 6.  This might be adequate for most documents, but not mindmaps.

Do you have any suggestions in this area?

**Comment by distbit0** [comment]
Ah hey thanks for this response @phase1geo. Sorry about the late reply. 

Yeah the current plain text import function is great, insofar as that it is compatible with the types of markdown documents I'd like to import, which are basically just nested dot point lists.

I do not at least personally see any need for the import function itself to be modified at all.

What I was wondering though is if you would mind adding functions to import plain text and export md to the CLI for minder.
I'd imagine the most elegant way of doing so would be to support importing from all currently supported formats as well as exporting to all supported formats to thee CLI.

This would be extremely useful for me as I have a script which is currently broken due to this CLI functionality not yet existing, designed to keep indented markdown lists in sync with minder mindmap files. If exporting and importing were added as command line functions to minder, I could integrate them into this sync script, making minder significantly more useful to me! :)

I'd imagine that in the CLI, to import, the user would specify the file to import (such as an md file), the import format (in my case, text) as well as the output file name (which would be a .minder file)

For exporting via the CLI I'd imagine the arguments would be the minder file to export, the output file name and export format.

Thank you for considering this.

Would be very much appreciated! :)

Distbit

**Comment by distbit0** [comment]
@phase1geo so all this issue is is basically [486](https://github.com/phase1geo/Minder/issues/486) except for importing md rather than just exporting via the CLI. 

So just a matter of exposing a pre-existing function within the Minder GUI as a CLI command :)

Distbit

**Comment by phase1geo** [comment]
I'm in the process of adding Markdown import support.  I'm basically only going to support importing Markdown format that Minder exports.  I have most of it working with the exception of images.  I'll update this issue when I have something ready for you to test.  Just thought I would let you know that there is some progress on this issue.

**Comment by phase1geo** [comment]
I have finally completed and included this functionality in the master branch which will be available in the next release.  If you are still interested in this functionality, feel free to clone this repository, build and try it out.  The method for importing a file is to use the --import=<type> where <type> in this case would be 'markdown' (without the single quotes). Then provide the file to import.  If you want Minder to just do a quick import/export, use the --export=<type> option.  The available import and export types are listed using the --help command-line option.
