### ISSUE TITLE
Fade out and lock/protect node connections / arrows for folded nodes' children

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#494]
I create a lot of connections with the `x` shortcut key, which leads to those various dashed arrows interconnecting nodes:

![Capture d’écran de 2022-07-01 19-15-14](https://user-images.githubusercontent.com/479401/176976978-a09eb91e-fedf-4e2a-b5bd-340f7bfdc421.png)

However, the problem is that when you fold the parent node, the dashed interconnections are left dangling in emptiness, and they "look" broken but are not:

![Capture d’écran de 2022-07-01 19-15-21](https://user-images.githubusercontent.com/479401/176977090-c0351466-84f5-4bbc-9692-248ae7a7fb27.png)

I think a visual indication would be in order, and preventing the user from moving/editing those connections until they unfold the related parent nodes, as accidents can happen too easily otherwise. For the visual indication, maybe Minder could make them transparent (30 or 50% opaque)?

**Comment by phase1geo** [comment]
That's actually a bug that has been fixed in the master branch, I believe.
