### ISSUE TITLE
(Flatpak) Export to freeplane/freemind crashes

### ISSUE THREAD

**Issue by deknos** [phase1geo/Minder#496]
Hello,
i want to export Minder files to Freemind or freeplane, but the export crashes silently. This is with the flatpak application.
If there are instructions i can try to provide a coredump, if possible with flatpak?

**Comment by deknos** [comment]
i have to change texts but i see what i can do! thanks!

**Comment by barthon-b** [comment]
Hi @deknos, which OS are you on? I'm getting the same on Manjaro which is on 1.14.0-1. If you're on Manjaro as well, this likely is the same as #483 and we'll get the fix in 1.15

**Comment by phase1geo** [comment]
I'm going to consider this issue to be fixed with the 1.15.2 release (it was probably fixed in 1.15.0).  If this issue still remains, feel free to reopen it.
