### ISSUE TITLE
Org mode export format

### ISSUE THREAD

**Issue by wpfan1000** [phase1geo/Minder#498]
Hi, I think it is great that you have provided an export to org mode.

I did an export in Minder to org mode and noticed that the file does not export to the standard org mode format.

The file that Minder exports has leading spaces per node and more indentation for deeper nodes, but only 1 leading star regardless of how deep the node level is.

The org mode format does not use indentation / leading spaces for subheadings.

Instead it uses more leading stars.

So a level 1 heading starts with:
*
A subheading starts with:
**
and so on.

There are no leading spaces used at all. All headings/headlines/nodes are left justified.

This is described eg at
https://orgmode.org/manual/Headlines.html

Please modify the org mode export functionality to suit the org mode format

**Comment by phase1geo** [comment]
I will get that corrected. Thanks!

**Comment by wpfan1000** [comment]
Great, thanks very much.

**Comment by wpfan1000** [comment]
Also please consider putting a blank line between each line of text in the text file (whether or not that line is a heading or contents for the heading).
The example at
https://orgmode.org/manual/Headlines.html
Does not show a blank line between each line of text but in org mode this is displayed as very cramped together :)

**Comment by wpfan1000** [comment]
My apologies.
I just noticed:
https://orgmode.org/manual/Clean-View.html
which shows an alternative format for an org mode file which seems to resemble the or mode export file of Minder.
Is this the standard that you used?
I have been using org mode for years and was not aware of this other format.
However, one needs to set org mode up to use this format:
https://orgmode.org/manual/Hard-indentation.html
And in all my years of using and learning org mode I had never seen this other format or needing to set org mode up to use it.
I expect though that most people who use org mode are not aware of this other format or needing to set up org mode for it.
So it may still be best to use the default format described at
https://orgmode.org/manual/Headlines.html

**Comment by phase1geo** [comment]
I will create an export option that allows you to select the format that you want to use (Minder will remember this setting until it is changed by the user, so you might only have to change it once if it is not the default). Does that sound reasonable?

**Comment by wpfan1000** [comment]
That would be great if you could put in the option to select the export format.
All my other org mode files use the default format.
So to use the hard-indentation format I would have to add and afterwards remove this setting to the .emacs config file:
https://orgmode.org/manual/Hard-indentation.html
So if you could put in the option that would save me having to do this.
Thanks again!
Great package and great support :)

**Comment by phase1geo** [comment]
I have implemented this feature in the master branch.

**Comment by wpfan1000** [comment]
Thanks!
