### ISSUE TITLE
Is flathub a secure installation source for Minder?

### ISSUE THREAD

**Issue by wpfan1000** [phase1geo/Minder#499]
Hi, I am a happy user of Rocky Linux, which is as you may know a byte for byte fork of Red Hat Enterprise Linux.
Hence flatpak is installed by default in Rocky, because it is in RHEL and I believe Fedora as well.
And so flatpak is a great way for me to use Minder.
BUT unfortunately with some packages on flathub, the developer of the package is not at all involved with adding the package on to flathub.
So someone else is taking a copy of the package, and putting it up on flathub.
And this leaves the opportunity for the code of the package on flathub to be modified from the original, including unwanted code.
And so before I use a flathub package, I always try and check if the developer is involved as a contributor for the flathub package, or at least mentions it as an official installation source.
https://github.com/flathub/com.github.phase1geo.minder/graphs/contributors/
I tried to check this with Minder and I dont think you are a contributor. Please correct me if I am wrong.
Then I also check if the developer is recommending flathub as an install option in the Installation instructions.
I dont see flathub mentioned under Installation or Distributions under
https://github.com/phase1geo/Minder
You do mention flathub under
https://github.com/phase1geo
But I am not sure if you are endorsing it by mentioning it.

As an example there are 2 versions of XMind on flathub:
https://flathub.org/apps/details/net.xmind.XMind
and
https://flathub.org/apps/details/net.xmind.XMind8
which says:
NOTE: This wrapper is not verified by, affiliated with, or supported by XMind Ltd.

And so I would not use XMind8.

Could you please let me know what your opinion is about using Minder on flatpak? Is it secure?

Thanks ahead of time from me, also an engineer (retired)

**Comment by phase1geo** [comment]
Minder does have a Flatpak manifest file in the top-level GitHub directory.  This Flatpak manifest, however, is based on the elementaryOS Flatpak runtime and not the Gnome Flatpak runtime.  The Flatpak manifest checked into Flathub is not maintained by Minder, so I would consider that to be an "unofficial" Flatpak.

So the short answer is that it depends on if your distribution includes the elementary Flatpak "store" (official) or only Flathub (unofficial).

**Comment by wpfan1000** [comment]
Thanks for explaining this.
Since the Minder version on flatpak for RHEL is not official, I will use it in a separate virtual machine to keep it isolated from my host / main Rocky Linux OS.
