### ISSUE TITLE
Can't connect a child node to two root nodes

### ISSUE THREAD

**Issue by lucascenir** [phase1geo/Minder#50]
I want to connect a child node to two root nodes, like an idea that converges from two different origins or something like a family tree.
![captura de tela de 2019-02-08 17 27 15](https://user-images.githubusercontent.com/14957594/52501316-32aa0400-2bc7-11e9-8ff5-347fbd06e625.png)
Is that possible and I'm missing something?

**Comment by phase1geo** [comment]
This is not currently possible; however, in a future release it will be possible to make these sort of connections.

**Comment by phase1geo** [comment]
Updating this issue to inform that in the upcoming 1.3 release, Minder will have support for a “connections” feature which will allow named links to be added between any two nodes in the mind map. This feature should satisfy this feature request.
