### ISSUE TITLE
Add support for ZWNJ character in title

### ISSUE THREAD

**Issue by ahangarha** [phase1geo/Minder#500]
In Farsi (Persian) and maybe some other languages, we use ZWNJ character to add a non-joining space between some letters. Currently Minder doesn't let this character to be added to the title.

As a reference you can try نرم‌افزار which currently look like نرمافزار

**Comment by phase1geo** [comment]
I'm not sure what would be required to fix this issue as font production is supposed to be handled by Pango and the input method context handler (both of which are standard libraries that are outside of Minder's code base).

**Comment by ahangarha** [comment]
I am not familiar with this project's stack. I tried to check the code but didn't find anything about text manipulation. So you mean there is not mechanism to sanitize the text within the code base; there is no text manipulation. Right?

**Comment by ahangarha** [comment]
I see something interesting.
I can type ZWNJ in detail window. Also I can copy paste a text with ZWNJ to the title but I cannot type it there.

So I guess there should be some kind of filtering/sanitization in the case of title.

**Comment by phase1geo** [comment]
The note field is a standard Gtk.TextBuffer which has its own text bindings.  The title fields in the mind-map are a more custom implementation with its own bindings, but under the hood should use the same input method and font rendering libraries as a Gtk.TextBuffer.  So there is a difference but I would not expect any differences in capabilities (at least in terms of entering characters regardless of language).

So, out of curiosity, how would I reproduce this issue on my end?  I'm not terribly familiar with characters used outside of those in most western countries.

**Comment by phase1geo** [comment]
For context, my laptop is a QWERTY keyboard (so maybe it is not possible to reproduce?)

**Comment by ahangarha** [comment]
You can add Persian (Farsi) keyboard to your system and use standard keyboard (there might be multiple options. To verify if you have installed right keyboard, set the layout to Persian and press m button. You should see پ.

If so, just press these keys while using Persian keyboard: 'kvl' (نرم) and then Shift+space (for ZWNJ) and then 'htchv'. You should see نرم‌افزار not نرمافزار.

**Comment by phase1geo** [comment]
Okay, I believe that I now have this issue fixed in the master branch.  It should be available in the 1.15.3 release.  If you would like to try it before then (to make sure I didn't miss anything), feel free to grab the master branch and give it a go.

**Comment by ahangarha** [comment]
I couldn't run the project from the code in the repo.

**Comment by ahangarha** [comment]
Is this issue resolved in any of the recent releases? I don't see relevant entries in the release notes.

**Comment by ahangarha** [comment]
Thanks for fixing this issue.
