### ISSUE TITLE
minder not compile or install:  missing lmarkdown library file

### ISSUE THREAD

**Issue by tckosvic** [phase1geo/Minder#504]
Tried both compiling and "sudo ./app install" of minder as cloned from github and whatever i try I get message that library "lmarkdown" is not found.  This library file does not exist in openSUSE OS as far as I can  find.  I also cannot find any reference to it elsewhere on internet as e.g., rpmfind or other file sources.  I get no info anywhere that it exists.

Is it perhaps created in meson compilation?   I am using system installed meson on openSUSE  I did not compile meson.

So, what/where is lmarkdown that is needed for minder install?

thanks,     tom kosvic

**Comment by phase1geo** [comment]
It's the libmarkdown2-dev package the contains the needed library.

**Comment by tckosvic** [comment]
thanks, found it
