### ISSUE TITLE
Disabling Animations of Property Sidebar

### ISSUE THREAD

**Issue by louwers** [phase1geo/Minder#510]
I find the animation of the Property Sidebar Tabs to be pretty distracting (switching between tabs, or unselecting a node).

Would it be an option to remove them? Or allow the user to disable them through a setting?

**Comment by phase1geo** [comment]
I have committed a change to the master branch that disables UI animations using the new "enable-ui-animations" glib setting.  To disable UI animations, you will need to access the terminal and add the following command:

`gsettings set com.github.phase1geo.minder enable-ui-animations false`

Set the value to true to re-enable animations (if desired).

**Comment by louwers** [comment]
Works perfectly! :heart:
