### ISSUE TITLE
Gentoo Ebuild

### ISSUE THREAD

**Issue by al1r4d** [phase1geo/Minder#511]
would you make minder ebuild for gentoo?

**Comment by stkw0** [comment]
I just pushed to ebuild to GURU, see https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=41a9a1755e427776f42a81c53db456325d89b476

**Comment by phase1geo** [comment]
I'm going to close out this issue tomorrow evening unless there is a reason to keep this issue open.
