### ISSUE TITLE
GLib-GIO-ERROR: Settings schema 'com.github.phase1geo.minder' is not installed

### ISSUE THREAD

**Issue by stkw0** [phase1geo/Minder#512]
After compiling and installing Minder-1.14.0 (using meson instead of the app build script as I'm trying to make a package for a distro) I tried to execute it and the next error was returned:
```
(com.github.phase1geo.minder:15728): GLib-GIO-ERROR **: 12:45:43.756: Settings schema 'com.github.phase1geo.minder' is not installed
zsh: trace trap  /usr/bin/com.github.phase1geo.minder
``` 

Note that file /usr/share/glib-2.0/schemas/com.github.phase1geo.minder.gschema.xml was successfully installed on the system.

**Comment by stkw0** [comment]
Solved I executed meson/post_install.py manually

**Comment by eli-schwartz** [comment]
> as I'm trying to make a package for a distro

The post_install script cannot run at `meson install` time if it is being installed into a DESTDIR for staged installs that gets turned into a distro package.

That has to be run once the distro package is unpacked to the final filesystem.

Typically, it would be run by distro integration such as post-install hooks, scriptlets, or triggers.
