### ISSUE TITLE
Minder doesn't save files

### ISSUE THREAD

**Issue by xbseb** [phase1geo/Minder#513]
Hello! I bought the Minder app  in the elementary os AppCenter. Drawing a mindmap works well. But when I save a mindmap, the programme makes me think that I saved it successfully but it does not. The folder remains empty. Nothing here. I have a Dell XPS 13 and elementary os 6.1, all updates installed. I am not a linux expert. Thanks!

**Comment by phase1geo** [comment]
Minder is released as a Flatpak on elementary, so make sure that the Flatpak permissions are setup to allow you to save to your file system.

To do that, go to System Settings app, click the Applications icon, and select the Permissions tab. Once there, find the Minder app in the sidebar and select it. Then enable the Home Folder permission (you may also want to select Printing as well).

Let me know if that doesn't solve your problem.

**Comment by xbseb** [comment]
Thank for the immediate response. I did the changes that you suggested and also restarted the system. Unfortunately it still doesn't wok. I have also libreoffice as a Flatpack,it can save files to the documents folder.

**Comment by phase1geo** [comment]
Okay, the system restart shouldn't have been necessary.  You should only need to restart Minder after the permission change.  I tried this procedure on a fresh system, and it worked for me.

The current Minder Flatpak doesn't enable home directory permissions by default, but that doesn't mean that all Flatpak follow this convention.

**Comment by phase1geo** [comment]
![image](https://user-images.githubusercontent.com/22555565/193455688-2b68fa23-8e22-45e3-bc63-4b3e48d3dfc5.png)

**Comment by phase1geo** [comment]
After making the permission change, I started Minder (which displayed a new mindmap tab), made some edits to the mindmap, did a "Save As" (saving the document to my Documents directory in the file selector) and verified that the mindmap was created in the Documents directory with the Files app.

**Comment by phase1geo** [comment]
And in case you were wondering, yes, I have changed the default permissions in the Minder flatpak manifest to enable home directory permissions by default so you and other users don't have to do this manually.  I like that elementary OS has these permissions in their System Settings application.  Makes Flatpak permissions feel more native to the platform and makes it easier to change/review them without requiring someone to download a third party application or modify system files :)

**Comment by xbseb** [comment]
Hi :) I checked the systems settings once again, minder still has permission to access document folder. So, I tried it again and suddenly the app successfully saved the file in the folder. I can close the app and open the file again. So, it works. The next few times, I will carefully check if the file is saved. Thanks.

**Comment by phase1geo** [comment]
I'm going to close out this issue, but feel free to reopen it (or open a new issue) if you run into something.
