### ISSUE TITLE
Add Note to a Group

### ISSUE THREAD

**Issue by DVegGyver** [phase1geo/Minder#516]
I don't know if there is this option but it will be usefull to add a note and/or a TAG to a group...
This could be usefull when different sub note are grouped togheter. in the tag we can write WHY we have Grouped those nodes.
![gruppo](https://user-images.githubusercontent.com/99847466/195879475-c4f6cade-85c0-49f0-94b3-193e2242791e.png)

**Comment by phase1geo** [comment]
I have added support for group notes in the sidebar in the master branch.  Feel free to kick the tires and let me know your thoughts.

**Comment by DVegGyver** [comment]
Ok, at the moment I have build from source and I have the version 15.
I need to remake the build, right?

**Comment by phase1geo** [comment]
Yes, you will need to get the latest version of the master branch and rebuild it.
