### ISSUE TITLE
Notes are sometimes deleted when clicking on node

### ISSUE THREAD

**Issue by aflorea-2k** [phase1geo/Minder#517]
### Steps to reproduce

1. Create a node (or use root node), select it.
2. Open sidebar.
3. Write some note in the "Note" field. Node now has a "note" icon, and hovering it displays the note.
4. Deselect node, by clicking in an empty region. "note" icon and hovering still work. Sidebar is still open.
5. Select node by clicking on it.
6. Note has disappeared. "Note" field of the sidebar is empty, and the "note" icon isn't here anymore. Hovering over the node yields nothing.

### Expected behaviour

Note would still be there.

### Additional info

On Arch Linux.

```
$ pacman -Qi minder
Name            : minder
Version         : 1.14.0-1
...
Build Date      : Sat 12 Feb 2022 10:35:21 PM CET
Install Date    : Wed 19 Oct 2022 03:13:43 PM CEST

$ minder --version
1.14.0
```

**Comment by aflorea-2k** [comment]
Also, note that when viewing/editing notes, I see no trace of markdown support. I don't even know where I should be seeing Markdown.

**Comment by phase1geo** [comment]
Make sure that the "Enable Markdown" toggle is selected in preferences.

**Comment by aflorea-2k** [comment]
It is in fact enabled, both in the preferences and in the node's style menu.

**Comment by aflorea-2k** [comment]
Note: it seems to me that the bug only happens when selecting a node with a note when no node is selected. Consider :

1. No node is selected
2. I select a node with a note
3. Note disappears :'(

However,
1. A random node is selected
2. I select a node with a note
3. Note stays :)

**Comment by phase1geo** [comment]
Testing this out in the latest master branch, I am not able to replicate the issue WRT a note disappearing.  As for the Markdown issue, Minder should be installing its own GTK4 source view language file for Markdown which allows the note buffer to display the Markdown in a somewhat rendered format (i.e., headers are sized larger with coloring, bold text is bolded, italicized text is italicized, URLS are underlined/colored/clickable, etc.)

I'm not sure why this wouldn't be working on your system.

**Comment by jschoone** [comment]
> Note: it seems to me that the bug only happens when selecting a node with a note when no node is selected. Consider :
> 
> 1. No node is selected
> 2. I select a node with a note
> 3. Note disappears :'(
> 
> However,
> 
> 1. A random node is selected
> 2. I select a node with a note
> 3. Note stays :)

I also face that issue. Same version.

**Comment by MountainX** [comment]
On Arch Linux I have Minder  version 1.14.0 installed (via package 1.14.0-1), the same as the other comments. I face the same issue too.

In addition to what others have said, notes on connections appear to always be deleted when I select that node.

I have not found any reliable way to prevent notes from being deleted, therefore, I cannot use notes.

**Comment by FeWa-zu** [comment]
Same problem with Manjaro & minder in version 1.14 from the official repository.

**Comment by izzel** [comment]
I think I found a fix for it.
```diff
diff --git a/src/NodeInspector.vala b/src/NodeInspector.vala
index 84ec56d..c048ff6 100644
--- a/src/NodeInspector.vala
+++ b/src/NodeInspector.vala
@@ -513,7 +513,8 @@ public class NodeInspector : Box {
         _link_color.alpha = 65535;
       }
       _detach_btn.set_sensitive( current.parent != null );
-      _note.buffer.text = current.note;
+      string a = current.note;
+      _note.buffer.text = a;
       if( current.image != null ) {
         var url = _da.image_manager.get_uri( current.image.id ).replace( "&", "&amp;" );
         var str = "<a href=\"" + url + "\">" + url + "</a>";
```

My guess is that `current.note` gets freed somewhere and gives the `_note.buffer.text` potentially random garbage. It fails an assert in GTK for proper UTF-8 and probably clears the string.

```
(com.github.phase1geo.minder:16848): Gtk-CRITICAL **: 17:23:59.472: gtk_text_buffer_emit_insert: assertion 'g_utf8_validate (text, len, NULL)' failed
```

**Comment by connoisseu-r** [comment]
> Same problem with Manjaro & minder in version 1.14 from the official repository.

Same with you. If i open minder from command line and select a node with note, i will get something like this.
> (minder:13220): Gtk-CRITICAL **: 11:56:33.241: gtk_text_buffer_emit_insert: assertion 'g_utf8_validate (text, len, NULL)' failed

**Comment by 0ion9** [comment]
I'd been wondering whether to report this. I don't find there is any difference in effect whether the previous node had a note or not. In fact, notes are sometimes deleted just by clicking on a node that is a parent or leaf of that node.

Also, keyboard selection of the node has the same effect.

I can add that the effect also occurs with connection notes. I know group notes now exist but I haven't figured out how to create groups, so i haven't tested group notes.

Also on Arch Linux x86_64, FWIW.

**Comment by MDCIrony** [comment]
I have exactly the same problem in Manjaro 22.0 with minderV1.14.0. Initialy I install the app with:

`sudo pacman -S minder`

But i found some problems, including the notes deleted when I clicking the node.

The unique solution I found was install the app with flatpak:

`flatpak install flathub com.github.phase1geo.minder`

This solve all problems for me. Finally, I made an alias for run app from terminal, adding the next line in .zshrc:

`alias minder='flatpak run com.github.phase1geo.minder'`

**Comment by MDCIrony** [comment]
@Lvceo no, I don't receive that problem. Maybe you have missing modules from xapp. Try to reinstall: 

`sudo apt install xapp`

In this stack they talk about it: https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module

**Comment by MDCIrony** [comment]
@Lvceo I didn't receive that message. Maybe you need to update your xapp modules or have missing modules. Maybe trying reinstall can solve the problem?: 

`sudo pacman -S xapp`

On this links talk about it: 
Arch: https://bbs.archlinux.org/viewtopic.php?id=263690
Ubuntu: https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module

But I think that is a general problem, not from Minder.

**Comment by 4127157** [comment]
I have the same issue on Fedora 37. Minder version 1.14.0. 

Steps to replicate bug : -
1. Create a node
2. Add note to note 
3. Click outside node
4. Click and release node or drag node
5. Note disappears

I have attached a video of the behaviour for clarity. 

[minderBug-2023-01-17_10.03.34.webm](https://user-images.githubusercontent.com/89254856/212810960-b4973801-72dd-4686-9851-ac877298aa77.webm)

Let me know if more information would be required, I'd be happy to help.

**Comment by MountainX** [comment]
> Same behavior here under Manjaro & V1.14.0-1, quite annoying actually, I can't keep going working with it. Thinking to switch to an other tool to keep my mind mapping. I was very happy with it until this appears, what a pity.

Yes, a pity indeed. I agree with you about the promise of this application, but I can't keep working with it either due to this bug. I'm sad to leave it.

I switched to Obsidian and MarkMind. MarkMind has a freemium model. This video introduced me to MarkMind: https://www.youtube.com/watch?v=fMq0aoAjueE
MarkMind with the PDF annotation & linking features is a whole new level of functionality for me.

**Comment by franciscofbneves** [comment]
I have the same issue on Kubuntu 22.10

**Comment by phase1geo** [comment]
Has anyone tried downloading and compiling Minder from the master branch and seeing if this issue still persists?  I was not able to replicate this problem with the latest master branch.  I would like to know if a 1.15.0 release as the code sits now contains this issue or not.

**Comment by aflorea-2k** [comment]
I tried, but there's no way to compile minder without also installing it; I would have to create a VM to test this.

**Comment by izzel** [comment]
Just tested as of fbf808e. It still deletes the notes.

**Comment by phase1geo** [comment]
I have applied the suggested fix in the master branch.  Could someone give it a try and let me know if it has been fixed?

**Comment by phase1geo** [comment]
I have applied the suggested fix in the master branch.  Could someone give it a try and let me know if it has been fixed?

**Comment by dmkoder** [comment]
I just tried the master branch and the problem is fixed for me (on Manjaro). The issue with markdown is resolved as well. However, the same issue remains for the notes on the connection arrow. I assume that the same fix could be applied somewhere else in the code.

**Comment by phase1geo** [comment]
Okay, I have just pushed changes to fix connection and group notes as well.  Could you give it one more try?

**Comment by dmkoder** [comment]
I tried it now, everything works as expected.

**Comment by phase1geo** [comment]
Awesome. Thanks for testing this out.
