### ISSUE TITLE
remove "- " from nodes/content copied to clipboard

### ISSUE THREAD

**Issue by daveiro** [phase1geo/Minder#521]
Following up on issue #206, I think my last comment/question there ends up identifying a "bug", so I decided to open this issue. 

I think it does not make sense that, while copying content from a map to the clipboard, the new content of the characters "- " is added to each node.

The expected behavior would be to purely copy the contents of the node(s) as described in detail on my comment on #206.

This "bug" is bugging me a lot because it breaks a lot of different workflows where I need to manually replace the "- " in the pasted content in an intermediate editor, before I make the final paste in the final app.

Thanks for your attention.

**Comment by phase1geo** [comment]
The copied plain text format is meant to be compatible with Minder's quick entry format.  This format requires a prefixed -,+,* character to specify a subnode.  I don't have any plans on changing this copy behavior in Minder.

**Comment by daveiro** [comment]
I understand that compatibility issue, but I was expecting that it's possible that the clipboard is able to hold two different kinds of content: the one that can be pasted internally in Minder would be in the quick entry format; the one that can be pasted outside Minder would be plain content. This is what happens when, for example, copying text in a rich format inside, for example, thunderbird compose message window. Pasting in another message window inside thunderbird keeps the formatting. Pasting on, for example, gedit, only plain non formatted content is pasted. Would it be feasible that the Minder code handling the copy action "fills" both of these "buffers" with the respective content as it happens like in thunderbird?

**Comment by phase1geo** [comment]
Your thinking about this differently than I am. I want consistency in input and output from Minder. You should be able to copy paste text (formatted for Minder) from any other app into Minder's quick entry field from the standard clipboard's plaintext data. Therefore, to maintain this consistency, Minder copies plaintext output in this same format to the same clipboard in plaintext.

Doing what you are suggesting would break this consistency.

**Comment by daveiro** [comment]
Thanks for your reply. And I understand your logic. It makes sense that one can be editing some plain text file, already "thinking" on pasting that content into Minder in the appropriate format for the quick entry field, and that use-case makes perfect sense.

But I don't see the need for replicating that behavior/format in the output.

Is there a use-case where it can be useful to paste content coming out of minder in the quick entry format on an external app that is not minder?

By definition, I would say that "quick entry format" has the sole purpose of making it "quick" to easily entry content/nodes into Minder. Entry is only "in".

And I would say that the general and most common use-case for pasting content out of Minder is to quickly put some content (typically a list of things) on some e-mail message, or some chat message or some document.

And in all these cases, the "purer" the content, the better. If I want to format it with dashes or bullets or whatever, I can quickly do that in the e-mail or document program.

This behavior of outputting "pure content" out of the mindmap is the approach used in the other mindmap software I've used (freemind) and I think it's the most useful for all users.

As it is now, one needs to manually replace the "- " characters in the pasted content in an intermediate editor, before the final paste in the final app, which really breaks the workflow.
