### ISSUE TITLE
Minder opens empty file when reopening previous file that was moved

### ISSUE THREAD

**Issue by tomatic** [phase1geo/Minder#522]
I'm using Minder 1.13.1 installed via apt on Kubuntu 22.04.

**Steps to reproduce:**

1. Have a mind map open in Minder and then close Minder.
2. Move the mind map file to a different location.
3. Double-click the file you just moved in your file manager (or press Enter on it).

**Expected result:**

Minder opens the file normally.

**Actual result:**

Minder briefly flashes the file you intended to open, but then reverts to a new file with a single map root node. This can be repeated multiple times, the behaviour is the same each time. Only when you manually open the intended file from within Minder will it load and from there on you can open it from your file manager.

**Comment by phase1geo** [comment]
This issue should now be fixed in the master branch.
