### ISSUE TITLE
Undo moved node doesn't undo color change

### ISSUE THREAD

**Issue by hleskien** [phase1geo/Minder#523]
Hi,

when I move a node after an existing node with a different color, the moved node gets the same color, which is intended. When I try to undo the move, the moved node's color isn't changed back which is a bug in my view.

Kind regards

Holger

**Comment by phase1geo** [comment]
In my attempt to reproduce the problem, I'm not seeing an issue with the node's color in the mindmap after the undo move operation, but I am seeing that the color of the current node sidebar is not being updated.  Is that what you are seeing as well?

**Comment by hleskien** [comment]
Well I tried to put together an example and couldn't reproduce the problem either. But in my everyday mind map it is. I'll keep researching.
