### ISSUE TITLE
Ctrl+C and Ctrl+X don't work with multiple nodes selected

### ISSUE THREAD

**Issue by tomatic** [phase1geo/Minder#524]
I'm using Minder 1.14.0 und Kubuntu 22.04 with a US QWERTY keyboard layout.

Selecting multiple nodes and pressing Ctrl+C does not copy the nodes to the clipboard, it seems to do nothing. Right-clicking and selecting `Copy` from the contextual menu works and `Ctrl+V` also works. The shortcuts also work if only a single node is selected.

**Comment by phase1geo** [comment]
I have committed a change to the master branch to add support for Control-C and Control-X when multiple nodes are selected.
