### ISSUE TITLE
Potential Quick Entry enhancement

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#527]
I've used Quick Entry quite a lot over the past year or two and one caveat I keep running into is how new rows keep disappearing below the editor view once I've inserted a lot of those. I need to scroll down all the time just to see what I type in.

This could be fixed by allowing the user to scroll way past the current bottom line so that the last row could be sitting on top. Here is how it looks in Sublime Text (with a different type of content, but that's not the point):

![image](https://user-images.githubusercontent.com/57467/210432242-2cb27193-207a-45eb-a79b-8fb6384c11cc.png)

Note that you can see the latest entry and you have plenty of space below to make new entries without having to scroll again — until you make a lot more entries.

**Comment by phase1geo** [comment]
I have checked in a code change to the master branch to implement this feature request.  If you are able and willing, could you grab the latest from GitHub and see if this change meets your needs?
