### ISSUE TITLE
[feature-request] Drag canvas by holding the secondary mouse button

### ISSUE THREAD

**Issue by kemelzaidan** [phase1geo/Minder#529]
Hi,

first thanks for the awesome app and second, I'd like to ask for and enhancement: it would be awesome if we could navigate through the canvas by clicking on it with the secondary mouse button (usually the right one) as we commonly do on other similar apps.

Holding shift and using the mouse wheel to scroll is useful sometimes but not as natural as dragging it with the mouse.

Thanks a lot,

Kemel Zaidan

**Comment by phase1geo** [comment]
If your mouse has a middle click button (scroll button press most likely), you can hold that down and move the mouse to pan the canvas.
