### ISSUE TITLE
`Ctrl+E` file export keyboard shortcut does not seem to work

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#530]
I don't know if this is broken for you too, or if it's just me and my unusual keyboard layout (French Canadian Dvorak!), but on my GNOME 43 Fedora 37 desktop on X11/Xorg, the `Ctrl+E` keyboard shortcut (Export) doesn't do anything on Minder 1.14.0.

Other shortcuts, such as `Ctrl+F` (Find), `F9`, `Ctrl+P` (print), `Ctrl+Shift+S` (save as) work without problems.

**Comment by phase1geo** [comment]
The Control-E shortcut has been removed from the interface.  I have removed its reference in the shortcuts helper display.
