### ISSUE TITLE
Do you support flathub?

### ISSUE THREAD

**Issue by wpfan1000** [phase1geo/Minder#535]
Edit:
Sorry, I found I had already asked this:
https://github.com/phase1geo/Minder/issues/499
and I forgot.
My apologies, feel free to delete this post/issue.

Hi, I use Rocky Linux which is a fork (as you may know) of Redhat Enterprise Linux.
I would like to install Minder.

Under Distribution packages:
https://github.com/phase1geo/minder/#distribution-packages
I dont see Rocky or RHEL listed.
So I went to flathub and I see Minder is available via flatpak.
https://flathub.org/apps/details/com.github.phase1geo.minder

But often the packages that are available on flatpak / flathub are not official packages directly from the developer.
Sometimes the packages are forked from the dev by someone else and then put on flathub.
Often there is a warning with a package on flathub eg "This flathub package is not affliated or endorsed with the original package"

This leaves the concern that the flatpak version of Minder may not be official, and may be modified from the original.

I have not been able to find whether you endorse the Minder on flathub. Maybe you even provide Minder on flathub.

Could you please let me know if you endorse or are the person providing Minder on flathub?

**Comment by phase1geo** [comment]
I currently do not officially support the Flathub repository.  I do support a Flatpak for the elementary OS ecosystem, but that is separate from Flathub.

**Comment by wpfan1000** [comment]
Please consider adding Minder to flathub - there is already a Minder at flathub and it even has your name on it:
https://flathub.org/apps/com.github.phase1geo.minder

but since it is not by you, it is not official, and I am very concerned someone is modifying the code........

You can also verify the existing Minder on flathub by approving the third party:

https://flathub.org/about

Verified apps
What does the checkmark under an app name mean?

Some apps have a checkmark on the app page under the developer name. This means the app is published on Flathub by its original developer or a third party approved by the developer.
