### ISSUE TITLE
Add image import through quick entry or through file urls 

### ISSUE THREAD

**Issue by micahchoo** [phase1geo/Minder#538]
I love this app, I have been looking for something that retains relationships in the export for sooo long. I love that in theory it's possible to build out a minder map entirely in XML. Thank you for this, my feature request is in the subject.

**Comment by phase1geo** [comment]
In a quick entry field, how would you prefer to add images?  Would you prefer to add them via Markdown syntax (i.e., ![text](uri) ).  Drag and drop support?  Or something else?  Keep in mind that it is valid for nodes to contain links to files and URLs within them, so I don't think I would supporting adding an image just by its file path.

**Comment by micahchoo** [comment]
I think through drag and drop would be awesome. Right now its quite a long process if my main unit of the mind map is an image.

**Comment by phase1geo** [comment]
Okay, that sounds reasonable.

In the meantime, you should be able to setup a mind map with images somewhat quickly by essentially creating your tree structure (with empty nodes) and then drag and drop your images onto those nodes in the map itself.  Not sure how you are currently adding image nodes currently, but if you didn't know you could drag and drop images onto existing nodes, it could help speed things up for you while this feature is implemented.

**Comment by micahchoo** [comment]
Ohh I didn't know that. I've been trying it out on my Windows with wsl and drag and drop is difficult to do. But i'll try it out on my Linux Machine. Thanks!

**Comment by phase1geo** [comment]
I have the requested functionality implemented in the latest release of Minder.   You can add the image path manually by prefixing the pathname with an '!' character within the node or you can simply drag and drop an image onto an existing bulleted "node" within the quick entry UI.
