### ISSUE TITLE
PNG export also exports the colored state of selected nodes

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#544]
This is a somewhat minor issue as there is a workaround, but with Minder 1.14.0 on Fedora 38, if you have a node selected in the mind map when exporting to PNG (and probably other formats), that node will remain colored blue (selection color) in the resulting exported file. Minder should avoid that; maybe by temporarily de-selecting any selected nodes, and re-selecting them after export?

**Comment by phase1geo** [comment]
I believe that this issue also exists with the new 1.15.1 version.  There's a partial fix in place there, but I think it still needs some work.

**Comment by phase1geo** [comment]
I think that exporting is now working properly in regards to avoiding drawing selections.
