### ISSUE TITLE
Minder-specific Markdown sourceview highlighting syntax is registered systemwide and interferes with regular markdown

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#549]
Hi~!  I have Minder 1.15.2 installed [from the Fedora 38 repositories](https://packages.fedoraproject.org/pkgs/minder/minder/), and I recently noticed (with this latest version) that it interferes with syntax highlighting for `.md` / `.markdown` files in other applications such as Gedit (I haven't tried other text editors, but I'd suspect they'd have the same issue). For example, the `# heading` headers are not colored like they normally would with the regular "markdown" syntax.

It turns out that gedit picks the "Markdown-minder" syntax over the normal "Markdown" syntax color thingy. Here's how it looks like if you click the syntax button in the Gedit statusbar:

![image](https://github.com/phase1geo/Minder/assets/479401/e2497946-34b1-431a-8098-4eab6ee445db)

Is there something that could be done on the minder side to keep that syntax highlighting registered only within itself, and not affecting the rest of the system's apps? I doubt anyone would edit .minder files outside of the Minder application.

**Comment by phase1geo** [comment]
I will look into it.

**Comment by phase1geo** [comment]
There looks to be a way to change the search directory list for languages and styles.

Once I get that change in and you get it, you will need to delete the minder files from your ~/.local/share/gtksourceview-4/language-specs and ~/.local/share/gtksourceview-4/styles directories.

**Comment by phase1geo** [comment]
I have  committed a fix to the master branch which should fix this issue.  I'm going to add an FAQ to address this issue as well.
