### ISSUE TITLE
I can not use the "<" symbol

### ISSUE THREAD

**Issue by andrefcorreia** [phase1geo/Minder#55]
I am trying to use the symbol "<" on node and cant use it. Like image below. The node stay empty
![Captura de tela de 2019-04-01 17-03-27](https://user-images.githubusercontent.com/7284944/55355999-285a0700-54a0-11e9-865d-60aa2f4cc0dd.png)
If I remove the symbol "<" it works. 
![Captura de tela de 2019-04-01 17-03-44](https://user-images.githubusercontent.com/7284944/55356114-7242ed00-54a0-11e9-8ab5-09c423cfbfb6.png)

**Comment by phase1geo** [comment]
Node titles allow HTML markup to allow text to be styled. The text between the < and > characters are being parsed as HTML syntax. If you want a '<' character, use '&lt;'.

Just a heads up that the next version of Minder will allow markup mode to be enabled/disabled within a node. It will also fix some issues surrounding editing marked up node text within the canvas.

**Comment by andrefcorreia** [comment]
Hi,
 " If you want a '<' character, use '<' "
didn't work

**Comment by phase1geo** [comment]
I forgot that GitHub allows Markdown... Use &-l-t-; removing the dash character in this text
