### ISSUE TITLE
Please support flathub

### ISSUE THREAD

**Issue by wpfan1000** [phase1geo/Minder#550]
Please consider adding Minder to flathub - there is already a Minder at flathub and it even has your name on it:
https://flathub.org/apps/com.github.phase1geo.minder

but since it is not by you, it is not official, and I am very concerned someone is modifying the code........

You can also verify the existing Minder on flathub by approving the third party:

https://flathub.org/about

Verified apps
What does the checkmark under an app name mean?

Some apps have a checkmark on the app page under the developer name. This means the app is published on Flathub by its original developer or a third party approved by the developer.

I am using Rocky Linux, which along with Alma Linux, are becoming very popular forks of Red Hat Enterprise Linux (RHEL), and an official flathub version would allow users of these distros to use Minder. 

I see you do support Fedora. As you may know, Fedora is an upstream development version of RHEL, so it would be great if the downstream versions of Fedora, ie RHEL, Rocky and Alma would be supported as well.

**Comment by phase1geo** [comment]
I am currently working on trying to get a Flathub package to work properly with the new 1.15.3 release.

**Comment by wpfan1000** [comment]
Great news! Thanks!

**Comment by wpfan1000** [comment]
Thanks for doing all that. I did not know flathub could do that. If you don't mind, please consider mentioning flatpak as a method of installation under your Installation heading at https://github.com/phase1geo/Minder and provide a link to https://flathub.org/apps/com.github.phase1geo.minder.

**Comment by phase1geo** [comment]
Done. Thank you for the suggestion!

**Comment by wpfan1000** [comment]
Thanks :)
