### ISSUE TITLE
Regression: broken zoom coordinates system?

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#551]
Hi ! I'm running version 1.15.2 from the Fedora 38 repositories, on a GNOME Wayland session with two monitors. I have also experienced the issue if running under a Xorg GNOME session. The issue did not occur in 1.14.x and earlier.

It's a bit difficult for me to explain, but basically it seems as if the whole coordinates system is broken, whether for existing .minder files or brand new ones: when you Ctrl+Scroll to zoom in/out (or even using the zoom menu actions), zoom seems to occur based on either (0, 0) coordinates or "something completely off-screen somewhere". I can't quite figure out what it's based on, but in any case it never is related to the mouse cursor's position, nor the selected node, and I am having great difficulty moving around and zooming to see the contents because of this.

Here is a video that attempts to demonstrate the problem (unfortunately you can't see the mouse cursor, but it doesn't matter, suffice to notice that it seems to use a fixed anchor point for the zoom no matter what happens): https://youtu.be/Fo5qvjMl-eQ

**Comment by phase1geo** [comment]
This issue should now be fixed in the master branch.
