### ISSUE TITLE
Overlapping branches / broken node auto-positioning in recent versions

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#552]
Here's a demonstration video where I'm simply trying to drag and release the nodes in the same spot where I initiated their drag: https://youtu.be/NoikzZWooRg

When dragging nodes to reorder them, or even just for the fun of "wiggling" them a bit (or you start a drag and change your mind...), the positioning used to be flawless, but now it often positions them in completely unpredictable faraway places, where it will overlap with other nodes from other tree branches, or even with itself.

This did not happen in previous versions, as far as I know.

Additional observations:

* Sometimes dragging the parent node resets/re-positions all the children correctly.
* This happens both for old existing .minder files, and newly created ones, and does not seem to require a hugely complex tree to occur.
* It occurs with all map root node layout styles.
* Like in #551, I'm running version 1.15.2 from the Fedora 38 repositories, on a GNOME Wayland session with two monitors; I tested under a Xorg GNOME session as well and it occurs there, too. I don't think I experienced this issue in 1.14.x and earlier, or maybe something in the middleware stack changed between Fedora 37 and 38, but I kinda doubt it would cause this issue in this particular app only.

**Comment by nekohayo** [comment]
This seems to behave differently depending on what zoom level you are at. Maybe it is related to zoom and coordinates; maybe it is also related to font sizes / font scaling? (just throwing some wild guesses at this)

**Comment by phase1geo** [comment]
This issue should be fixed in the master branch now.
