### ISSUE TITLE
Jumping other side of root node with arrow keys

### ISSUE THREAD

**Issue by tamerh** [phase1geo/Minder#557]
Hi, Firstly thanks a lot for this is amazing app.

I have one issue and not sure it is a known issue. When I navigate with arrow keys I can't jump to other side of the root node. 

For instance if I am at the right side of the root node i can navigate within the child nodes with the arrow keys and able to reach the root node but can't go to other side of the root node. 

I have to click one of the node in the other side of the root node in order to navigate among them.

**Comment by phase1geo** [comment]
I'll look into potentially improving this.  With that said, all nodes that have the root node as a parent are siblings and you should be able to navigate between sibling nodes using the up/down arrow keys.  So if you are using a layout that allows nodes on both sides of the root node, just trying using up/down when one of the nodes connected to the root node is selected.

I know that's not quite what you are looking for, but at least you won't have to grab for the mouse :)

**Comment by tamerh** [comment]
oh I got you there is way to go other side :) Thanks.
