### ISSUE TITLE
Keeping folding state

### ISSUE THREAD

**Issue by tamerh** [phase1geo/Minder#558]
Hello,  Currently, when I use the fold/unfold option, it unfolds all children nodes, including those that were previously folded. Is there way to keep the child node folding state? If not It would be great to save folding state this is very useful for me especially when I gradually present my map.

**Comment by phase1geo** [comment]
Which version of Minder are you using?  For versions > 1.15.0, clicking the fold icon or selecting a node an hitting 'f' to fold will do a "shallow fold" meaning that it will remember folds happening further down the tree.  Holding shift while clicking or hitting the 'f' key will do a deep fold, meaning that all nodes on the folded branch will follow the selected node.

For versions 1.14.x and below, I don't believe that shallow folding was supported.

**Comment by tamerh** [comment]
Yes seems I have old version 1.5.1 for Ubuntu. I installed with `apt install minder` and my repo seems up to date. How can I install latest version?

**Comment by phase1geo** [comment]
Yes, that version is pretty ancient. I don’t control Ubuntu packages, so you would either have to install via Flatpak (I don’t know if Ubuntu supports this) or try installing from source (recommended).

**Comment by tamerh** [comment]
I updated to latest version. All issues has gone and came with cool features. Thanks
