### ISSUE TITLE
Loading icon

### ISSUE THREAD

**Issue by tamerh** [phase1geo/Minder#559]
Hi, Seems that loading icon stuck at the toolbar. what could be the reason or how can i fix it? Thanks 
![Screenshot from 2023-07-18 14-11-38](https://github.com/phase1geo/Minder/assets/13216024/bbe11ce9-d03e-4e86-bb22-15d42cd1bc97)

**Comment by phase1geo** [comment]
If there is a valid, pre-existing mindmap in the unnamed1.minder tab, you will need to save it to somewhere on disk.  If you can't save from the UI, the minder file will be located in your ~/.local/share/minder directory (if you are running a Flatpak version of Minder, this directory might be somewhere else on disk).

Once you have an unnamed Minder files saved to disk, try deleting the ~/.local/share/minder/tab_state.xml file and restarting Minder.  Deleting this file will remove Minder's knowledge of what was loaded in tabs, so you will need to reopen anything you were previously working on.

As for the cause of the issue, I don't know.  I would need to be able to reproduce your situation on my end which may or may not be possible.  It looks like you might be running on Ubuntu.  I don't currently have a way of running on Ubuntu.

**Comment by tamerh** [comment]
Thanks, yes using Ubuntu and my minder version seems old 1.5.1. Applied your suggestion no unnamed file and clean tab_state.xml but loading icon is still there.

**Comment by phase1geo** [comment]
Ugh.  I don't know that I have a suggestion beyond installing the latest stable release (1.15.2) from GitHub.
