### ISSUE TITLE
Navigation design : intuitive moves ?

### ISSUE THREAD

**Issue by goldanorak** [phase1geo/Minder#562]
Hello, I'm running Minder 1.15.1 into linux mint 21.2; cinnamon environment version 5.8.4. Thanks again for this great software ! The choice of shortcuts for zooming into the map (Ctrl + scroll) or for moving it when it's too big for the screen (Alt + simple mouse movement) seems to me to be too different from the norm (or how i think it is ;-). It seems to me that the predominant model, with a mouse, in most softwares that display images is : zoom in/out with a simple scroll (without a Ctrl key), and for moving when the zoom is enlarged: Ctrl+"drag-and-drop" (rather than a simple mouse movement). And the correlation between cursor move and map move, as I see it in Minder 1.15.1, seems to me to be very little used elsewhere in display designs, and therefore not very intuitive. Most of the time in softwares, when you drag and drop in a given direction, the view moves in the opposite direction, like a sheet of paper being slid across a table with hand. Wouldn't it be more intuitive ? In Minder 1.15.1, it goes in the other direction, as if you had to show, with the mouse, in which direction you wanted to move. This is rarely used, but it's also impractical in many situations, because when you come to a corner that's "trimmed" on the display, your mouse is usually already there too, so there's no room on the screen to move the mouse cursor further in that direction ; so you have to start by moving the mouse back in the opposite direction ... then press Alt, and then move the cursor back in that direction. Likewise, dragging and dropping (with or without Ctrl) seems more intuitive, because it corresponds more closely to the gesture of the hand touching the paper to move it, before lifting itself up again. So I make this proposal, even if it's not a "bug", but a question of design with a certain subjectivity.

**Comment by phase1geo** [comment]
I have added a new preference option to the master branch that allows the user to specify whether "natural scrolling" should be used within Minder.  There are three settings:  use the system setting, always use natural scrolling, and never use natural scrolling.  This will change all canvas panning operations to use the desired behavior.
