### ISSUE TITLE
Can't save theme, saved theme will disappear.

### ISSUE THREAD

**Issue by command-z-z** [phase1geo/Minder#569]
When i customize a new theme, and set `prefer Dark Mode`, then click save button. The saved theme will disappear.
minder version: 1.15.6

**Comment by phase1geo** [comment]
I'm just thinking about this.  Minder will hide all themes that do not match the current system theme (by default).  So if you are working in a system with a light theme and you set the "prefer dark mode" setting of the theme and save it, it will not be displayed in the theme chooser.  You can change this in Minder's settings (to always show all themes).

In the Appearances panel of preferences, set the "Hide themes not matching visual style" to the off position.  Let me know if your new theme appears after doing that.  If it does not, I will continue to consider this issue a bug.

**Comment by command-z-z** [comment]
> I'm just thinking about this. Minder will hide all themes that do not match the current system theme (by default). So if you are working in a system with a light theme and you set the "prefer dark mode" setting of the theme and save it, it will not be displayed in the theme chooser. You can change this in Minder's settings (to always show all themes).
> 
> In the Appearances panel of preferences, set the "Hide themes not matching visual style" to the off position. Let me know if your new theme appears after doing that. If it does not, I will continue to consider this issue a bug.

I'm so sorry too late to reply you. After I set the "Hide themes not matching visual style" to the on position, the problem is solved. Thank you for your awesome application.
