### ISSUE TITLE
Better keyboard workflow

### ISSUE THREAD

**Issue by CameronNemo** [phase1geo/Minder#57]
It would be superb if I could navigate most of the node creation, deletion, and traversal with keyboard shortcuts.

I like the vim shortcuts, but I understand that everybody has their preferences.

Anyway there are some rough edges when you are trying to use this app with only the keyboard. Hopefully they can be addressed.

**Comment by phase1geo** [comment]
I have a new version of Minder that should be released on elementary AppCenter sometime this week. I would be curious to know if any of the rough edges you mentioned are better in that release. If not, I would like to know more specifically what needs to be fixed or improved.

Minder doesn't use Vim shortcuts unless you are just considering the use of character keys minus modifier keys for keyboard commands. I don't really see how adding modifier keys improves keyboard usage beyond what currently exists, but perhaps I could be convinced otherwise if there was more detail about this.

**Comment by CameronNemo** [comment]
I am using 1.2.1. Only using text nodes.

Pressing `escape` while editing the text in a node clears the contents of the node. Furthermore undo will not restore the text. This is the biggest frustration for me. I suggest making `escape` simply save the current text in the node.

The `e` (edit) shortcut is hard to guess. `i` is more familiar for vim users. Furthermore I don't understand how to close the inspector menu (using the keyboard) when I inevitably and accidentally press `i` instead of `e`.

`enter` & `tab` make enough sense.

The arrow keys have me jumping around my keyboard more than I would like to (`escape`, `delete`, and the arrow keys are in three different corners). `h`, `j`, `k`, and `l` are open, on the home row, and again they are familiar/guessable for vim users. Additionally (and this might be a challenge I understand) it would be pleasant if the level 'cursor position' was preserved. For example, if I am in a lower level and I move to the parent level then back (`left` then `right`), I would want to be in the same place I started. Currently I start back at the first node at that level.

Zooming with `z` was a surprise. I think `ctrl` + `0|-|=` is pretty standard. I don't see `ctrl` + `+` being used often, however. That was again a surprise. `a` and `p` both surprises (anterior? peer?).

**Comment by phase1geo** [comment]
I believe that I have most of the changes in place in the "connect" development branch. Here is a rundown of what I have done:

1. Hitting the Escape key while editing a node's title in the canvas will end editing mode, retaining the changes made to the title.
2. Hitting the Escape key when the inspector sidebar has input focus will cause the sidebar to close and return keyboard focus to the canvas. (Until this change is generally available, you can always use the Control-| shortcut to open/close the sidebar).
3. I have implemented the h, j, k and l keys to map to the left, down, up and right key functionality that currently exists.
4. I have implemented support for remembering which child node was last selected within a parent node.

As for the 'e', 'z' and 'Z' keys, I don't think that I'm going to change their current function for now.

By the way, 'a' stands for ancestor and 'p' stands for previous sibling (n stands for next sibling).

**Comment by CameronNemo** [comment]
Thanks for addressing this!
