### ISSUE TITLE
Linking a node to a group or multiple nodes

### ISSUE THREAD

**Issue by NicolasSchuler** [phase1geo/Minder#570]
Hi,

**Describe the solution you'd like**
Like the title is suggesting, I want to link a node (blue node) to a specific group of different nodes (green group). By looking at the documentation and trying things in the application itself, I could not find a method to this, so I wanted to propose this idea as a feature enhancement.
![](https://i.ibb.co/jJP14Xz/minder-group-links2.png)
I've attached a picture for further clarification.
Maybe it could be possible to link nodes to groups, or increase the number of node-links for a node?
For my particular case, I would like the link itself nor the group to be visible, because this would visually clutter my mindmap to much (nodes are too much apart and grouping could be excessive). Optimally, the possibility of linking a node to multiple other nodes would suffice (in my case). For example, by allowing in the "Note"-Tab of a node property to 'list nodes' manually.

--

**Note:**
* *node-1*
* *node-2*
* *node-3*

--

so that I can click on them.

**Describe alternatives you've considered**
I could maybe transform it, by utilizing a node which represents the group (maybe even a hidden node?).

Regardless of the feature request, thanks for all the work. I really do like Minder and I think it is a great application.

**Comment by phase1geo** [comment]
Adding support for linking to more than one node is a good suggestion.  Linking to a group is not really feasible, but we could allow the user to select a group to link to which would create a link to the primary node in that group.

I have some different thoughts about the UI/UX for this request, but it ultimately supports the desired functionality requested here.

**Comment by NicolasSchuler** [comment]
Thank you very much for your consideration.

It is not directly stated in my post, but allowing the user to also express why the nodes are connected was also a subgoal. For example if I'm learning a language and have sentence patterns that are similar but slightly different, I wanted to express why it is slightly different in the "Note"-Tab and then have a clickable link to the node.

**Comment by phase1geo** [comment]
Thank you for that extra bit of clarification. Makes sense.

**Comment by phase1geo** [comment]
Okay, I have updated the main branch to include support for this functionality.  Here's how it works:

From any mind-map, select a node and copy it (Control-C).  Select a node, connection or group in the same mindmap or any other mindmap, go to the note field and perform a paste.  This will insert text that looks like "@Node-X" where X will be a unique number within the mindmap.  This text will be underlined to indicate that it is Control-clickable.  You can add additional information in the note field to document the node relationship (or anything else that you want).

To select the node within its associated mindmap, simply Control-click the "@Node-X" text.  You can also get some tooltip information about the node, by Control-hovering the mouse over the "@Node-X" text.

Feel free to give this a try.  These node links can be added to any note field.  Additionally, if the associated node/connection is copy and pasted to another mindmap, the linked node information will follow it and everything should work as expected (the node will link to the original mindmap map that was copied).

If you are able, feel free to download and build from source and give the feature a try.  Feel free to provide any feedback.

**Comment by NicolasSchuler** [comment]
Thank you very much. I tried it right now on a fresh VM (lubuntu 23.04 (Lunar Lobster)).

With nodes this worked as you described, with groups and connections I couldn't get it working and the application crashed. 


`** (com.github.phase1geo.minder:3548): CRITICAL **: 12:20:24.532: note_view_paste_node_link: assertion 'link != NULL' failed`
and sometimes also:
`(com.github.phase1geo.minder:3548): Gtk-CRITICAL **: 12:20:38.880: _gtk_selection_request: assertion '(data.format >= 8) && (data.format % 8 == 0)' failed
`

The hovering works and shows the title of the node. I guess giving the node an ID for a name is a good approach if the node-title is too long, or contains a lot of words etc. I would prefer something like the link mechanism in markdown, where you have a link and you can give it a name, because that way I could see in an instance the node title (which in my case is a unique grammar point), instead of hovering over them one by one (looking at the title in the tooltip) or writing the node title besides the node-link.

But I think your approach is the most general one that will work for all use cases and the most users equally 👍.

**Comment by phase1geo** [comment]
Okay, if you want to try pulling from the main branch again, these issues should be addressed.

**Comment by NicolasSchuler** [comment]
The crashes are gone 👍. And thank you for adding the node title next to the link. 

I missunderstood your post before (https://github.com/phase1geo/Minder/issues/570#issuecomment-1732490988), because I thought links to groups and connections are also possible now. That's why I got a little bit confused.

From my part this issue can be closed now.
