### ISSUE TITLE
Please introduce the ability to increase image resolution when exporting to PNG and JPG.

### ISSUE THREAD

**Issue by qua-rus** [phase1geo/Minder#572]
... The resulting file is very low resolution and cannot be used.
Thank you in advance.

**Comment by phase1geo** [comment]
Is the issue with the resolution itself or is the mindmap really small in the resulting image?  Could you provide a screenshot of the PNG/JPG image so that I can see what might be required to replicate this issue?  I haven't had any issues with image resolution in my own testing of image exporting.

Additionally, JPEG export does provide a "Quality" slider in the export interface that could affect image quality.  The PNG export provides its own "Compression" slider that might also affect image quality.  If you are using newer versions of Minder (I can't recall exactly which version these export options became available), you could try changing those values to see its effect on the export output.

**Comment by qua-rus** [comment]
Hello.
If the size of the mind map is small, then the file resolution when exporting is not enough. The clarity of the picture suffers (files are attached).
![NOTEs_0_compression](https://github.com/phase1geo/Minder/assets/91870946/c87e1fec-62cf-4bc1-88d4-c115a0fd7c79)
![NOTEs_5_compression](https://github.com/phase1geo/Minder/assets/91870946/abd4b9f6-6492-4a3c-8388-b510b0ade160)
![Screenshot_2023-10-02_15-06-39](https://github.com/phase1geo/Minder/assets/91870946/a0f71c0f-5f0a-4167-99d4-53207eda0e9b)
![Screenshot_2023-10-02_15-07-14](https://github.com/phase1geo/Minder/assets/91870946/51ff3882-bbcc-4f79-a414-55a9be6b4952)

If the mind map is large, then using a graphic file in a larger format (larger than A4) will also be problematic.
In https://app.diagrams.net, when exporting to a graphic format, scaling is used... this allows you to achieve the necessary clarity of the picture.
I will be glad to see a similar tool in your application.
Thank you in advance.

**Comment by phase1geo** [comment]
So are you suggesting that Minder add a Zoom option when exporting?

I mean PNG/JPEG images are not scalable graphic formats, so at some point when zooming in on an image (pretty much anything above 100%), the resolution is not going to look worse and worse.  I wouldn't necessarily consider that an issue specific to Minder.

I'm not sure that I understand the issue with "small" mindmaps and how scaling would fix anything.  Perhaps more clarification here would be useful to me.

If adding a zoom option is what is being asked for, keep in mind that any images added to a mindmap that were bit-mapped graphic images have resolution issues when zooming within Minder.  Again, not a Minder-specific issue -- just a limitation of what can be done with bit-mapped graphics.  So if you embed images with a poor resolution, scaling the mindmap up before exporting is going to mean that those images will not look very good.

**Comment by qua-rus** [comment]
Hello.
To evaluate my wishes, I offer image files of a simple diagram exported using drawio (https://app.diagrams.net https://github.com/jgraph/drawio-desktop):
Export scale 100%
![zero_100](https://github.com/phase1geo/Minder/assets/91870946/43d6e2ca-b0c5-40ce-8a86-0236d2055022)
![zero_100_screen](https://github.com/phase1geo/Minder/assets/91870946/16c52622-fcaa-4387-b7b7-cf22463940f1)

**Comment by phase1geo** [comment]
I have added zoom options to the JPEG and PNG export formats.  This will draw the resulting image at a different zoom level than the default (100%) if adjusted.  This change has been committed to the main branch.

**Comment by qua-rus** [comment]
Thank you. All the best.
