### ISSUE TITLE
Other OS

### ISSUE THREAD

**Issue by gibranlp** [phase1geo/Minder#58]
Hi,

Is it oossible to install this in other linux distros, like Fedora o Solus?

**Comment by phase1geo** [comment]
I’m sure it’s possible since the source code is available; however, I have nothing in the project that will build install packages apart from Debian and I don’t plan on creating and maintaining those myself.

**Comment by tim77** [comment]
@gibranlp https://github.com/phase1geo/Minder/issues/59

**Comment by phase1geo** [comment]
I have added Minder installation instructions to the README file.
