### ISSUE TITLE
Progress indicator above tab bar

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#586]
Starting at two open tabs, Minder gets a circular progress indicator at the center of the tab bar:

![image](https://github.com/phase1geo/Minder/assets/57467/b5d7107b-651e-491b-b8fe-afcc2ddb627f)

I purged the local config folder, purged system directories of all traces of Minder, then did a clean build and install from git, and I just can't get rid of it.

This is currently on Ubuntu 23.10, but I've seen this on earlier versions of Ubuntu for the past year or so, I just haven't reported it before.

**Comment by phase1geo** [comment]
Have you been able to replicate this issue lately?  There is another issue that was created in the last week or so against Linux Mint.  I'm unable to replicate this problem on any system (although I remember seeing it on Ubuntu versions in the past).

**Comment by prokoudine** [comment]
I have switched to Fedora and I don't see this issue anymore. So it must be Debian/Ubuntu/Mint-specific.

**Comment by phase1geo** [comment]
Okay thanks.

**Comment by phase1geo** [comment]
I'm going to close out this issue as #632 is a more recent version of this issue.
