### ISSUE TITLE
Fedora RPM package

### ISSUE THREAD

**Issue by tim77** [phase1geo/Minder#59]
#### Not issue, just info:

📦 Minder RPM package in [COPR](https://copr.fedorainfracloud.org/coprs/atim/minder/)

How to install:
```shell
sudo dnf copr enable atim/minder -y && sudo dnf install minder -y
```
Run:
```
minder
```
Will try to push it main repos soon.

Thank you. 🙏

**Comment by phase1geo** [comment]
Thank you for providing this!

**Comment by phase1geo** [comment]
I have updated the Minder README to include this installation information.

**Comment by phase1geo** [comment]
Are the installation instructions that I have posted in the README still correct?

**Comment by tim77** [comment]
Yep but after few days Minder will be available in official Fedora repos and you can install it via Gnome software or by:
```
sudo dnf install minder
```
