### ISSUE TITLE
Completion status not updated

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#591]
1. Create some nodes, press T to add todo status
2. Mark a few as done. Parent node gets an update that shows the task is partially done
3. Delete the nodes that have the 'done' status
4. The parent node is not update and still has 'partially done' indicator

**Comment by phase1geo** [comment]
I am able to replicate this issue.  I'll start digging into it shortly.

**Comment by phase1geo** [comment]
I have committed a fix to the master branch to fix this issue.
