### ISSUE TITLE
Shortcut for setting a color

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#596]
One common action I do that is missing a keyboard shortcut is setting a color to a selection of nodes.

Ideally, it would be great to have a keyboard shortcuts editor so that users could reassign shortcuts to various actions. But even something available by default for "Set color..." would be great. How about 'C' (Color)? I could do a PR if you are fine with the idea.

**Comment by phase1geo** [comment]
I have committed a change to the master branch that adds support for Shift-L to change the link color of one or more selected nodes.

Eventually, adding a shortcut configuration capability, but hopefully this gets you going for the time being.

**Comment by prokoudine** [comment]
Wow, that's already a huge improvement, because going through 3 levels of menus was a bit too much. Thanks a lot!
