### ISSUE TITLE
Just a suggestion about emojis

### ISSUE THREAD

**Issue by andrefcorreia** [phase1geo/Minder#60]
If possible, would be great to add emoji when edit text in a node.
![Captura de tela de 2019-05-03 16-23-26](https://user-images.githubusercontent.com/7284944/57161477-17175980-6dc2-11e9-81af-4cd6e176b6e9.png)

**Comment by phase1geo** [comment]
Makes sense to me :)

**Comment by phase1geo** [comment]
I have added this feature in one of the development branches in GitHub, so the feature will be available in the next release. To insert an emoji while editing the node’s text in the mind map, you will use “Control-.” (Same shortcut used to display the emoji picker in entry and text fields).

**Comment by andrefcorreia** [comment]
OK. Thank you
