### ISSUE TITLE
1.16.2 build error

### ISSUE THREAD

**Issue by tim77** [phase1geo/Minder#602]
https://kojipkgs.fedoraproject.org//work/tasks/8013/111878013/build.log

Vala: `0.56.14`

**Comment by phase1geo** [comment]
How are you adding the additional gcc options?

**Comment by phase1geo** [comment]
I can't replicate these compile failures using Minder's build meson build system even in a Fedora 40 container.  I'm going to need some help creating a build environment that I can reproduce these issues and verify their fix.

**Comment by tim77** [comment]
This is canonical Fedora build flags which i MUST used for official packages:

```
CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
```

- https://docs.fedoraproject.org/en-US/packaging-guidelines/#_compiler_flags
- https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/buildflags.md

**Comment by tim77** [comment]
It compiles fine locally for me as well for f39, f40. Something with Koji builders i guess. Sorry for noise. until I can get more information.

https://src.fedoraproject.org/rpms/minder/pull-request/3

**Comment by tim77** [comment]
This [could related](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/GKCRXZESHSCCEKED2N5GNQ7GH32VSK2X/#GKCRXZESHSCCEKED2N5GNQ7GH32VSK2X) to porting on modern C and F40 progress.

> Come up with a way to resolve the Vala situation, likely by embedded
  “#pragma GCC diagnostic” in the generated C source files.  Vala is
  currently not able to generate type-safe C, and is unlikely that this
  going to change soon.  (The numbers above do not include packages
  which have failures in Vala code only.)  In some cases, there is
  nothing that can be done about this on the Vala source code side.  Not
  all of these type errors are harmless, of course, but I don't see a
  way to deal with this except by telling GCC to be less picky.
