### ISSUE TITLE
Unlink the "scroll" behavior and the "alt+drag-n-drop" behavior, in settings

### ISSUE THREAD

**Issue by goldanorak** [phase1geo/Minder#603]
Hi, I'm writing this issue to separate more clearly several different suggestions concerning mouse movements and shortcuts, which I proposed in issue #562. In the solution you've added for issue #562, i think there's still one problem : two parameters behave in contradictory ways ... but remain apparently linked : the way Minder interprets scrolling, and the way Minder interprets "alt+drag-and-drop" (i'm using minder on a desktop computer). When I reverse the operation of one (with the new function added in settings), I reverse the other too. The problem, as I see it, is that in Minder, the designs of these two movements contradict each other. When scrolling is in "natural" mode (like normal web browser behavior, for example) ... alt+drag-n-drop behavior is counter-intuitive (on a desktop computer and from my point of view at least). So the only way, at present, to get back a natural "alt+drag-n-drop" behavior ... is to set Minder to have a counter-intuitive "scroll". So what I propose would be to unlink these two settings, and have 2 different options for each in the parameters. Thanks

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch.  I removed the natural scrolling preference option as I do not believe this is actually needed to solve the problem.  Scrolling will work according to your system's preference value.  Alt+drag/middle click will pan such that the canvas will follow the mouse cursor.
