### ISSUE TITLE
Button icons don't render when running under WSL

### ISSUE THREAD

**Issue by ChristopherHaws** [phase1geo/Minder#604]
Hey there! I have been using this app on linux and have been really liking it, but also wanted to use it in windows. I was able to get it working without any problem, however the only issue I have found is that button icons don't seem to render.

![image](https://github.com/phase1geo/Minder/assets/5934505/54e8411f-a3a6-4b74-b8cb-0a315cfc71ce)

I'm not sure if this is a simple fix or not. I would be happy to try any test builds if you need someone to test a fix.

Thanks!

**Comment by phase1geo** [comment]
Okay, so a few things here.  The New, Open, Save, Undo, Redo and Information icons are all built-in icons within elementary OS (and most other Linux distributions) in the "elementary" or "bicolor" icon theme set.  Not sure what icon theme is used in WSL, but obviously it's missing these icons for some reason.  I don't know if there is a way to get these installed in your environment, but that would fix those issues.

The two missing icons on the right side of the header bar are the "focus" and "sidebar" icons.  These are custom icons in Minder and are provided to the application as part of its own built-in resources.  I'm not sure why this wouldn't be working in your environment.  Did you build Minder within the Windows WSL environment?

**Comment by ChristopherHaws** [comment]
Thanks very much, that pointed me in the right direction!

I tried installing `elementary-icon-theme` and [elementary's fonts](https://github.com/elementary/fonts) (plus `sudo fc-cache -fv` to refresh the font cache) but that didn't seem to make a difference. I then installed the `gnome-font-viewer` and noticed some of its fonts were missing too, so I figured it was probably a gnome level issue, not a distro specific issue which let me to installing `gnome-icon-theme` which seems to have fixed most of the icons! From what I can tell, the only icon that seems to be missing is the `Show Property Sidebar` button.

![image](https://github.com/phase1geo/Minder/assets/5934505/f44cdae1-d83e-43d0-9afb-cb24a326d37d)


## Steps to install minder on Windows:
```shell
# Install WSL2 with Ubuntu in cmd or pwsh
wsl.exe --install -d ubuntu

# Install Minder in WSL
sudo apt update
sudo apt upgrade
sudo apt install minder
sudo apt install gnome-icon-theme
```

Minder should now be installed and can be opened from WSL with `com.github.phase1geo.minder` or from Windows using the app shortcut in the start menu:
![image](https://github.com/phase1geo/Minder/assets/5934505/69e0cb99-b801-48f0-846b-29a63ef6ae75)
