### ISSUE TITLE
Issues / Comments

### ISSUE THREAD

**Issue by gibranlp** [phase1geo/Minder#61]
Hi,

I have a few issues / comments / suggestions.

Whenever i change the style for all current nodes, when i make a new node, the style go back to its defaults, making that new node with default style(including everything, font, branch, link options, node options) different from all the rest of nodes.

There should  be a way to import other .minder files, in case you want to merge a few maps, which is what im trying to do now, instead of making them again.

Cheers!, Great program, love it.

**Comment by phase1geo** [comment]
I believe that the styling issue is a bug at this point. I will look 
into it soon and get a fix checked in which will be generally available 
in the next release.

As for minder file "merging", I'll have to think about how to best 
accomplish this as this functionality does not currently exist. I do 
have plans to add tab support to a minder window that will allow the 
editing of more than one mindmap in a window, so doing something like 
merging an existing mindmap would basically just be a copy/paste 
operation within the application between the two tabs. I could also 
look into providing copy/paste support between two Minder windows, if 
GTK supports interprocess communication. Of course, I could also add an 
import feature just as you suggest.

I appreciate the feedback!

Regards,
Trevor

**Comment by gibranlp** [comment]
Another awesome thing would be if you could draw freely or have some predefined shapes to highlight some nodes, maybe draw lines to "link" or jus to show some nodes togheter like an extra layer, i wish i knew how to code to help you out.

**Comment by phase1geo** [comment]
That feature request is already on my list. It won’t be available in the next release, but should show up soon after that.

**Comment by phase1geo** [comment]
After reviewing this issue, I believe that both the styling issue and adding support for copying/pasting between Minder windows as added to the 1.3 release. I have noted the feature request for visually grouping nodes in my feature tracker, so I'm going to close this issue.
