### ISSUE TITLE
Flatpak version crashes on Opensuse Tumbleweed Plasma

### ISSUE THREAD

**Issue by ultramekon** [phase1geo/Minder#610]
Installed OK but crashes when trying to run it:

Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
           PID: 21488 (com.github.phas)
           UID: 1000 (mpo)
           GID: 1000 (mpo)
        Signal: 11 (SEGV)
     Timestamp: Fri 2024-03-01 19:36:08 GMT (8min ago)
  Command Line: /usr/bin/com.github.phase1geo.minder
    Executable: /usr/bin/com.github.phase1geo.minder
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-com.github.phase1geo.minder-925662d8c5c843fd84c77ab13a907636.scope
          Unit: user@1000.service
     User Unit: app-com.github.phase1geo.minder-925662d8c5c843fd84c77ab13a907636.scope
         Slice: user-1000.slice
     Owner UID: 1000 (mpo)
       Boot ID: 99681c3e8d6342fe93975a8e4bc57e50
    Machine ID: be3eb50a6f5343f5ac2fffe46b623ea6
      Hostname: butthole
       Storage: /var/lib/systemd/coredump/core.com\x2egithub\x2ephas.1000.99681c3e8d6342fe93975a8e4bc57e50.21488.1709321768000000.zst (present)
  Size on Disk: 4.2M
       Message: Process 21488 (com.github.phas) of user 1000 dumped core.
                
                Stack trace of thread 21488:
                #0  0x00007fd92e97ff6c __strlen_evex (libc.so.6 + 0x17ff6c)
                #1  0x00005578bb92085e n/a (com.github.phase1geo.minder + 0x6785e)
                #2  0x00005578bb98a3bc n/a (com.github.phase1geo.minder + 0xd13bc)
                #3  0x00005578bb9883b2 n/a (com.github.phase1geo.minder + 0xcf3b2)
                #4  0x00005578bb953691 n/a (com.github.phase1geo.minder + 0x9a691)
                #5  0x00005578bb92c23e n/a (com.github.phase1geo.minder + 0x7323e)
                #6  0x00007fd92f29d334 n/a (libgtk-3.so.0 + 0x9d334)
                #7  0x00007fd92f5354a7 n/a (libgtk-3.so.0 + 0x3354a7)
                #8  0x00007fd92fe0a661 n/a (libgobject-2.0.so.0 + 0x17661)
                #9  0x00007fd92fe1e426 n/a (libgobject-2.0.so.0 + 0x2b426)
                #10 0x00007fd92fe24ce2 g_signal_emit_valist (libgobject-2.0.so.0 + 0x31ce2)
                #11 0x00007fd92fe24d8f g_signal_emit (libgobject-2.0.so.0 + 0x31d8f)
                #12 0x00007fd92f545f32 n/a (libgtk-3.so.0 + 0x345f32)
                #13 0x00007fd92f3199a1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1199a1)
                #14 0x00007fd92f319aad n/a (libgtk-3.so.0 + 0x119aad)
                #15 0x00007fd92f545e1c n/a (libgtk-3.so.0 + 0x345e1c)
                #16 0x00007fd92f3199a1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1199a1)
                #17 0x00007fd92f319aad n/a (libgtk-3.so.0 + 0x119aad)
                #18 0x00007fd92f37ae3a n/a (libgtk-3.so.0 + 0x17ae3a)
                #19 0x00007fd92f545e1c n/a (libgtk-3.so.0 + 0x345e1c)
                #20 0x00007fd92f3199a1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1199a1)
                #21 0x00007fd92f41db50 n/a (libgtk-3.so.0 + 0x21db50)
                #22 0x00007fd92f31a25d n/a (libgtk-3.so.0 + 0x11a25d)
                #23 0x00007fd92f32c444 n/a (libgtk-3.so.0 + 0x12c444)
                #24 0x00007fd92f2d2976 n/a (libgtk-3.so.0 + 0xd2976)
                #25 0x00007fd92f32c444 n/a (libgtk-3.so.0 + 0x12c444)
                #26 0x00007fd92f41db9c n/a (libgtk-3.so.0 + 0x21db9c)
                #27 0x00007fd92f545e1c n/a (libgtk-3.so.0 + 0x345e1c)
                #28 0x00007fd92f3199a1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1199a1)
                #29 0x00007fd92f319aad n/a (libgtk-3.so.0 + 0x119aad)
                #30 0x00007fd92f37ae3a n/a (libgtk-3.so.0 + 0x17ae3a)
                #31 0x00007fd92f2a2068 n/a (libgtk-3.so.0 + 0xa2068)
                #32 0x00007fd92f5353bd n/a (libgtk-3.so.0 + 0x3353bd)
                #33 0x00007fd92fe0a468 g_closure_invoke (libgobject-2.0.so.0 + 0x17468)
                #34 0x00007fd92fe1dcb8 n/a (libgobject-2.0.so.0 + 0x2acb8)
                #35 0x00007fd92fe1e86a n/a (libgobject-2.0.so.0 + 0x2b86a)
                #36 0x00007fd92fe24ce2 g_signal_emit_valist (libgobject-2.0.so.0 + 0x31ce2)
                #37 0x00007fd92fe24d8f g_signal_emit (libgobject-2.0.so.0 + 0x31d8f)
                #38 0x00007fd92f545f32 n/a (libgtk-3.so.0 + 0x345f32)
                #39 0x00007fd92f3199a1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1199a1)
                #40 0x00007fd92f42f06a n/a (libgtk-3.so.0 + 0x22f06a)
                #41 0x00007fd92f31a25d n/a (libgtk-3.so.0 + 0x11a25d)
                #42 0x00007fd92f32c444 n/a (libgtk-3.so.0 + 0x12c444)
                #43 0x00007fd92f427511 n/a (libgtk-3.so.0 + 0x227511)
                #44 0x00007fd92f545e1c n/a (libgtk-3.so.0 + 0x345e1c)
                #45 0x00007fd92f3199a1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1199a1)
                #46 0x00007fd92f319aad n/a (libgtk-3.so.0 + 0x119aad)
                #47 0x00007fd92f2c9c8d n/a (libgtk-3.so.0 + 0xc9c8d)
                #48 0x00007fd92f31a25d n/a (libgtk-3.so.0 + 0x11a25d)
                #49 0x00007fd92f32c444 n/a (libgtk-3.so.0 + 0x12c444)
                #50 0x00007fd92f2ca1b1 n/a (libgtk-3.so.0 + 0xca1b1)
                #51 0x00007fd92f545e1c n/a (libgtk-3.so.0 + 0x345e1c)
                #52 0x00007fd92f3199a1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1199a1)
                #53 0x00007fd92eb8bcfc n/a (libhandy-1.so.0 + 0x59cfc)
                #54 0x00007fd92f545e1c n/a (libgtk-3.so.0 + 0x345e1c)
                #55 0x00007fd92f3199a1 gtk_container_propagate_draw (libgtk-3.so.0 + 0x1199a1)
                #56 0x00007fd92eb99f89 n/a (libhandy-1.so.0 + 0x67f89)
                #57 0x00007fd92f545e1c n/a (libgtk-3.so.0 + 0x345e1c)
                #58 0x00007fd92f54ade0 n/a (libgtk-3.so.0 + 0x34ade0)
                #59 0x00007fd92f3f940e gtk_main_do_event (libgtk-3.so.0 + 0x1f940e)
                #60 0x00007fd92f13e267 n/a (libgdk-3.so.0 + 0x39267)
                #61 0x00007fd92f14f5e9 n/a (libgdk-3.so.0 + 0x4a5e9)
                #62 0x00007fd92f1538d6 n/a (libgdk-3.so.0 + 0x4e8d6)
                #63 0x00007fd92f153adc n/a (libgdk-3.so.0 + 0x4eadc)
                
                Stack trace of thread 21490:
                #0  0x00007fd92e911bcd syscall (libc.so.6 + 0x111bcd)
                #1  0x00007fd92fd62d40 g_cond_wait (libglib-2.0.so.0 + 0xb7d40)
                #2  0x00007fd92fcd303b n/a (libglib-2.0.so.0 + 0x2803b)
                #3  0x00007fd92fd35ae2 n/a (libglib-2.0.so.0 + 0x8aae2)
                #4  0x00007fd92fd3549e n/a (libglib-2.0.so.0 + 0x8a49e)
                #5  0x00007fd92e892bb2 start_thread (libc.so.6 + 0x92bb2)
                #6  0x00007fd92e91400c __clone3 (libc.so.6 + 0x11400c)
                
                Stack trace of thread 21491:
                #0  0x00007fd92e90578f __poll (libc.so.6 + 0x10578f)
                #1  0x00007fd92fd08aff n/a (libglib-2.0.so.0 + 0x5daff)
                #2  0x00007fd92fd0920c g_main_context_iteration (libglib-2.0.so.0 + 0x5e20c)
                #3  0x00007fd92fd09251 n/a (libglib-2.0.so.0 + 0x5e251)
                #4  0x00007fd92fd3549e n/a (libglib-2.0.so.0 + 0x8a49e)
                #5  0x00007fd92e892bb2 start_thread (libc.so.6 + 0x92bb2)
                #6  0x00007fd92e91400c __clone3 (libc.so.6 + 0x11400c)
                
                Stack trace of thread 21493:
                #0  0x00007fd92e90578f __poll (libc.so.6 + 0x10578f)
                #1  0x00007fd92fd08aff n/a (libglib-2.0.so.0 + 0x5daff)
                #2  0x00007fd92fd0920c g_main_context_iteration (libglib-2.0.so.0 + 0x5e20c)
                #3  0x00007fd92d03c97d n/a (libdconfsettings.so + 0x697d)
                #4  0x00007fd92fd3549e n/a (libglib-2.0.so.0 + 0x8a49e)
                #5  0x00007fd92e892bb2 start_thread (libc.so.6 + 0x92bb2)
                #6  0x00007fd92e91400c __clone3 (libc.so.6 + 0x11400c)
                
                Stack trace of thread 21510:
                #0  0x00007fd92e90578f __poll (libc.so.6 + 0x10578f)
                #1  0x00007fd92a95de71 n/a (libpulse.so.0 + 0x33e71)
                #2  0x00007fd92a947854 pa_mainloop_poll (libpulse.so.0 + 0x1d854)
                #3  0x00007fd92a9520d6 pa_mainloop_iterate (libpulse.so.0 + 0x280d6)
                #4  0x00007fd92a952180 pa_mainloop_run (libpulse.so.0 + 0x28180)
                #5  0x00007fd92a961e19 n/a (libpulse.so.0 + 0x37e19)
                #6  0x00007fd92a8ff89f n/a (libpulsecommon-17.0.so + 0x5d89f)
                #7  0x00007fd92e892bb2 start_thread (libc.so.6 + 0x92bb2)
                #8  0x00007fd92e91400c __clone3 (libc.so.6 + 0x11400c)
                
                Stack trace of thread 21492:
                #0  0x00007fd92e90578f __poll (libc.so.6 + 0x10578f)
                #1  0x00007fd92fd08aff n/a (libglib-2.0.so.0 + 0x5daff)
                #2  0x00007fd92fd0942f g_main_loop_run (libglib-2.0.so.0 + 0x5e42f)
                #3  0x00007fd92efd29f6 n/a (libgio-2.0.so.0 + 0x1259f6)
                #4  0x00007fd92fd3549e n/a (libglib-2.0.so.0 + 0x8a49e)
                #5  0x00007fd92e892bb2 start_thread (libc.so.6 + 0x92bb2)
                #6  0x00007fd92e91400c __clone3 (libc.so.6 + 0x11400c)
                ELF object binary architecture: AMD x86-64

**Comment by phase1geo** [comment]
Is Minder installed from Flatpak on this system or some other way?  Unfortunately, the stack trace that is provided her lacks meaningful symbols to help me understand where in the code things are going wrong.

**Comment by ultramekon** [comment]
Hi, I've since rebuilt my laptop with Tumbleweed and Plasma 6 and it's
working now thanks.
