### ISSUE TITLE
Why is Markdown colored in notes?

### ISSUE THREAD

**Issue by ScriptlessWeek** [phase1geo/Minder#616]
![Screenshot at 2024-04-19 08-10-35](https://github.com/phase1geo/Minder/assets/155108629/3f13ece1-db63-4be0-b48f-2b77ca76e8a4)

For some reason it's all colored and I can't figure out how to fix it. I'm not sure if this is a bug or something else on my side. I'm using Linux Mint 21.3 and my wm is xfwm 4.18, not sure if these could it effect it or not. I'm also using Minder 1.16.4 from Flatpak.

**Comment by phase1geo** [comment]
Minder applies syntax highlighting for notes.  It is not considered a bug and there isn't a way to disable it.

**Comment by ScriptlessWeek** [comment]
Thanks for answering my question. I suppose I will just avoid using markdown in notes for the time being.

Thanks for making this software by the way. There aren't a lot of simple mind map tools out there so it is greatly appreciated.

**Comment by phase1geo** [comment]
I will go ahead and make this issue a request for a new feature -- the ability to not highlight Markdown text.  The only exception is that I am going to underline links and node links within the note since the user can click on these links within the note to open them so having a visual indicator that this can be done is required.

**Comment by phase1geo** [comment]
I have committed a change to the master branch that provides a new preferences option that will allow the user affect the colorization of the notes fields.  I have also adjusted the blue color used to improve readability in dark modes.  Feel free to grab the latest code and build it on your system to test it out.

**Comment by ScriptlessWeek** [comment]
Awesome, really appreciated.

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes.
