### ISSUE TITLE
Feature Request: Provide Windows binaries

### ISSUE THREAD

**Issue by Beutlin** [phase1geo/Minder#62]
Please also release a Windows version of Minder.

**Comment by phase1geo** [comment]
I have no idea how this would be accomplished short of rewriting a Windows-specific version of Minder. Minder is coded in Vala, has Gtk+ bindings, and relies on a Linux filesystem.  If you or anyone else know of a way to migrate the existing project to work in Windows, I would be willing to integrate pull requests, but I am not planning on doing this work.

**Comment by Fatih20** [comment]
You shouldn't focus to this at all. Your effort are better invested at new features instead of refactoring the whole code to suit Windows, which, by the way, are less likely to donate compared to eOS AND gives less motivation for people to switch to eOS. It's just not worth it.

**Comment by phase1geo** [comment]
Agreed. I did not assign this issue to myself.

**Comment by phase1geo** [comment]
Closing out this issue as it appears no one wants to take on this task.
