### ISSUE TITLE
Crash when trying to add a new node

### ISSUE THREAD

**Issue by meyou69** [phase1geo/Minder#620]
When trying to add another node to the mind map, the application crashes immediately after I press the "Insert" button. It seems to be due to a SIGSEGV signal.

I'm on Fedora 40, the KDE Plasma spin.

The program was installed via Flathub and it's at version 1.16.4.

Here's the output of coredumpctl:

alex@ultimate-lenovo-laptop:~$ coredumpctl dump 30002
           PID: 30002 (com.github.phas)
           UID: 1000 (alex)
           GID: 1000 (alex)
        Signal: 11 (SEGV)
     Timestamp: Sun 2024-05-26 01:37:14 EEST (9min ago)
  Command Line: com.github.phase1geo.minder
    Executable: /app/bin/com.github.phase1geo.minder
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-com.github.phase1geo.minder-29982.scope
          Unit: user@1000.service
     User Unit: app-flatpak-com.github.phase1geo.minder-29982.scope
         Slice: user-1000.slice
     Owner UID: 1000 (alex)
       Boot ID: 7f24c8a63fec48aeb7e5bbc7bdb7bf14
    Machine ID: 63a76b76659c4b0fba70489b6ddccc0a
      Hostname: ultimate-lenovo-laptop
       Storage: /var/lib/systemd/coredump/core.com\x2egithub\x2ephas.1000.7f24c8a63fec48aeb7e5bbc7bdb7bf14.30002.1716676634000000.zst (present)
  Size on Disk: 4.6M
       Message: Process 30002 (com.github.phas) of user 1000 dumped core.
                
                Stack trace of thread 2:
                #0  0x0000555aa8a43939 n/a (/app/bin/com.github.phase1geo.minder + 0xdd939)
                #1  0x0000555aa8a447ce n/a (/app/bin/com.github.phase1geo.minder + 0xde7ce)
                #2  0x00007fe10dcbed92 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x14d92)
                #3  0x00007fe10dced768 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x43768)
                #4  0x00007fe10dcdd316 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x33316)
                #5  0x00007fe10dcdd5b3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x335b3)
                #6  0x00007fe10dcbed92 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x14d92)
                #7  0x00007fe10dced768 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x43768)
                #8  0x00007fe10dcdd316 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x33316)
                #9  0x00007fe10dcdd5b3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x335b3)
                #10 0x0000555aa8a2c83a n/a (/app/bin/com.github.phase1geo.minder + 0xc683a)
                #11 0x0000555aa8a27b3c n/a (/app/bin/com.github.phase1geo.minder + 0xc1b3c)
                #12 0x00007fe10dcdd480 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x33480)
                #13 0x00007fe10dcdd5b3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x335b3)
                #14 0x00007fe10d0ebea8 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0xebea8)
                #15 0x00007fe10dcdd480 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x33480)
                #16 0x00007fe10dcdd5b3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x335b3)
                #17 0x00007fe10d0ebc10 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0xebc10)
                #18 0x00007fe10d0a6c23 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0xa6c23)
                #19 0x00007fe10dcdd480 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x33480)
                #20 0x00007fe10dcdd5b3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x335b3)
                #21 0x00007fe10d1d2ec3 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x1d2ec3)
                #22 0x00007fe10dcc34aa n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x194aa)
                #23 0x00007fe10dcdd480 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x33480)
                #24 0x00007fe10dcdd5b3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x335b3)
                #25 0x00007fe10d1c449c n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x1c449c)
                #26 0x00007fe10d1cdf8b n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x1cdf8b)
                #27 0x00007fe10d1d3b9a n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x1d3b9a)
                #28 0x00007fe10d18a017 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x18a017)
                #29 0x00007fe10d393bd8 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x393bd8)
                #30 0x00007fe10d0a5337 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0xa5337)
                #31 0x00007fe10dcdd480 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x33480)
                #32 0x00007fe10dcdd5b3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x335b3)
                #33 0x00007fe10d39d164 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x39d164)
                #34 0x00007fe10d221d20 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x221d20)
                #35 0x00007fe10d222b49 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x222b49)
                #36 0x00007fe10cf493b3 n/a (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0.2409.32 + 0x453b3)
                #37 0x00007fe10cf7516e n/a (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0.2409.32 + 0x7116e)
                #38 0x00007fe10dbc9d71 n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4 + 0x59d71)
                #39 0x00007fe10dc20a18 n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4 + 0xb0a18)
                #40 0x00007fe10dbc92af n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4 + 0x592af)
                #41 0x00007fe10d21e4b5 n/a (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2409.32 + 0x21e4b5)
                #42 0x0000555aa898bab8 n/a (/app/bin/com.github.phase1geo.minder + 0x25ab8)
                #43 0x00007fe10dcdd480 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x33480)
                #44 0x00007fe10dcdd5b3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4 + 0x335b3)
                #45 0x00007fe10ce19128 n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7200.4 + 0xec128)
                #46 0x00007fe10ce1931b n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7200.4 + 0xec31b)
                #47 0x0000555aa898c9d8 n/a (/app/bin/com.github.phase1geo.minder + 0x269d8)
                #48 0x00007fe10c62958a n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2958a)
                #49 0x00007fe10c62964b n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2964b)
                #50 0x0000555aa8989d35 n/a (/app/bin/com.github.phase1geo.minder + 0x23d35)
                ELF object binary architecture: AMD x86-64

**Comment by meyou69** [comment]
[sample.webm](https://github.com/phase1geo/Minder/assets/92801613/0b839433-d98e-4e23-91eb-802fb93439d5)

There you go. As you can see, immediately after I click on the "Insert" button, it crashes

**Comment by phase1geo** [comment]
Thanks for the extra info. I can replicate this issue and should have a fix available shortly.

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch.

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes.
