### ISSUE TITLE
Shortcuts Cheatsheet doesn't fit the screen

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#623]
On 2560x1440 (14"), the Shortcuts Cheatsheet window doesn't fit the screen at all, I need to Meta+drag up to see the pagination buttons.

![image](https://github.com/phase1geo/Minder/assets/57467/a86526c8-cd6b-4fa1-850a-340cf8794554)

**Comment by phase1geo** [comment]
I have attempted to improve things by moving the "Center In View" and "Place Into View" shortcuts into their own "View" group.  This should shorten the window a bit in height, but let me know if it is still too large.  It seems weird to me that the window would grow itself beyond the screen limits as the shortcuts window is a standard Gtk shortcut window widget, but what do I know?

**Comment by phase1geo** [comment]
The change has been committed to the main branch if you want to test it out.

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes.
