### ISSUE TITLE
command-line export not working when an instance is already running

### ISSUE THREAD

**Issue by eudoxos** [phase1geo/Minder#624]
I am using the command-line interface to automate export of mindmaps via `com.github.phase1geo.minder map.minder --export=markdown map.md`. This only works when an instance of Minder (=GUI) is not running. Otherwise it re-uses the running window, only opens the map (or focuses it if already opened), and ignores the `--export=markdown map.md` bit.

On a similar note, if no instance is running, the export briefly opens the GUI (thus cannot be run headless).

I much appreciate Minder, and I know development of anything is hard. So please take this just as a modest suggestion which would make my life easier.

**Comment by phase1geo** [comment]
I think I can make things better when running the command-line while the window is displayed.  I'm not sure what I can do about the headless bit, but I'll look into it.  This might not be a lot of effort to get this working as you need it to.

**Comment by phase1geo** [comment]
I have committed a change to the master branch which provides support for invoking Minder commands while the application is currently running.  This fix will also fix issues where a Minder process can be left running when the application is closed.

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes.
