### ISSUE TITLE
Moving nodes using keyboard instead drag&drop: child node → parent node

### ISSUE THREAD

**Issue by solrafa** [phase1geo/Minder#627]
Hi, 
I'd like to move nodes using keyboard instead drag&drop.

Now I can move a sibling up/down using ALT+up or ALT+down.

It will be great if I could move a child node to previous level, becoming it as a parent note (an uncle node).

And it will good if I could select one or more nodes using SHIFT+up/down and move them with ALT+up/down or ALT+right/left.

Thanks for make our brainstorming better,
Rafael

**Comment by phase1geo** [comment]
This is a good suggestion.

**Comment by phase1geo** [comment]
I have pushed a change to the master branch which redefines an existing keyboard shortcut and adds a new keyboard shortcut to replace that existing functionality.

- Alt + Direction of parent node = moves the currently selected node to be a sibling of its parent (new requested functionality)
- Alt + Direction of child nodes = moves the children of the currently selected node to be siblings of the node (previously existed but used Alt + Direction of parent node).

I think that this new combination of keyboard shortcuts should be intuitive and satisfies the new request.

The request for multiple selection move may need to hold off as I don't currently have support for moving multiply selected nodes at the moment.  This is on the list so once that functionality exists I can add keyboard shortcuts.

**Comment by solrafa** [comment]
Thanks a lot! 
I had sent my idea merely as a suggestion for a wish list. I'm happy the idea could potentially help more people.

**Comment by phase1geo** [comment]
Thank you for a great suggestion!

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes.
