### ISSUE TITLE
Nodes get added on top of each other

### ISSUE THREAD

**Issue by jeancf** [phase1geo/Minder#63]
I am on Manjaro Linux and I am just trying Minder for the first time.

All nodes get added (using Tab from root or Return from existing child) in the same spot. Changing node layout has no effect.

![Screenshot_20190512_121337](https://user-images.githubusercontent.com/885845/57580873-81f61e00-74af-11e9-962e-63fdd4f121c0.png)

**Comment by phase1geo** [comment]
This problem has already been fixed in the "connect" branch.

If you want a known working version of Minder, I would suggest that you grab the latest released version instead of grabbing the code in the master branch.

**Comment by jeancf** [comment]
OK. I used the minder-git AUR package from Archlinux that points to the master branch.

I think it is common practice to merge development branches into master for release. This enables automated tools (like Archlinux AUR git packages) to get updated automatically with the latest releases.

**Comment by phase1geo** [comment]
I have merged the fix into master.

**Comment by jeancf** [comment]
Great, thanks!
