### ISSUE TITLE
Left/right keyboard navigation not working correctly

### ISSUE THREAD

**Issue by tomatic** [phase1geo/Minder#630]
Navigating left or right from the current node doesn't work correctly. In the attached screen recording, I'm repeatedly pressing the right arrow, but Minder is only jumping between the main and the left node. Same happens when using the `L` key.

The only way I can navigate to the right node is by first going to the left one and then pressing `N` or `P`.

Minder v1.16.4 on Kubuntu 24.04.

https://github.com/user-attachments/assets/2187fd59-676a-49bf-946d-7d568b8ed474

**Comment by phase1geo** [comment]
I have committed a change to the main branch which fixes this behavior.  Up, down, left and right should work more intuitively for main (root) nodes within the mindmap when their layout is horizontal or vertical in nature.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes.
