### ISSUE TITLE
Ctrl + Backspace selects entire node text in some instances

### ISSUE THREAD

**Issue by tomatic** [phase1geo/Minder#631]
When creating a new node and typing in text, pressing Ctrl + Backspace to delete the previous word selected the entire node text. It only seems to happen on initial node creation and editing. If I edit an existing node, it behaves normally.

Minder 1.16.4 on Kubuntu 24.04.

https://github.com/user-attachments/assets/07da3eb2-03fc-459b-a863-df3d5fce88ec

**Comment by phase1geo** [comment]
I have fixed this issue in the main branch.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes.
