### ISSUE TITLE
Change layout on sub-nodes (multiple times)

### ISSUE THREAD

**Issue by dishorned** [phase1geo/Minder#634]
Hey Guys,

I haven't found a feature request for this, nor have I found a way to do so. Currently it seems only be possible to set a layout for the whole mind map like creating all nodes to the right. If you want to create a process with 20 sub-nodes (steps), you cannot create a screenshot and paste it somewhere else, as the image will be very flat but ultra-wide.

So it would be nice, if you can change the layout on sub-nodes like having 3 nodes to the right, than 2 nodes down and 3 nodes to the left. I know this is a mind-mapping software and not intended to create complex process-diagrams, but with slight changes or feature improvements this could be a go-to software for a lot of scenarios.

Thanks a lot and best regards

**Comment by phase1geo** [comment]
You can always change the layout to manual and then you can put the sub nodes wherever you would like.

**Comment by dishorned** [comment]
Maybe i was not clear enough. You are right, it's possible by manually arranging them, but that cost a lot of time if you want it to look nice. As I said, I know this is not a process-diagram software, but that may help others as well, to get rid of a second software to use. Especially the one I use normally for creating such diagrams isn't able to easily add a new parent node which is very anoing when adding a step inbetween. This is something you software is already capable of.

So it would be nice, if you hover over a node to can click on a little symbol to create a new node left/right/above/below like in other software or can click on a node and select a new node layout for all sub-nodes, kind of a inherit structure/hierarchy.

I know there are a lot open tasks, but maybe this could be something to keep in mind.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by dishorned** [comment]
> to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html) maybe this will solve your problem.

Don't open this link. It's a Phishing site trying you to execute Powershell commands!

**Comment by phase1geo** [comment]
I have deleted the post and reported this content to GitHub.

**Comment by phase1geo** [comment]
I have spent some time thinking about this request.  I'll leave it as a future feature request, but it got me to thinking about creating a new feature called "sequences".  If a node is marked as a sequence, its child nodes will be drawn such that the first child node will link to the parent, but all remaining child nodes will look like they are linked to the previous sibling node.  Additionally, sequenced nodes will (perhaps optionally) display a sequence number that automatically be assigned to the child nodes and will be automatically updated if child nodes are rearranged, removed, inserted into, etc.

This feature enhancement might be an even better way to display list of "steps" associated with a node and keep the mindmap more concise from a drawing perspective, giving you closer to what you want.

Again, I'm not saying that the feature I have outlined here negates a user's need to specify directions to add a child node to, but it is a rather simple solution (from Minder's node layout engine perspective) that might help to provide you a better way to display this type of information.  I have this feature partially implemented in a branch at present and it looks pretty good so far.

**Comment by dishorned** [comment]
I can not fully imagine how it will look like but I am excited to see it. My suggestion was just the way I would implement it without the knowledge of the code and how it works in the back. May your solution is even better.

Let me know, when it's done and released.

**Comment by phase1geo** [comment]
I have the implementation of sequences committed to the master branch.  This will be available in the 1.17.0 upcoming stable release.

**Comment by dishorned** [comment]
Nice! I will test it as soon as the flatpak is available via flathub.

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes for sequences.  I'm going to close this issue for now.  The request for different layouts can still be considered an open feature request, if needed.
