### ISSUE TITLE
Non-canonical freedesktop path for icon file

### ISSUE THREAD

**Issue by tim77** [phase1geo/Minder#635]
Look like the proper place for Minder icon file is `scalable` folder since it in SVG format. 

`icons/hicolor/128x128/apps/com.github.phase1geo.minder.svg`
to
`icons/hicolor/scalable/apps/com.github.phase1geo.minder.svg`

Can we try this in order to fix https://github.com/flathub/com.github.phase1geo.minder/pull/40?

```
"errors": [
    "non-png-icon-in-hicolor-size-folder"

    "non-png-icon-in-hicolor-size-folder: ['/tmp/tmp57ti8txx/icons/hicolor/128x128/apps/com.github.phase1geo.minder.svg', '/tmp/tmp57ti8txx/icons/hicolor/24x24/apps/com.github.phase1geo.minder.svg', '/tmp/tmp57ti8txx/icons/hicolor/64x64/apps/com.github.phase1geo.minder.svg', '/tmp/tmp57ti8txx/icons/hicolor/32x32/apps/com.github.phase1geo.minder.svg', '/tmp/tmp57ti8txx/icons/hicolor/48x48/apps/com.github.phase1geo.minder.svg', '/tmp/tmp57ti8txx/icons/hicolor/16x16/apps/com.github.phase1geo.minder.svg']"
    
"message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
```

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch. It will be generally available in the upcoming 1.17 release.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by phase1geo** [comment]
Release 1.17.0 version contains the required changes.
