### ISSUE TITLE
Can not export new Version

### ISSUE THREAD

**Issue by gibranlp** [phase1geo/Minder#66]
Hi,

I just updated to the last version of Minder and i don't seem to be able to export any map.

I have tried to export to every option (bmp, png, pdf, etc) and none seem to work.

I am using Arch, i am far from my other computer on Elementary and i have not tried there, will update from that OS later tonight.

Cheers.

**Comment by gibranlp** [comment]
I just tried on ElementaryOS with minder 1.3.0 and the same i can export.
 Is this a bug or did i do something wrong?

**Comment by phase1geo** [comment]
I believe that I'm seeing the same thing on my end. The export window pops up but when I hit export, no output file is created. Does that match your experience?

I'll look into this right away.

**Comment by gibranlp** [comment]
Yes,

The window closes and the task appears to be completed correctly, but no files is created.

Yes, Cheers man!

**Comment by phase1geo** [comment]
This issue has been fixed in the master branch and will be available in the 1.3.1 release.

**Comment by gibranlp** [comment]
Awesome, thanks man!

**Comment by metal3d** [comment]
And could you please tell us when this version will be available ?

**Comment by metal3d** [comment]
EDIT: ok the version is already here, this is fedora version that is not already present

**Comment by metal3d** [comment]
FYI, 1.3.1 is available in updates-testing for Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1718527

```
# install
sudo dnf install minder --enablerepo=updates-testing
# or update
sudo dnf update minder --enablerepo=updates-testing
```

**Comment by metal3d** [comment]
Export is working, but markdown (at least) are not overwritten if already exported.

**Comment by phase1geo** [comment]
Closing bug now that 1.4.0 is in the release pipeline.
