### ISSUE TITLE
Freezes after update

### ISSUE THREAD

**Issue by hus3h** [phase1geo/Minder#72]
First of all thanks for this great app. I was so glad I found it.

After the latest update I noticed that Minder freezes sometimes. This freeze seems to be random (it just happened as I'm writing this issue and Minder is in the background). When it happens I can't move/resize/close the whole Minder window, so I have to force stop Minder (end process).

This light grey box on the right appears when it happens, and it seems to appear be on the top of all the programs, not just minder. It'll disappear when I end Minder's process. Note that the box can't be resized, clicked.

![Screenshot from 2019-06-19 12-07-26](https://user-images.githubusercontent.com/39054982/59754602-144bc780-928f-11e9-9e52-90dbf3ebc984.png)

Another small freeze happens when I select a node, and double tap with my laptop's touchpad (that's a right click). This freeze lasts for few seconds and it seems switching to another program then switching back to Minder stops it. Right clicking with a mouse doesn't do that so I'm not sure what could be the problem.

I have Minder 1.3.1 on Fedora 29 (packages are up-to-date). Installed using dnf install.

**Comment by phase1geo** [comment]
Can you reproduce the problem and at the point when it freezes, use a terminal to connect gdb to the hung process? If you can do that, I’m interested in knowing the stack trace at the point when the application freezes. I have never seen Minder freeze up, so I will need your assistance in tracking down this issue.

**Comment by hus3h** [comment]
Sure,

I started Minder from terminal to check for any debug messages and found out that in both cases of freezing, I'm getting this message when I move the mouse in the Minder window:

![Screenshot from 2019-06-20 19-48-05](https://user-images.githubusercontent.com/39054982/59867082-dc7b7780-9395-11e9-8f8a-c35bcde3d186.png)

```
(com.github.phase1geo.minder:21105): Gtk-CRITICAL **: 19:52:14.384: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
```

As for gdb, I don't have previous experience with it so please tell me if there's a specific command you're interested in.

Here's the output of ``bt`` command (after it froze):
```
#0  0x00007fab811af461 in poll () from /lib64/libc.so.6
#1  0x00007fab822cd3a6 in ?? () from /lib64/libglib-2.0.so.0
#2  0x00007fab822cd762 in g_main_loop_run () from /lib64/libglib-2.0.so.0
#3  0x00007fab81af2c5d in gtk_main () from /lib64/libgtk-3.so.0
#4  0x000055d0259da0ae in ?? ()
#5  0x00007fab823af3dd in g_closure_invoke () from /lib64/libgobject-2.0.so.0
#6  0x00007fab823c21b4 in ?? () from /lib64/libgobject-2.0.so.0
#7  0x00007fab823cbaaa in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#8  0x00007fab823cc0a3 in g_signal_emit () from /lib64/libgobject-2.0.so.0
#9  0x00007fab8161cad8 in ?? () from /lib64/libgio-2.0.so.0
#10 0x00007fab8161cc8f in g_application_run () from /lib64/libgio-2.0.so.0
#11 0x000055d0259da5c4 in ?? ()
#12 0x00007fab810e1413 in __libc_start_main () from /lib64/libc.so.6
#13 0x000055d0259c322e in ?? ()
```

**Comment by phase1geo** [comment]
Hmmm. I'm not sure what to say about this. The stack trace that you are providing doesn't include any Minder code calls, so I don't think the issue with necessarily with Minder itself. I was able to successfully use the two-finger double tap on my laptop touchpad to bring up the contextual menu. I'm running the latest version of elementary OS with Gtk 3.22.30.

**Comment by ForlornWongraven** [comment]
I have the same issue on Fedora30.

com.github.phase1geo.minder

(com.github.phase1geo.minder:14580): GLib-GObject-WARNING **: 11:41:33.769: invalid cast from 'DrawArea' to 'GtkWindow'

(com.github.phase1geo.minder:14580): Gtk-CRITICAL **: 11:41:47.883: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(com.github.phase1geo.minder:14580): Gtk-CRITICAL **: 11:41:47.883: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(com.github.phase1geo.minder:14580): Gdk-CRITICAL **: 11:42:38.993: Window 0x55869aaff7d0 has not been made visible in GdkSeatGrabPrepareFunc

(com.github.phase1geo.minder:14580): Gdk-CRITICAL **: 11:42:38.994: Window 0x55869aaff7d0 has not been made visible in GdkSeatGrabPrepareFunc

The app stops working after a random time with those "GdkSeatGrabPrepareFunc" errors.

**Comment by phase1geo** [comment]
With the latest version of Minder (1.7.2), does anyone know if this problem still occurs?

**Comment by hus3h** [comment]
I upgraded Fedora since then so I'm not sure if it still occurs with the older versions, now I'm running Fedora 31 and I'm not having any problems. I think it's safe to close the issue until it happens again. Thanks for your efforts.

**Comment by phase1geo** [comment]
Closing bug without an official fix as it may be out of date.
