### ISSUE TITLE
Automatic node layout issue in 1.4.0

### ISSUE THREAD

**Issue by phase1geo** [phase1geo/Minder#76]
elementary os Juno
The new version only work in manual mode :(

![minder](https://user-images.githubusercontent.com/8943997/61190550-54c31900-a674-11e9-995d-4b14defca086.gif)

_Originally posted by @mauriaguilar in https://github.com/phase1geo/Minder/issues/23#issuecomment-511243409_

**Comment by phase1geo** [comment]
I am going to look into this issue right away as I'm able to easily reproduce this problem on my end as well.

**Comment by phase1geo** [comment]
I believe that this issue has been fixed in the development branch. I will be creating a new 1.4.1 release shortly.

**Comment by mauriaguilar** [comment]
yes, now works!
thanks!
