### ISSUE TITLE
Edit a mindmap created in one computer in another

### ISSUE THREAD

**Issue by nikus** [phase1geo/Minder#77]
Hello, I have a question and couldn't find the answer in the docs and I don't know if this is the right place to ask it.

I was trying to sync my mind maps on multiples computers using services like dropbox and I noticed that I cannot embed images into the .minder files, is that correct? Also when I add images, the program records the absolute path of the image in the system, making it difficult to have the same map on multiples computers.

Is there any workaround it or am I misunderstanding something?

**Comment by phase1geo** [comment]
Reviewing the code base, I believe that you are correct.  It does appear that the way Minder currently manages images, it would not work to view the same mind map on two different computers.  The Minder image manager does store the URI of the image (so if you drag and drop an image from the browser to a mind map, the URL of that image is stored).  However, it appears that Minder is only storing a local copy at the moment that the image is added to the mind map.  It does not appear that I am making any effort to download missing images if they are available.

I had thought about the idea of making Minder files essentially an archive containing both the XML and related images files; however, I have not completed that code to date.

If you want a quick and dirty "fix" for the issue, you can copy the contents of the ~/.local/share/minder/images directory from one machine to the other. I'm not implying that this an acceptable path forward, but it should get you by.

This is definitely an area that needs to be rethought and addressed in a simple, straightforward manner. I apologize for the inconvience in the meantime.

**Comment by phase1geo** [comment]
I have updated the development branch to add the ability to export a mindmap to a new "Portable Mindmap" format.  This new filetype is a single compressed archive file containing the .minder file plus all related image files.  This new .pminder file can be sent to a different filesystem and imported (like any other importable document format).  After being imported, the .minder file contents stored within the .pminder file will be extracted to the same directory that the .pminder file exists within and the related images are written to the ~/.local/share/minder/images directory where all other Minder images are stored and managed.

If the Minder file needs to be sent to another file system (or back to the original file system), the file will need to be re-exported.

**Comment by phase1geo** [comment]
This feature has been implemented in the 1.7.0 stable release.  Closing request.
