### ISSUE TITLE
Feature Request: Export to GraphML

### ISSUE THREAD

**Issue by dtzWill** [phase1geo/Minder#78]
I'd very much like to share what I've created in Minder with tools like Gephi or yEd-- and at least for yEd it looks like graphML would be best way to go there.

Is this something Minder could support or has plans to support?  Any known difficulties preventing adding export support (import is nice but :3))?

Regardless, is there anything an external party could help that would facilitate this (short of fully tackling it and submitting a PR)?

Thanks for the great tool, look forward to putting it to use among my other graph-manipulation tools!

**Comment by phase1geo** [comment]
Sounds like a reasonable request. I guess I could use your help in testing the Minder version that supports this feature when it is ready to be tested. I’ll update this issue when I have something for you to try.

**Comment by phase1geo** [comment]
I have the necessary changes to support exporting to yEd checked into the 'devel' git branch.  If you would be willing to build Minder from the latest files in that branch and verify that the yEd export feature works to your satisfaction, I would greatly appreciate that.

I'm not sure about providing Gephi export support at this point.

**Comment by dtzWill** [comment]
Excerpts from Trevor Williams's message of July 23, 2019 9:36 pm:
> I have the necessary changes to support exporting to yEd checked into the 'devel' git branch.  If you would be willing to build Minder from the latest files in that branch and verify that the yEd export feature works to your satisfaction, I would greatly appreciate that.

Built no problem, and successfully opened in yEd! Thank you!

> 
> I'm not sure about providing Gephi export support at this point.


yEd was my primary use case, I mostly mentioned Gephi as what I thought
would be "free" once a graphml exporter was added.

Looks like theme colors are exported as well, other than background I
believe but that's minor and much less important than getting the data
and its structure properly captured across tooling :).

Things look good, nothing particularly out-of-place
like text overflowing its node when it didn't previously.
Haven't attempted to push any particular edge cases, just the graphs
I've been working on.

LGTM!

Thanks for the quick turn-around!
