### ISSUE TITLE
Select multiple nodes

### ISSUE THREAD

**Issue by Fatih20** [phase1geo/Minder#80]
And the capability of playing around with it :

- Align
- Collectively modify node shapes, dash line, etc.

**Comment by phase1geo** [comment]
This feature request is already on the roadmap so it will be coming in a future release (although it won’t be in the 1.5 release). I will add node alignment to the list.

**Comment by Fatih20** [comment]
Thanks, that would be epic!

**Comment by phase1geo** [comment]
Multiple node selection support has been added, allowing for several bulk functions to be applied. However, the next release will not have support for node alignment (that functionality will be added in a later release).

**Comment by phase1geo** [comment]
Release 1.6.0 has been released with this change.
