### ISSUE TITLE
Search and sidebar button looks out of place

### ISSUE THREAD

**Issue by Fatih20** [phase1geo/Minder#83]
![Screenshot from 2019-08-03 15 32 23](https://user-images.githubusercontent.com/51940383/62409917-5f842480-b608-11e9-9e2f-5e721d348eb8.png)
In my opinion, they should be changed to a colored skeuomorphic icon as well. Any way to change that?

**Comment by phase1geo** [comment]
When I changed the header bar color to irs current color, the skeuomorphic search icon was hard to see. I can’t remember if the same was true for the sidebar button, but it might have been. I will contact the elementary OS folks to see if they have an opinion about this.

**Comment by Fatih20** [comment]
Would you want me to make a colored skeuomorphic icon for the sidebar?

**Comment by phase1geo** [comment]
I would certainly be interested!

**Comment by Fatih20** [comment]
https://drive.google.com/open?id=1XYeyZxVtakP4J6onvI-KQgyQ-bnm96WD Here's a simple one. What do you think?

**Comment by phase1geo** [comment]
Those looks really nice. Did you create them?

**Comment by Fatih20** [comment]
I took some icons from elementary icon set and then I modified them.

**Comment by phase1geo** [comment]
Okay, I have installed the new sidebar hide/show icons in the development branch and things look much better. I have gotten feedback from the elementary team about what to do about the search icon and they think that a modified search icon with better contrast. Is this something that you could help me improve as well? You do some really nice icon work.

**Comment by Fatih20** [comment]
Okay, I'll get to it. Thanks for the compliment.

**Comment by Fatih20** [comment]
I've updated the google drive folder with my design of the magnifying glass. Check it out!

**Comment by phase1geo** [comment]
The new search icon has been installed in the development branch.  Looks much better now.

**Comment by Fatih20** [comment]
Is both of the icon already installed? Don't forget to put me in the credit.

**Comment by phase1geo** [comment]
I have credited you in the git commit message for both icons and I will also credit your work in the release notes.

**Comment by Fatih20** [comment]
Thanks!
