### ISSUE TITLE
Move the theme and node layout option from sidebar to headerbar

### ISSUE THREAD

**Issue by Fatih20** [phase1geo/Minder#85]
Instead of having it in the sidebar, IMO, it's better to have them at the headerbar with a dropdown menu. I'll draw a mock-up of this. It also declutter the sidebar.

**Comment by phase1geo** [comment]
I want to limit adding items to the header to those that are only necessary. I have one or two features in mind that will require buttons in the header bar so I don't think that I want to move the layout/theme sidebar to the header bar.
