### ISSUE TITLE
Fill with Link Color has a bug

### ISSUE THREAD

**Issue by Fatih20** [phase1geo/Minder#86]
FWLC can only be enabled if the node has a closed shape. The problem here is that after I change the node's shape to a closed shape, I can't just apply FWLC. Instead, I'll need to deselect and then select the node again to enable FWLC.

**Comment by phase1geo** [comment]
I believe the right thing to do in this case is to disable the FWLC switch if the affected nodes cannot be filled in. I will work on a fix shortly.

**Comment by Fatih20** [comment]
I know that's how it's supposed to work. The bug is that FWLC can't be activated after I change the node border from the default none to the closed shapes. I would need to change the node > deselect > reselect > toggle FWLC. The bug here is that if I don't deselect and reselect, FWLC can't be activated despite the node already has a closed shape.

**Comment by phase1geo** [comment]
I have committed a fix to the development branch for this issue.  It will be generally available in the next release.
