### ISSUE TITLE
Add Org-mode export ?

### ISSUE THREAD

**Issue by bepolymathe** [phase1geo/Minder#87]
Hello,

Thank you very much for this pleasant, useful and functional software!

I write a lot of my texts in .org (Org-mode format) and then export them (especially in.odt). It would therefore be very useful to be able to export in this format (based on the Markdown model). 

If we look at the work you did for Markdown, we would probably have to change a little bit to get an "ExportOrg.vala"? Change something here (remplace "-" by "*") ? 

![image](https://user-images.githubusercontent.com/29939805/63941921-e643ea00-ca6c-11e9-90aa-dd15215afc41.png)

What do you think of that?

**Comment by phase1geo** [comment]
Would the only difference between "ExportOrg" and "ExportMarkdown" be this one character? If so, I can just change the character from a '-' to a '*'. Markdown editors treat either character in the same way.

**Comment by phase1geo** [comment]
I have created a new org-mode branch in Minder which has initial support for Org-Mode exporting built-in. If you would be willing to test this out and help me make improvements to it, I would be more than happy to work with you on it. I am an Emacs user and, as such, don't have working knowledge of Org-Mode. I only know about its formatting from the user manual.

**Comment by phase1geo** [comment]
@wi24rd Is your hear up above mean that you have tested out this feature by any chance? I'm just waiting to hear from someone who uses Org-Mode that the Minder export is basically working.

**Comment by phase1geo** [comment]
I'm going to consider this issue closed as I would like to get a new Minder version released to AppCenter ASAP. If there is a bug with the export, either re-open this issue or create a new issue.

**Comment by phase1geo** [comment]
This feature has been implemented in the 1.7.0 stable release.  Closing request.  If there is an issue with the implementation, feel free to open a new issue or reopen this one.
