### ISSUE TITLE
Change the default node

### ISSUE THREAD

**Issue by Fatih20** [phase1geo/Minder#89]
Normally, if you add a new node, it will have no border, 4 margin, 6 padding, etc. My suggestion is to be able to change this parameters for a new node that just has been added.

**Comment by phase1geo** [comment]
I think that this should be considered a bug. Minder does have support for remembering style changes for nodes at a given level. So I think that the current methodology just needs to be tweaked a bit to work better.

**Comment by phase1geo** [comment]
I have committed a fix to the development branch for this issue.  It will be generally available in the next release.
