### ISSUE TITLE
Add icons to node

### ISSUE THREAD

**Issue by phase1geo** [phase1geo/Minder#92]
We will want to add the ability to add icons/stickers to a node.  Currently, Minder can display an image and emoji, but more is requested here.

**Comment by phase1geo** [comment]
I'm not exactly sure where I am going to get the sticker icons from at this point.

**Comment by Fatih20** [comment]
What exactly does this mean? What help do you need?

**Comment by phase1geo** [comment]
This feature request is from a user that wants the option to add one (or possibly more) icons (or stickers) to a node. I know that other mind mapping tools provide a palette of various icons that can help provide more visual information to a node.

Examples of such icons might include:
- Star
- Checkmark
- Dollar sign
- Birthday cake
- Book
- Computer
- Gears
- Alarm clock
- Filing cabinet
- Warning sign
- Bug
- Target
- Calendar
- Fire
- Car
- Bell
- Bicycle
- Balloon
- Etc., etc.

Generally, the icons have a similar design aesthetic.

The help wanted label is meant to say that if this feature were to be implemented, I would need someone else to design a bevvy of sticker icons that we could make available through this feature. I'm not really an artist (such as yourself) so I don't want to take that part of the task on.

I asked the elementary OS community on slack if they knew if such a "sticker pack" like this exists, but I have not heard anything in the affirmative. The only suggestion is to use the emoji picker for this purpose which Minder already has support for.

I don't really know if this feature is necessary given the array of emojis that are available so I'm not really specifying that this feature is required. I'm just including it in the list of requested features.

**Comment by phase1geo** [comment]
I will say one more thing here that is relevant. We could potentially just use the Gtk.IconTheme.get_default() results; however, I the resulting list is pretty ad hoc, probably contains a lot of images that no one would use, and doesn't look cohesive when displayed together. A nicely curated list of available icons would be preferrable, in my opinion.

**Comment by Fatih20** [comment]
Sure, I can make the whole sticker. What size do you need it in?

**Comment by Fatih20** [comment]
Furthermore, can you add the code side so when I'm done, I would only need to put the icon in the folder you've set up.

**Comment by phase1geo** [comment]
Implementing this feature is not a priority for me at the moment; however, if you create icons you can just put them in a “stickers” subdirectory under the main “data” directory for now.

**Comment by phase1geo** [comment]
I’m thinking the icons shouldn’t need to be any larger than 32x32 pixels.

**Comment by phase1geo** [comment]
Perhaps even 24x24 would suffice.

**Comment by Fatih20** [comment]
Hmm, alright.

**Comment by phase1geo** [comment]
I'm thinking about dropping support for this feature since creating and maintaining a sticker pack goes beyond the scope of this project. Hopefully, the use of emoji or images can take the place of stickers.

@Fatih20 Are you okay with not supporting this feature? If you have already put together a sticker pack, I can keep this feature request around; however, if you haven't made any progress on this feature, I think it will be best to wontfix it.

**Comment by Fatih20** [comment]
It's fine.

**Comment by phase1geo** [comment]
Going ahead with wontfixing this issue.
