### ISSUE TITLE
Provide Prebuild DEB

### ISSUE THREAD

**Issue by amxmln** [phase1geo/Minder#99]
Hi, first of all, let me say that this is an awesome application. Great work! I would love to use it, but since I don’t use just elementaryOS, but also multiple other Debian-based distributions in parallel, I was wondering if you could offer a pre-built .deb as part of the releases?

I guess this issue could partially fixed by providing the app as a Flatpak, but if it’s not too much trouble for you, I’d still prefer a .deb.

I completely understand if that’s beyond the scope of your vision for this project, I just figured it couldn’t hurt asking.

Cheers and keep up the great work!

**Comment by phase1geo** [comment]
To be honest, I haven’t created any packages for Minder to date. Other users have made it available for other non-elementary systems. Obviously, elementary OS packages the Debian package for elementary. I have the Debian packaging files in the Minder repo so if someone wanted to  Debian file, I presume they should have everything they need.

**Comment by phase1geo** [comment]
Putting a help wanted label to see if anyone else wants to take this packaging request on.

**Comment by phase1geo** [comment]
Closing out this issue since it appears no one wants to take on this task.
